// <auto-generated>
//  This code was generated by a tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
// </auto-generated>
namespace Commons.Packets.Updates
{
   public partial class PlayerItemUpdate : IUpdate {}
   public partial class PlayerAvatarUpdate : IUpdate {}
   public partial class PlayerAchievementUpdate : IUpdate {}
   public partial class PlayerUpdate : IUpdate {}
   public partial class PlayerAcquiredItemsUpdate : IUpdate {}
   public partial class PlayerDisplayMessageUpdate : IUpdate {}
   public partial class PlayerDisconnectedUpdate : IUpdate {}
   public partial class PlayerChatUpdate : IUpdate {}
   public partial class BoardPlayerUpdate : IUpdate, IBoardUpdate {}
   public partial class BoardAchievementUpdate : IUpdate, IBoardUpdate {}
   public partial class BoardPlayerInventoryMergeUpdate : IUpdate, IBoardUpdate {}
   public partial class BoardPlayerInventorySpawnUpdate : IUpdate, IBoardUpdate {}
   public partial class BoardPlayerInventoryMoveUpdate : IUpdate, IBoardUpdate {}
   public partial class BoardPlayerInventoryTransferUpdate : IUpdate, IBoardUpdate {}
   public partial class BoardPlayerInventoryExpandUpdate : IUpdate, IBoardUpdate {}
   public partial class BoardPlayerInventoryResetHoldUpdate : IUpdate, IBoardUpdate {}
   public partial class VariableUpdate : IUpdate, IBoardUpdate {}
   public partial class SelectTraitUpdate : IUpdate, IBoardUpdate {}
   public partial class CompleteSelectTraitUpdate : IUpdate, IBoardUpdate {}
   public partial class BoardStateUpdate : IUpdate, IBoardUpdate {}
   public partial class BoardPlayerRunCheatUpdate : IUpdate, IBoardUpdate {}
   public partial class RerollSelectTraitUpdate : IUpdate, IBoardUpdate {}
   public partial class BoardPlayerInventoryRootingUpdate : IUpdate, IBoardUpdate {}
}
