id: 110305
name: "행운 젤리"
type: Normal
tags: [Monster]
armorType: NormalArmor
warmupDelay: 0.8
targetMode: Chaser
targetAwareDistance: 24.0
targetResetDistance: 30.0
deadDestroyDelaySeconds: 0.4

addStats:
  - { type: Hp, value: [220.0] }
  - { type: Attack, value: [20.0] }
  - { type: Defense, value: [6.0] }
  - { type: AttackSpeed, value: [1.2] }
  - { type: MoveSpeed, value: [3.2] }
  - { type: Luck, value: [20.0] }
  - { type: ScalePercent, value: [-63.0] }

triggers:
  - UNIT_ONSTART_WEEKDAYLUCKYJELLYSTART
  - UNIT_ONUPDATE_WEEKDAYLUCKYJELLYATTACK

dropAddItemGroups:
  - shouldAddAll: false
    probPercent: 75
    addItems:
      - { itemDataId: 200111, count: 2, weight: 55, group: 1 }
      - { itemDataId: 200112, count: 1, weight: 35, group: 1 }
      - { itemDataId: 200113, count: 1, weight: 10, group: 1, pityGroup: 6 }
  - shouldAddAll: true
    probPercent: 100
    addItems:
      - { itemDataId: 5, minCount: 35, maxCount: 70 }

prefab: "Units/Monsters/melee_slime3_yellow.prefab"
sprite: "Units/Monsters/Assets/melle_slime3.png"
animations:
  Idle: Idle
  Run: Run
  Attack: Attack1
  Dead: Dead
uiScale: 0.96
collideSize: { x: 0.85, y: 0.85 }
hitSize: { x: 0.95, y: 0.95 }
