using System.Text;
using System.Text.RegularExpressions;

namespace Generators;

internal static class WorldServer_WorldPlayer_Handler_Update_Generator
{
    private static void Main(string[] args)
    {
        var solutionRoot = Directory.GetCurrentDirectory().Split("Generators")[0]; 

        var protoPath = solutionRoot + $@"\Commons\Packets\Updates\Updates.proto";
        var outputFilePath = solutionRoot + $@"\WorldServer\WorldPlayer\Handler\WorldPlayer.Handler.Update.generated.cs";
        
        Console.WriteLine("proto path: " + protoPath);

        if (!File.Exists(protoPath))
        {
            Console.WriteLine("😒 Proto file not found");
            return;
        }
        
        var regex = new Regex(@"^\s*([a-zA-Z0-9\.]+)\s+([a-zA-Z0-9_]+)\s*=\s*\d+;");

        var messages = new List<string>();
        using (var reader = new StreamReader(protoPath))
        {
            var isRequestSection = false;
            while (reader.ReadLine() is { } line)
            {
                if (line.Contains($"oneof Update"))
                {
                    isRequestSection = true;
                    continue;
                }

                if (!isRequestSection)
                    continue;

                if (line.Contains('}'))
                    break;

                if (line.Contains("--ignore-server-handle"))
                    continue;

                var match = regex.Match(line);
                if (match.Success)
                {
                    var name = match.Groups[1].Value;
                    messages.Add(name);
                }
            }
        }
        
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//  This code was generated by a tool.");
        sb.AppendLine("//");
        sb.AppendLine("//  Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//  the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using Commons;");
        sb.AppendLine($"using Commons.Packets.Updates;");
        sb.AppendLine();
        sb.AppendLine("// ReSharper disable once CheckNamespace");
        sb.AppendLine("namespace WorldServer.WorldPlayer;");
        sb.AppendLine();
        sb.AppendLine("public partial class WorldPlayer");
        sb.AppendLine("{");
        foreach (var message in messages)
        {
            sb.AppendLine(@$"   private partial Task<bool> HandlePacket({message} update);");
        }
        sb.AppendLine();
        sb.AppendLine(@$"   private async Task<bool> HandleUpdate(Update update)");
        sb.AppendLine(@"    {");
        sb.AppendLine(@$"       switch (update.UpdateCase)");
        sb.AppendLine(@"        {");
        foreach (var message in messages)
        {
            sb.AppendLine(@$"           case Update.UpdateOneofCase.{message}:");
            sb.AppendLine(@$"               return await HandlePacket(update.{message}).ConfigureAwait(false);");
        }
        sb.AppendLine(@"            default:");
        sb.AppendLine(@"                if (Config.IsDebug)");
        sb.AppendLine($$"""
                                            Logger.Info($"Invalid Update case {update.UpdateCase}");
                        """);
        sb.AppendLine(@"                return false;");
        sb.AppendLine(@"        }");
        sb.AppendLine(@"    }");
        sb.AppendLine("}");
        
        if (Path.GetDirectoryName(outputFilePath) is { } directoryName)
        {
            Directory.CreateDirectory(directoryName);
            File.WriteAllText(outputFilePath, sb.ToString());
            
            Console.WriteLine($"👍 Successfully generated packet response extension. generate to {outputFilePath}");
        }
        else
        {
            Console.WriteLine($"😒 Failed to generate packet response extension. generate to {outputFilePath}");
        }
    }
    
}