// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ItemGroupStatType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Commons.Types.Units.ItemGroupStat {

  /// <summary>Holder for reflection information generated from ItemGroupStatType.proto</summary>
  public static partial class ItemGroupStatTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for ItemGroupStatType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemGroupStatTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdJdGVtR3JvdXBTdGF0VHlwZS5wcm90bxIhQ29tbW9ucy5UeXBlcy5Vbml0",
            "cy5JdGVtR3JvdXBTdGF0InkKEEFkZEl0ZW1Hcm91cFN0YXQSQgoEdHlwZRgB",
            "IAEoDjI0LkNvbW1vbnMuVHlwZXMuVW5pdHMuSXRlbUdyb3VwU3RhdC5JdGVt",
            "R3JvdXBTdGF0VHlwZRISCgppdGVtR3JvdXBzGAIgAygFEg0KBXZhbHVlGAMg",
            "AygCKqkBChFJdGVtR3JvdXBTdGF0VHlwZRIRCg1EYW1hZ2VQZXJjZW50EAAS",
            "EwoPQ29vbGRvd25QZXJjZW50EAESEwoPQ3JpdGljYWxQZXJjZW50EAISGQoV",
            "Q3JpdGljYWxEYW1hZ2VQZXJjZW50EAMSFAoQS25vY2tiYWNrUGVyY2VudBAE",
            "EhsKF0FkZGl0aW9uYWxBdHRhY2tQZXJjZW50EAUSCQoFQ291bnQQBmIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Commons.Types.Units.ItemGroupStat.ItemGroupStatType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Types.Units.ItemGroupStat.AddItemGroupStat), global::Commons.Types.Units.ItemGroupStat.AddItemGroupStat.Parser, new[]{ "Type", "ItemGroups", "Value" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ItemGroupStatType {
    [pbr::OriginalName("DamagePercent")] DamagePercent = 0,
    [pbr::OriginalName("CooldownPercent")] CooldownPercent = 1,
    [pbr::OriginalName("CriticalPercent")] CriticalPercent = 2,
    [pbr::OriginalName("CriticalDamagePercent")] CriticalDamagePercent = 3,
    [pbr::OriginalName("KnockbackPercent")] KnockbackPercent = 4,
    [pbr::OriginalName("AdditionalAttackPercent")] AdditionalAttackPercent = 5,
    [pbr::OriginalName("Count")] Count = 6,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AddItemGroupStat : pb::IMessage<AddItemGroupStat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AddItemGroupStat> _parser = new pb::MessageParser<AddItemGroupStat>(() => new AddItemGroupStat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AddItemGroupStat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Commons.Types.Units.ItemGroupStat.ItemGroupStatTypeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddItemGroupStat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddItemGroupStat(AddItemGroupStat other) : this() {
      type_ = other.type_;
      itemGroups_ = other.itemGroups_.Clone();
      value_ = other.value_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddItemGroupStat Clone() {
      return new AddItemGroupStat(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Commons.Types.Units.ItemGroupStat.ItemGroupStatType type_ = global::Commons.Types.Units.ItemGroupStat.ItemGroupStatType.DamagePercent;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Units.ItemGroupStat.ItemGroupStatType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "itemGroups" field.</summary>
    public const int ItemGroupsFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_itemGroups_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> itemGroups_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> ItemGroups {
      get { return itemGroups_; }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 3;
    private static readonly pb::FieldCodec<float> _repeated_value_codec
        = pb::FieldCodec.ForFloat(26);
    private readonly pbc::RepeatedField<float> value_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Value {
      get { return value_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AddItemGroupStat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AddItemGroupStat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if(!itemGroups_.Equals(other.itemGroups_)) return false;
      if(!value_.Equals(other.value_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Commons.Types.Units.ItemGroupStat.ItemGroupStatType.DamagePercent) hash ^= Type.GetHashCode();
      hash ^= itemGroups_.GetHashCode();
      hash ^= value_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Commons.Types.Units.ItemGroupStat.ItemGroupStatType.DamagePercent) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      itemGroups_.WriteTo(output, _repeated_itemGroups_codec);
      value_.WriteTo(output, _repeated_value_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Commons.Types.Units.ItemGroupStat.ItemGroupStatType.DamagePercent) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      itemGroups_.WriteTo(ref output, _repeated_itemGroups_codec);
      value_.WriteTo(ref output, _repeated_value_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Commons.Types.Units.ItemGroupStat.ItemGroupStatType.DamagePercent) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      size += itemGroups_.CalculateSize(_repeated_itemGroups_codec);
      size += value_.CalculateSize(_repeated_value_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AddItemGroupStat other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Commons.Types.Units.ItemGroupStat.ItemGroupStatType.DamagePercent) {
        Type = other.Type;
      }
      itemGroups_.Add(other.itemGroups_);
      value_.Add(other.value_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Commons.Types.Units.ItemGroupStat.ItemGroupStatType) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            itemGroups_.AddEntriesFrom(input, _repeated_itemGroups_codec);
            break;
          }
          case 26:
          case 29: {
            value_.AddEntriesFrom(input, _repeated_value_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Commons.Types.Units.ItemGroupStat.ItemGroupStatType) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            itemGroups_.AddEntriesFrom(ref input, _repeated_itemGroups_codec);
            break;
          }
          case 26:
          case 29: {
            value_.AddEntriesFrom(ref input, _repeated_value_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
