// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ResourceGlobal.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Commons.Resources {

  /// <summary>Holder for reflection information generated from ResourceGlobal.proto</summary>
  public static partial class ResourceGlobalReflection {

    #region Descriptor
    /// <summary>File descriptor for ResourceGlobal.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResourceGlobalReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRSZXNvdXJjZUdsb2JhbC5wcm90bxIRQ29tbW9ucy5SZXNvdXJjZXMaClRh",
            "Z3MucHJvdG8aElJlc291cmNlQnVmZi5wcm90bxoSUmVzb3VyY2VJdGVtLnBy",
            "b3RvGhFSZXNvdXJjZU1hcC5wcm90bxoTUmVzb3VyY2VTa2lsbC5wcm90bxoU",
            "UmVzb3VyY2VTdHJpbmcucHJvdG8aFVJlc291cmNlVHJpZ2dlci5wcm90bxoS",
            "UmVzb3VyY2VVbml0LnByb3RvIv4DCg5SZXNvdXJjZUdsb2JhbBIKCgJpZBgB",
            "IAEoBRIkCgR0YWdzGAIgAygOMhYuQ29tbW9ucy5SZXNvdXJjZXMuVGFnEjwK",
            "E1Jlc291cmNlQnVmZkdsb2JhbHMYAyADKAsyHy5Db21tb25zLlJlc291cmNl",
            "cy5SZXNvdXJjZUJ1ZmYSPAoTUmVzb3VyY2VJdGVtR2xvYmFscxgEIAMoCzIf",
            "LkNvbW1vbnMuUmVzb3VyY2VzLlJlc291cmNlSXRlbRI6ChJSZXNvdXJjZU1h",
            "cEdsb2JhbHMYBSADKAsyHi5Db21tb25zLlJlc291cmNlcy5SZXNvdXJjZU1h",
            "cBI+ChRSZXNvdXJjZVNraWxsR2xvYmFscxgGIAMoCzIgLkNvbW1vbnMuUmVz",
            "b3VyY2VzLlJlc291cmNlU2tpbGwSQAoVUmVzb3VyY2VTdHJpbmdHbG9iYWxz",
            "GAcgAygLMiEuQ29tbW9ucy5SZXNvdXJjZXMuUmVzb3VyY2VTdHJpbmcSQgoW",
            "UmVzb3VyY2VUcmlnZ2VyR2xvYmFscxgIIAMoCzIiLkNvbW1vbnMuUmVzb3Vy",
            "Y2VzLlJlc291cmNlVHJpZ2dlchI8ChNSZXNvdXJjZVVuaXRHbG9iYWxzGAkg",
            "AygLMh8uQ29tbW9ucy5SZXNvdXJjZXMuUmVzb3VyY2VVbml0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Commons.Resources.TagsReflection.Descriptor, global::Commons.Resources.ResourceBuffReflection.Descriptor, global::Commons.Resources.ResourceItemReflection.Descriptor, global::Commons.Resources.ResourceMapReflection.Descriptor, global::Commons.Resources.ResourceSkillReflection.Descriptor, global::Commons.Resources.ResourceStringReflection.Descriptor, global::Commons.Resources.ResourceTriggerReflection.Descriptor, global::Commons.Resources.ResourceUnitReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Resources.ResourceGlobal), global::Commons.Resources.ResourceGlobal.Parser, new[]{ "Id", "Tags", "ResourceBuffGlobals", "ResourceItemGlobals", "ResourceMapGlobals", "ResourceSkillGlobals", "ResourceStringGlobals", "ResourceTriggerGlobals", "ResourceUnitGlobals" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResourceGlobal : pb::IMessage<ResourceGlobal>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResourceGlobal> _parser = new pb::MessageParser<ResourceGlobal>(() => new ResourceGlobal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResourceGlobal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Commons.Resources.ResourceGlobalReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceGlobal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceGlobal(ResourceGlobal other) : this() {
      id_ = other.id_;
      tags_ = other.tags_.Clone();
      resourceBuffGlobals_ = other.resourceBuffGlobals_.Clone();
      resourceItemGlobals_ = other.resourceItemGlobals_.Clone();
      resourceMapGlobals_ = other.resourceMapGlobals_.Clone();
      resourceSkillGlobals_ = other.resourceSkillGlobals_.Clone();
      resourceStringGlobals_ = other.resourceStringGlobals_.Clone();
      resourceTriggerGlobals_ = other.resourceTriggerGlobals_.Clone();
      resourceUnitGlobals_ = other.resourceUnitGlobals_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceGlobal Clone() {
      return new ResourceGlobal(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "tags" field.</summary>
    public const int TagsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Commons.Resources.Tag> _repeated_tags_codec
        = pb::FieldCodec.ForEnum(18, x => (int) x, x => (global::Commons.Resources.Tag) x);
    private readonly pbc::RepeatedField<global::Commons.Resources.Tag> tags_ = new pbc::RepeatedField<global::Commons.Resources.Tag>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Resources.Tag> Tags {
      get { return tags_; }
    }

    /// <summary>Field number for the "ResourceBuffGlobals" field.</summary>
    public const int ResourceBuffGlobalsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Commons.Resources.ResourceBuff> _repeated_resourceBuffGlobals_codec
        = pb::FieldCodec.ForMessage(26, global::Commons.Resources.ResourceBuff.Parser);
    private readonly pbc::RepeatedField<global::Commons.Resources.ResourceBuff> resourceBuffGlobals_ = new pbc::RepeatedField<global::Commons.Resources.ResourceBuff>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Resources.ResourceBuff> ResourceBuffGlobals {
      get { return resourceBuffGlobals_; }
    }

    /// <summary>Field number for the "ResourceItemGlobals" field.</summary>
    public const int ResourceItemGlobalsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Commons.Resources.ResourceItem> _repeated_resourceItemGlobals_codec
        = pb::FieldCodec.ForMessage(34, global::Commons.Resources.ResourceItem.Parser);
    private readonly pbc::RepeatedField<global::Commons.Resources.ResourceItem> resourceItemGlobals_ = new pbc::RepeatedField<global::Commons.Resources.ResourceItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Resources.ResourceItem> ResourceItemGlobals {
      get { return resourceItemGlobals_; }
    }

    /// <summary>Field number for the "ResourceMapGlobals" field.</summary>
    public const int ResourceMapGlobalsFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Commons.Resources.ResourceMap> _repeated_resourceMapGlobals_codec
        = pb::FieldCodec.ForMessage(42, global::Commons.Resources.ResourceMap.Parser);
    private readonly pbc::RepeatedField<global::Commons.Resources.ResourceMap> resourceMapGlobals_ = new pbc::RepeatedField<global::Commons.Resources.ResourceMap>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Resources.ResourceMap> ResourceMapGlobals {
      get { return resourceMapGlobals_; }
    }

    /// <summary>Field number for the "ResourceSkillGlobals" field.</summary>
    public const int ResourceSkillGlobalsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Commons.Resources.ResourceSkill> _repeated_resourceSkillGlobals_codec
        = pb::FieldCodec.ForMessage(50, global::Commons.Resources.ResourceSkill.Parser);
    private readonly pbc::RepeatedField<global::Commons.Resources.ResourceSkill> resourceSkillGlobals_ = new pbc::RepeatedField<global::Commons.Resources.ResourceSkill>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Resources.ResourceSkill> ResourceSkillGlobals {
      get { return resourceSkillGlobals_; }
    }

    /// <summary>Field number for the "ResourceStringGlobals" field.</summary>
    public const int ResourceStringGlobalsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Commons.Resources.ResourceString> _repeated_resourceStringGlobals_codec
        = pb::FieldCodec.ForMessage(58, global::Commons.Resources.ResourceString.Parser);
    private readonly pbc::RepeatedField<global::Commons.Resources.ResourceString> resourceStringGlobals_ = new pbc::RepeatedField<global::Commons.Resources.ResourceString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Resources.ResourceString> ResourceStringGlobals {
      get { return resourceStringGlobals_; }
    }

    /// <summary>Field number for the "ResourceTriggerGlobals" field.</summary>
    public const int ResourceTriggerGlobalsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Commons.Resources.ResourceTrigger> _repeated_resourceTriggerGlobals_codec
        = pb::FieldCodec.ForMessage(66, global::Commons.Resources.ResourceTrigger.Parser);
    private readonly pbc::RepeatedField<global::Commons.Resources.ResourceTrigger> resourceTriggerGlobals_ = new pbc::RepeatedField<global::Commons.Resources.ResourceTrigger>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Resources.ResourceTrigger> ResourceTriggerGlobals {
      get { return resourceTriggerGlobals_; }
    }

    /// <summary>Field number for the "ResourceUnitGlobals" field.</summary>
    public const int ResourceUnitGlobalsFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Commons.Resources.ResourceUnit> _repeated_resourceUnitGlobals_codec
        = pb::FieldCodec.ForMessage(74, global::Commons.Resources.ResourceUnit.Parser);
    private readonly pbc::RepeatedField<global::Commons.Resources.ResourceUnit> resourceUnitGlobals_ = new pbc::RepeatedField<global::Commons.Resources.ResourceUnit>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Resources.ResourceUnit> ResourceUnitGlobals {
      get { return resourceUnitGlobals_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResourceGlobal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResourceGlobal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if(!tags_.Equals(other.tags_)) return false;
      if(!resourceBuffGlobals_.Equals(other.resourceBuffGlobals_)) return false;
      if(!resourceItemGlobals_.Equals(other.resourceItemGlobals_)) return false;
      if(!resourceMapGlobals_.Equals(other.resourceMapGlobals_)) return false;
      if(!resourceSkillGlobals_.Equals(other.resourceSkillGlobals_)) return false;
      if(!resourceStringGlobals_.Equals(other.resourceStringGlobals_)) return false;
      if(!resourceTriggerGlobals_.Equals(other.resourceTriggerGlobals_)) return false;
      if(!resourceUnitGlobals_.Equals(other.resourceUnitGlobals_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      hash ^= tags_.GetHashCode();
      hash ^= resourceBuffGlobals_.GetHashCode();
      hash ^= resourceItemGlobals_.GetHashCode();
      hash ^= resourceMapGlobals_.GetHashCode();
      hash ^= resourceSkillGlobals_.GetHashCode();
      hash ^= resourceStringGlobals_.GetHashCode();
      hash ^= resourceTriggerGlobals_.GetHashCode();
      hash ^= resourceUnitGlobals_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      tags_.WriteTo(output, _repeated_tags_codec);
      resourceBuffGlobals_.WriteTo(output, _repeated_resourceBuffGlobals_codec);
      resourceItemGlobals_.WriteTo(output, _repeated_resourceItemGlobals_codec);
      resourceMapGlobals_.WriteTo(output, _repeated_resourceMapGlobals_codec);
      resourceSkillGlobals_.WriteTo(output, _repeated_resourceSkillGlobals_codec);
      resourceStringGlobals_.WriteTo(output, _repeated_resourceStringGlobals_codec);
      resourceTriggerGlobals_.WriteTo(output, _repeated_resourceTriggerGlobals_codec);
      resourceUnitGlobals_.WriteTo(output, _repeated_resourceUnitGlobals_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      tags_.WriteTo(ref output, _repeated_tags_codec);
      resourceBuffGlobals_.WriteTo(ref output, _repeated_resourceBuffGlobals_codec);
      resourceItemGlobals_.WriteTo(ref output, _repeated_resourceItemGlobals_codec);
      resourceMapGlobals_.WriteTo(ref output, _repeated_resourceMapGlobals_codec);
      resourceSkillGlobals_.WriteTo(ref output, _repeated_resourceSkillGlobals_codec);
      resourceStringGlobals_.WriteTo(ref output, _repeated_resourceStringGlobals_codec);
      resourceTriggerGlobals_.WriteTo(ref output, _repeated_resourceTriggerGlobals_codec);
      resourceUnitGlobals_.WriteTo(ref output, _repeated_resourceUnitGlobals_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      size += tags_.CalculateSize(_repeated_tags_codec);
      size += resourceBuffGlobals_.CalculateSize(_repeated_resourceBuffGlobals_codec);
      size += resourceItemGlobals_.CalculateSize(_repeated_resourceItemGlobals_codec);
      size += resourceMapGlobals_.CalculateSize(_repeated_resourceMapGlobals_codec);
      size += resourceSkillGlobals_.CalculateSize(_repeated_resourceSkillGlobals_codec);
      size += resourceStringGlobals_.CalculateSize(_repeated_resourceStringGlobals_codec);
      size += resourceTriggerGlobals_.CalculateSize(_repeated_resourceTriggerGlobals_codec);
      size += resourceUnitGlobals_.CalculateSize(_repeated_resourceUnitGlobals_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResourceGlobal other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      tags_.Add(other.tags_);
      resourceBuffGlobals_.Add(other.resourceBuffGlobals_);
      resourceItemGlobals_.Add(other.resourceItemGlobals_);
      resourceMapGlobals_.Add(other.resourceMapGlobals_);
      resourceSkillGlobals_.Add(other.resourceSkillGlobals_);
      resourceStringGlobals_.Add(other.resourceStringGlobals_);
      resourceTriggerGlobals_.Add(other.resourceTriggerGlobals_);
      resourceUnitGlobals_.Add(other.resourceUnitGlobals_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            tags_.AddEntriesFrom(input, _repeated_tags_codec);
            break;
          }
          case 26: {
            resourceBuffGlobals_.AddEntriesFrom(input, _repeated_resourceBuffGlobals_codec);
            break;
          }
          case 34: {
            resourceItemGlobals_.AddEntriesFrom(input, _repeated_resourceItemGlobals_codec);
            break;
          }
          case 42: {
            resourceMapGlobals_.AddEntriesFrom(input, _repeated_resourceMapGlobals_codec);
            break;
          }
          case 50: {
            resourceSkillGlobals_.AddEntriesFrom(input, _repeated_resourceSkillGlobals_codec);
            break;
          }
          case 58: {
            resourceStringGlobals_.AddEntriesFrom(input, _repeated_resourceStringGlobals_codec);
            break;
          }
          case 66: {
            resourceTriggerGlobals_.AddEntriesFrom(input, _repeated_resourceTriggerGlobals_codec);
            break;
          }
          case 74: {
            resourceUnitGlobals_.AddEntriesFrom(input, _repeated_resourceUnitGlobals_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            tags_.AddEntriesFrom(ref input, _repeated_tags_codec);
            break;
          }
          case 26: {
            resourceBuffGlobals_.AddEntriesFrom(ref input, _repeated_resourceBuffGlobals_codec);
            break;
          }
          case 34: {
            resourceItemGlobals_.AddEntriesFrom(ref input, _repeated_resourceItemGlobals_codec);
            break;
          }
          case 42: {
            resourceMapGlobals_.AddEntriesFrom(ref input, _repeated_resourceMapGlobals_codec);
            break;
          }
          case 50: {
            resourceSkillGlobals_.AddEntriesFrom(ref input, _repeated_resourceSkillGlobals_codec);
            break;
          }
          case 58: {
            resourceStringGlobals_.AddEntriesFrom(ref input, _repeated_resourceStringGlobals_codec);
            break;
          }
          case 66: {
            resourceTriggerGlobals_.AddEntriesFrom(ref input, _repeated_resourceTriggerGlobals_codec);
            break;
          }
          case 74: {
            resourceUnitGlobals_.AddEntriesFrom(ref input, _repeated_resourceUnitGlobals_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
