// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ResourceAudio.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Commons.Resources {

  /// <summary>Holder for reflection information generated from ResourceAudio.proto</summary>
  public static partial class ResourceAudioReflection {

    #region Descriptor
    /// <summary>File descriptor for ResourceAudio.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResourceAudioReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNSZXNvdXJjZUF1ZGlvLnByb3RvEhFDb21tb25zLlJlc291cmNlcxoKVGFn",
            "cy5wcm90byKABAoNUmVzb3VyY2VBdWRpbxIkCgR0YWdzGAEgAygOMhYuQ29t",
            "bW9ucy5SZXNvdXJjZXMuVGFnEgoKAmlkGGQgASgFEjMKBHR5cGUYZSABKA4y",
            "JS5Db21tb25zLlJlc291cmNlcy5SZXNvdXJjZUF1ZGlvLlR5cGUSDQoEbmFt",
            "ZRjIASABKAkSDwoGcHJlZmFiGMkBIAEoCRIOCgVkZWxheRisAiABKAISDwoG",
            "dm9sdW1lGK0CIAEoAhIcChNtaW5UaW1lQmV0d2VlblBsYXlzGK4CIAEoAhIZ",
            "ChBtYXhJbnN0YW5jZUNvdW50GK8CIAEoBRJACgpoYXB0aWNUeXBlGJADIAEo",
            "DjIrLkNvbW1vbnMuUmVzb3VyY2VzLlJlc291cmNlQXVkaW8uSGFwdGljVHlw",
            "ZRIUCgtoYXB0aWNEZWxheRiRAyABKAIaUgoGR2xvYmFsEj4KBmRhdGFJZBgB",
            "IAEoCzIuLkNvbW1vbnMuUmVzb3VyY2VzLlJlc291cmNlQXVkaW8uR2xvYmFs",
            "LkRhdGFJZBoICgZEYXRhSWQiKAoEVHlwZRIPCgtVbnNwZWNpZmllZBAAEgcK",
            "A0JnbRABEgYKAkZ4EAIiOAoKSGFwdGljVHlwZRIICgROb25lEAASCQoFU21h",
            "bGwQARIKCgZNZWRpdW0QAhIJCgVMYXJnZRADYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Commons.Resources.TagsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Resources.ResourceAudio), global::Commons.Resources.ResourceAudio.Parser, new[]{ "Tags", "Id", "Type", "Name", "Prefab", "Delay", "Volume", "MinTimeBetweenPlays", "MaxInstanceCount", "HapticType", "HapticDelay" }, null, new[]{ typeof(global::Commons.Resources.ResourceAudio.Types.Type), typeof(global::Commons.Resources.ResourceAudio.Types.HapticType) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Resources.ResourceAudio.Types.Global), global::Commons.Resources.ResourceAudio.Types.Global.Parser, new[]{ "DataId" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Resources.ResourceAudio.Types.Global.Types.DataId), global::Commons.Resources.ResourceAudio.Types.Global.Types.DataId.Parser, null, null, null, null, null)})})
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResourceAudio : pb::IMessage<ResourceAudio>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResourceAudio> _parser = new pb::MessageParser<ResourceAudio>(() => new ResourceAudio());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResourceAudio> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Commons.Resources.ResourceAudioReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceAudio() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceAudio(ResourceAudio other) : this() {
      tags_ = other.tags_.Clone();
      id_ = other.id_;
      type_ = other.type_;
      name_ = other.name_;
      prefab_ = other.prefab_;
      delay_ = other.delay_;
      volume_ = other.volume_;
      minTimeBetweenPlays_ = other.minTimeBetweenPlays_;
      maxInstanceCount_ = other.maxInstanceCount_;
      hapticType_ = other.hapticType_;
      hapticDelay_ = other.hapticDelay_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResourceAudio Clone() {
      return new ResourceAudio(this);
    }

    /// <summary>Field number for the "tags" field.</summary>
    public const int TagsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Commons.Resources.Tag> _repeated_tags_codec
        = pb::FieldCodec.ForEnum(10, x => (int) x, x => (global::Commons.Resources.Tag) x);
    private readonly pbc::RepeatedField<global::Commons.Resources.Tag> tags_ = new pbc::RepeatedField<global::Commons.Resources.Tag>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Resources.Tag> Tags {
      get { return tags_; }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 100;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 101;
    private global::Commons.Resources.ResourceAudio.Types.Type type_ = global::Commons.Resources.ResourceAudio.Types.Type.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Resources.ResourceAudio.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 200;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prefab" field.</summary>
    public const int PrefabFieldNumber = 201;
    private string prefab_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Prefab {
      get { return prefab_; }
      set {
        prefab_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "delay" field.</summary>
    public const int DelayFieldNumber = 300;
    private float delay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Delay {
      get { return delay_; }
      set {
        delay_ = value;
      }
    }

    /// <summary>Field number for the "volume" field.</summary>
    public const int VolumeFieldNumber = 301;
    private float volume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Volume {
      get { return volume_; }
      set {
        volume_ = value;
      }
    }

    /// <summary>Field number for the "minTimeBetweenPlays" field.</summary>
    public const int MinTimeBetweenPlaysFieldNumber = 302;
    private float minTimeBetweenPlays_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MinTimeBetweenPlays {
      get { return minTimeBetweenPlays_; }
      set {
        minTimeBetweenPlays_ = value;
      }
    }

    /// <summary>Field number for the "maxInstanceCount" field.</summary>
    public const int MaxInstanceCountFieldNumber = 303;
    private int maxInstanceCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxInstanceCount {
      get { return maxInstanceCount_; }
      set {
        maxInstanceCount_ = value;
      }
    }

    /// <summary>Field number for the "hapticType" field.</summary>
    public const int HapticTypeFieldNumber = 400;
    private global::Commons.Resources.ResourceAudio.Types.HapticType hapticType_ = global::Commons.Resources.ResourceAudio.Types.HapticType.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Resources.ResourceAudio.Types.HapticType HapticType {
      get { return hapticType_; }
      set {
        hapticType_ = value;
      }
    }

    /// <summary>Field number for the "hapticDelay" field.</summary>
    public const int HapticDelayFieldNumber = 401;
    private float hapticDelay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float HapticDelay {
      get { return hapticDelay_; }
      set {
        hapticDelay_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResourceAudio);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResourceAudio other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!tags_.Equals(other.tags_)) return false;
      if (Id != other.Id) return false;
      if (Type != other.Type) return false;
      if (Name != other.Name) return false;
      if (Prefab != other.Prefab) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Delay, other.Delay)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Volume, other.Volume)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MinTimeBetweenPlays, other.MinTimeBetweenPlays)) return false;
      if (MaxInstanceCount != other.MaxInstanceCount) return false;
      if (HapticType != other.HapticType) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(HapticDelay, other.HapticDelay)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= tags_.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Type != global::Commons.Resources.ResourceAudio.Types.Type.Unspecified) hash ^= Type.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Prefab.Length != 0) hash ^= Prefab.GetHashCode();
      if (Delay != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Delay);
      if (Volume != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Volume);
      if (MinTimeBetweenPlays != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MinTimeBetweenPlays);
      if (MaxInstanceCount != 0) hash ^= MaxInstanceCount.GetHashCode();
      if (HapticType != global::Commons.Resources.ResourceAudio.Types.HapticType.None) hash ^= HapticType.GetHashCode();
      if (HapticDelay != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(HapticDelay);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      tags_.WriteTo(output, _repeated_tags_codec);
      if (Id != 0) {
        output.WriteRawTag(160, 6);
        output.WriteInt32(Id);
      }
      if (Type != global::Commons.Resources.ResourceAudio.Types.Type.Unspecified) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) Type);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(194, 12);
        output.WriteString(Name);
      }
      if (Prefab.Length != 0) {
        output.WriteRawTag(202, 12);
        output.WriteString(Prefab);
      }
      if (Delay != 0F) {
        output.WriteRawTag(229, 18);
        output.WriteFloat(Delay);
      }
      if (Volume != 0F) {
        output.WriteRawTag(237, 18);
        output.WriteFloat(Volume);
      }
      if (MinTimeBetweenPlays != 0F) {
        output.WriteRawTag(245, 18);
        output.WriteFloat(MinTimeBetweenPlays);
      }
      if (MaxInstanceCount != 0) {
        output.WriteRawTag(248, 18);
        output.WriteInt32(MaxInstanceCount);
      }
      if (HapticType != global::Commons.Resources.ResourceAudio.Types.HapticType.None) {
        output.WriteRawTag(128, 25);
        output.WriteEnum((int) HapticType);
      }
      if (HapticDelay != 0F) {
        output.WriteRawTag(141, 25);
        output.WriteFloat(HapticDelay);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      tags_.WriteTo(ref output, _repeated_tags_codec);
      if (Id != 0) {
        output.WriteRawTag(160, 6);
        output.WriteInt32(Id);
      }
      if (Type != global::Commons.Resources.ResourceAudio.Types.Type.Unspecified) {
        output.WriteRawTag(168, 6);
        output.WriteEnum((int) Type);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(194, 12);
        output.WriteString(Name);
      }
      if (Prefab.Length != 0) {
        output.WriteRawTag(202, 12);
        output.WriteString(Prefab);
      }
      if (Delay != 0F) {
        output.WriteRawTag(229, 18);
        output.WriteFloat(Delay);
      }
      if (Volume != 0F) {
        output.WriteRawTag(237, 18);
        output.WriteFloat(Volume);
      }
      if (MinTimeBetweenPlays != 0F) {
        output.WriteRawTag(245, 18);
        output.WriteFloat(MinTimeBetweenPlays);
      }
      if (MaxInstanceCount != 0) {
        output.WriteRawTag(248, 18);
        output.WriteInt32(MaxInstanceCount);
      }
      if (HapticType != global::Commons.Resources.ResourceAudio.Types.HapticType.None) {
        output.WriteRawTag(128, 25);
        output.WriteEnum((int) HapticType);
      }
      if (HapticDelay != 0F) {
        output.WriteRawTag(141, 25);
        output.WriteFloat(HapticDelay);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += tags_.CalculateSize(_repeated_tags_codec);
      if (Id != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Type != global::Commons.Resources.ResourceAudio.Types.Type.Unspecified) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Name.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Prefab.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Prefab);
      }
      if (Delay != 0F) {
        size += 2 + 4;
      }
      if (Volume != 0F) {
        size += 2 + 4;
      }
      if (MinTimeBetweenPlays != 0F) {
        size += 2 + 4;
      }
      if (MaxInstanceCount != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(MaxInstanceCount);
      }
      if (HapticType != global::Commons.Resources.ResourceAudio.Types.HapticType.None) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) HapticType);
      }
      if (HapticDelay != 0F) {
        size += 2 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResourceAudio other) {
      if (other == null) {
        return;
      }
      tags_.Add(other.tags_);
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Type != global::Commons.Resources.ResourceAudio.Types.Type.Unspecified) {
        Type = other.Type;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Prefab.Length != 0) {
        Prefab = other.Prefab;
      }
      if (other.Delay != 0F) {
        Delay = other.Delay;
      }
      if (other.Volume != 0F) {
        Volume = other.Volume;
      }
      if (other.MinTimeBetweenPlays != 0F) {
        MinTimeBetweenPlays = other.MinTimeBetweenPlays;
      }
      if (other.MaxInstanceCount != 0) {
        MaxInstanceCount = other.MaxInstanceCount;
      }
      if (other.HapticType != global::Commons.Resources.ResourceAudio.Types.HapticType.None) {
        HapticType = other.HapticType;
      }
      if (other.HapticDelay != 0F) {
        HapticDelay = other.HapticDelay;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            tags_.AddEntriesFrom(input, _repeated_tags_codec);
            break;
          }
          case 800: {
            Id = input.ReadInt32();
            break;
          }
          case 808: {
            Type = (global::Commons.Resources.ResourceAudio.Types.Type) input.ReadEnum();
            break;
          }
          case 1602: {
            Name = input.ReadString();
            break;
          }
          case 1610: {
            Prefab = input.ReadString();
            break;
          }
          case 2405: {
            Delay = input.ReadFloat();
            break;
          }
          case 2413: {
            Volume = input.ReadFloat();
            break;
          }
          case 2421: {
            MinTimeBetweenPlays = input.ReadFloat();
            break;
          }
          case 2424: {
            MaxInstanceCount = input.ReadInt32();
            break;
          }
          case 3200: {
            HapticType = (global::Commons.Resources.ResourceAudio.Types.HapticType) input.ReadEnum();
            break;
          }
          case 3213: {
            HapticDelay = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            tags_.AddEntriesFrom(ref input, _repeated_tags_codec);
            break;
          }
          case 800: {
            Id = input.ReadInt32();
            break;
          }
          case 808: {
            Type = (global::Commons.Resources.ResourceAudio.Types.Type) input.ReadEnum();
            break;
          }
          case 1602: {
            Name = input.ReadString();
            break;
          }
          case 1610: {
            Prefab = input.ReadString();
            break;
          }
          case 2405: {
            Delay = input.ReadFloat();
            break;
          }
          case 2413: {
            Volume = input.ReadFloat();
            break;
          }
          case 2421: {
            MinTimeBetweenPlays = input.ReadFloat();
            break;
          }
          case 2424: {
            MaxInstanceCount = input.ReadInt32();
            break;
          }
          case 3200: {
            HapticType = (global::Commons.Resources.ResourceAudio.Types.HapticType) input.ReadEnum();
            break;
          }
          case 3213: {
            HapticDelay = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ResourceAudio message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("Unspecified")] Unspecified = 0,
        [pbr::OriginalName("Bgm")] Bgm = 1,
        [pbr::OriginalName("Fx")] Fx = 2,
      }

      public enum HapticType {
        [pbr::OriginalName("None")] None = 0,
        [pbr::OriginalName("Small")] Small = 1,
        [pbr::OriginalName("Medium")] Medium = 2,
        [pbr::OriginalName("Large")] Large = 3,
      }

      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Global : pb::IMessage<Global>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Global> _parser = new pb::MessageParser<Global>(() => new Global());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Global> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Commons.Resources.ResourceAudio.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Global() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Global(Global other) : this() {
          dataId_ = other.dataId_ != null ? other.dataId_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Global Clone() {
          return new Global(this);
        }

        /// <summary>Field number for the "dataId" field.</summary>
        public const int DataIdFieldNumber = 1;
        private global::Commons.Resources.ResourceAudio.Types.Global.Types.DataId dataId_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::Commons.Resources.ResourceAudio.Types.Global.Types.DataId DataId {
          get { return dataId_; }
          set {
            dataId_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Global);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Global other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(DataId, other.DataId)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (dataId_ != null) hash ^= DataId.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (dataId_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(DataId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (dataId_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(DataId);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (dataId_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataId);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Global other) {
          if (other == null) {
            return;
          }
          if (other.dataId_ != null) {
            if (dataId_ == null) {
              DataId = new global::Commons.Resources.ResourceAudio.Types.Global.Types.DataId();
            }
            DataId.MergeFrom(other.DataId);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (dataId_ == null) {
                  DataId = new global::Commons.Resources.ResourceAudio.Types.Global.Types.DataId();
                }
                input.ReadMessage(DataId);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10: {
                if (dataId_ == null) {
                  DataId = new global::Commons.Resources.ResourceAudio.Types.Global.Types.DataId();
                }
                input.ReadMessage(DataId);
                break;
              }
            }
          }
        }
        #endif

        #region Nested types
        /// <summary>Container for nested types declared in the Global message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types {
          [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
          public sealed partial class DataId : pb::IMessage<DataId>
          #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              , pb::IBufferMessage
          #endif
          {
            private static readonly pb::MessageParser<DataId> _parser = new pb::MessageParser<DataId>(() => new DataId());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pb::MessageParser<DataId> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::Commons.Resources.ResourceAudio.Types.Global.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public DataId() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public DataId(DataId other) : this() {
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public DataId Clone() {
              return new DataId(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override bool Equals(object other) {
              return Equals(other as DataId);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public bool Equals(DataId other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override int GetHashCode() {
              int hash = 1;
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void WriteTo(pb::CodedOutputStream output) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              output.WriteRawMessage(this);
            #else
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
              if (_unknownFields != null) {
                _unknownFields.WriteTo(ref output);
              }
            }
            #endif

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public int CalculateSize() {
              int size = 0;
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(DataId other) {
              if (other == null) {
                return;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            public void MergeFrom(pb::CodedInputStream input) {
            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
              input.ReadRawMessage(this);
            #else
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                }
              }
            #endif
            }

            #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
            void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                    break;
                }
              }
            }
            #endif

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
