FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

ARG PROJECT_PATH

WORKDIR /src
COPY server/Server/. ./Server/
RUN rm -rf ./Server/Commons
COPY commons/. ./Server/Commons/
RUN dotnet restore "$PROJECT_PATH"
RUN dotnet publish "$PROJECT_PATH" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

ARG APP_DLL
ENV APP_DLL=$APP_DLL

WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["sh", "-c", "dotnet \"$APP_DLL\""]
