// <auto-generated>
//  This code was generated by a tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
// </auto-generated>
using Commons;
using Commons.Packets.Updates;

// ReSharper disable once CheckNamespace
namespace WorldServer.WorldPlayer;

public partial class WorldPlayer
{
   private partial Task<bool> HandlePacket(BoardPlayerUpdate update);
   private partial Task<bool> HandlePacket(BoardAchievementUpdate update);
   private partial Task<bool> HandlePacket(BoardPlayerInventoryMergeUpdate update);
   private partial Task<bool> HandlePacket(BoardPlayerInventorySpawnUpdate update);
   private partial Task<bool> HandlePacket(BoardPlayerInventoryMoveUpdate update);
   private partial Task<bool> HandlePacket(BoardPlayerInventoryTransferUpdate update);
   private partial Task<bool> HandlePacket(BoardPlayerInventoryExpandUpdate update);
   private partial Task<bool> HandlePacket(BoardPlayerInventoryResetHoldUpdate update);
   private partial Task<bool> HandlePacket(VariableUpdate update);
   private partial Task<bool> HandlePacket(SelectTraitUpdate update);
   private partial Task<bool> HandlePacket(CompleteSelectTraitUpdate update);
   private partial Task<bool> HandlePacket(BoardStateUpdate update);
   private partial Task<bool> HandlePacket(BoardPlayerRunCheatUpdate update);
   private partial Task<bool> HandlePacket(RerollSelectTraitUpdate update);
   private partial Task<bool> HandlePacket(BoardPlayerInventoryRootingUpdate update);

   private async Task<bool> HandleUpdate(Update update)
    {
       switch (update.UpdateCase)
        {
           case Update.UpdateOneofCase.BoardPlayerUpdate:
               return await HandlePacket(update.BoardPlayerUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.BoardAchievementUpdate:
               return await HandlePacket(update.BoardAchievementUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.BoardPlayerInventoryMergeUpdate:
               return await HandlePacket(update.BoardPlayerInventoryMergeUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.BoardPlayerInventorySpawnUpdate:
               return await HandlePacket(update.BoardPlayerInventorySpawnUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.BoardPlayerInventoryMoveUpdate:
               return await HandlePacket(update.BoardPlayerInventoryMoveUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.BoardPlayerInventoryTransferUpdate:
               return await HandlePacket(update.BoardPlayerInventoryTransferUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.BoardPlayerInventoryExpandUpdate:
               return await HandlePacket(update.BoardPlayerInventoryExpandUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.BoardPlayerInventoryResetHoldUpdate:
               return await HandlePacket(update.BoardPlayerInventoryResetHoldUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.VariableUpdate:
               return await HandlePacket(update.VariableUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.SelectTraitUpdate:
               return await HandlePacket(update.SelectTraitUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.CompleteSelectTraitUpdate:
               return await HandlePacket(update.CompleteSelectTraitUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.BoardStateUpdate:
               return await HandlePacket(update.BoardStateUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.BoardPlayerRunCheatUpdate:
               return await HandlePacket(update.BoardPlayerRunCheatUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.RerollSelectTraitUpdate:
               return await HandlePacket(update.RerollSelectTraitUpdate).ConfigureAwait(false);
           case Update.UpdateOneofCase.BoardPlayerInventoryRootingUpdate:
               return await HandlePacket(update.BoardPlayerInventoryRootingUpdate).ConfigureAwait(false);
            default:
                if (Config.IsDebug)
                    Logger.Info($"Invalid Update case {update.UpdateCase}");
                return false;
        }
    }
}
