// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Commons.Game.Actions
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct UnitChangePlayerAvatarWeaponSlotAction : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public UnitChangePlayerAvatarWeaponSlotAction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Tick { get { return __p.bb.GetUint(__p.bb_pos + 0); } }
  public void MutateTick(uint tick) { __p.bb.PutUint(__p.bb_pos + 0, tick); }
  public uint UnitId { get { return __p.bb.GetUint(__p.bb_pos + 4); } }
  public void MutateUnitId(uint unit_id) { __p.bb.PutUint(__p.bb_pos + 4, unit_id); }
  public int WeaponSlot { get { return __p.bb.GetInt(__p.bb_pos + 8); } }
  public void MutateWeaponSlot(int weapon_slot) { __p.bb.PutInt(__p.bb_pos + 8, weapon_slot); }

  public static Offset<Commons.Game.Actions.UnitChangePlayerAvatarWeaponSlotAction> CreateUnitChangePlayerAvatarWeaponSlotAction(FlatBufferBuilder builder, uint Tick, uint UnitId, int WeaponSlot) {
    builder.Prep(4, 12);
    builder.PutInt(WeaponSlot);
    builder.PutUint(UnitId);
    builder.PutUint(Tick);
    return new Offset<Commons.Game.Actions.UnitChangePlayerAvatarWeaponSlotAction>(builder.Offset);
  }
}


}
