// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Player.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Commons.Types.Players {

  /// <summary>Holder for reflection information generated from Player.proto</summary>
  public static partial class PlayerReflection {

    #region Descriptor
    /// <summary>File descriptor for Player.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxQbGF5ZXIucHJvdG8SFUNvbW1vbnMuVHlwZXMuUGxheWVycxoUUGxheWVy",
            "VGVsZWdyYW0ucHJvdG8aFVBsYXllckludmVudG9yeS5wcm90bxoQUGxheWVy",
            "SXRlbS5wcm90bxoXUGxheWVyQWNoaWV2ZW1lbnQucHJvdG8aDUFkZEl0ZW0u",
            "cHJvdG8izAEKDVBsYXllck1lc3NhZ2USCgoCaWQYASABKAMSDAoEbmFtZRgC",
            "IAEoCRINCgVsZXZlbBgEIAEoBRIPCgdpc0FkbWluGAYgASgIEg8KB2JvYXJk",
            "SWQYAyABKAMSDQoFcG93ZXIYByABKAMSIQoZYXZhdGFyQ2hhcmFjdGVySXRl",
            "bURhdGFJZBgIIAEoBRI+Cgh0ZWxlZ3JhbRgFIAEoCzIsLkNvbW1vbnMuVHlw",
            "ZXMuUGxheWVycy5QbGF5ZXJUZWxlZ3JhbU1lc3NhZ2UiugEKF1NlbGVjdFRy",
            "YWl0RXZlbnRNZXNzYWdlEkMKBXN0YXRlGAEgASgOMjQuQ29tbW9ucy5UeXBl",
            "cy5QbGF5ZXJzLlNlbGVjdFRyYWl0RXZlbnRNZXNzYWdlLlN0YXRlEjUKDnRy",
            "YWl0SXRlbUdyb3VwGAIgASgLMh0uQ29tbW9ucy5UeXBlcy5UcmFpdEl0ZW1H",
            "cm91cCIjCgVTdGF0ZRILCgdQZW5kaW5nEAASDQoJSW1tZWRpYXRlEAEi7QYK",
            "EkJvYXJkUGxheWVyTWVzc2FnZRIKCgJpZBgBIAEoAxIRCglieXRlc05hbWUY",
            "AiABKAwSDQoFbGV2ZWwYAyABKAUSEAoIaXRlbVN0YXQYBCADKAISDQoFa2ls",
            "bHMYBSABKAUSDgoGZGVhdGhzGAYgASgFEgwKBGdvbGQYByABKAMSCwoDZXhw",
            "GAggASgDEjsKC2ludmVudG9yaWVzGAkgAygLMiYuQ29tbW9ucy5UeXBlcy5Q",
            "bGF5ZXJzLlBsYXllckludmVudG9yeRJBChFyb290ZWRJbnZlbnRvcmllcxgT",
            "IAMoCzImLkNvbW1vbnMuVHlwZXMuUGxheWVycy5QbGF5ZXJJbnZlbnRvcnkS",
            "OwoJaG9sZEl0ZW1zGAogAygLMiguQ29tbW9ucy5UeXBlcy5QbGF5ZXJzLlBs",
            "YXllckl0ZW1NZXNzYWdlEj8KDWFjcXVpcmVkSXRlbXMYDCADKAsyKC5Db21t",
            "b25zLlR5cGVzLlBsYXllcnMuUGxheWVySXRlbU1lc3NhZ2USSQoIbWlzc2lv",
            "bnMYDSADKAsyNy5Db21tb25zLlR5cGVzLlBsYXllcnMuQm9hcmRQbGF5ZXJN",
            "ZXNzYWdlLk1pc3Npb25zRW50cnkSQQoPbGVhcm5hYmxlVHJhaXRzGA4gAygL",
            "MiguQ29tbW9ucy5UeXBlcy5QbGF5ZXJzLlBsYXllckl0ZW1NZXNzYWdlEj8K",
            "DWFwcGxpZWRUcmFpdHMYDyADKAsyKC5Db21tb25zLlR5cGVzLlBsYXllcnMu",
            "UGxheWVySXRlbU1lc3NhZ2USQQoPaW52ZW50b3J5U2tpbGxzGBIgAygLMigu",
            "Q29tbW9ucy5UeXBlcy5QbGF5ZXJzLlBsYXllckl0ZW1NZXNzYWdlEiAKGHJl",
            "cm9sbExldmVsVXBTZWxlY3RUcmFpdBgQIAEoBRJJChFzZWxlY3RUcmFpdEV2",
            "ZW50cxgRIAMoCzIuLkNvbW1vbnMuVHlwZXMuUGxheWVycy5TZWxlY3RUcmFp",
            "dEV2ZW50TWVzc2FnZRpgCg1NaXNzaW9uc0VudHJ5EgsKA2tleRgBIAEoBRI+",
            "CgV2YWx1ZRgCIAEoCzIvLkNvbW1vbnMuVHlwZXMuUGxheWVycy5QbGF5ZXJB",
            "Y2hpZXZlbWVudE1lc3NhZ2U6AjgBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Commons.Types.Players.PlayerTelegramReflection.Descriptor, global::Commons.Types.Players.PlayerInventoryReflection.Descriptor, global::Commons.Types.Players.PlayerItemReflection.Descriptor, global::Commons.Types.Players.PlayerAchievementReflection.Descriptor, global::Commons.Types.AddItemReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Types.Players.PlayerMessage), global::Commons.Types.Players.PlayerMessage.Parser, new[]{ "Id", "Name", "Level", "IsAdmin", "BoardId", "Power", "AvatarCharacterItemDataId", "Telegram" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Types.Players.SelectTraitEventMessage), global::Commons.Types.Players.SelectTraitEventMessage.Parser, new[]{ "State", "TraitItemGroup" }, null, new[]{ typeof(global::Commons.Types.Players.SelectTraitEventMessage.Types.State) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Types.Players.BoardPlayerMessage), global::Commons.Types.Players.BoardPlayerMessage.Parser, new[]{ "Id", "BytesName", "Level", "ItemStat", "Kills", "Deaths", "Gold", "Exp", "Inventories", "RootedInventories", "HoldItems", "AcquiredItems", "Missions", "LearnableTraits", "AppliedTraits", "InventorySkills", "RerollLevelUpSelectTrait", "SelectTraitEvents" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PlayerMessage : pb::IMessage<PlayerMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerMessage> _parser = new pb::MessageParser<PlayerMessage>(() => new PlayerMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Commons.Types.Players.PlayerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerMessage(PlayerMessage other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      level_ = other.level_;
      isAdmin_ = other.isAdmin_;
      boardId_ = other.boardId_;
      power_ = other.power_;
      avatarCharacterItemDataId_ = other.avatarCharacterItemDataId_;
      telegram_ = other.telegram_ != null ? other.telegram_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerMessage Clone() {
      return new PlayerMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 4;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "isAdmin" field.</summary>
    public const int IsAdminFieldNumber = 6;
    private bool isAdmin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsAdmin {
      get { return isAdmin_; }
      set {
        isAdmin_ = value;
      }
    }

    /// <summary>Field number for the "boardId" field.</summary>
    public const int BoardIdFieldNumber = 3;
    private long boardId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long BoardId {
      get { return boardId_; }
      set {
        boardId_ = value;
      }
    }

    /// <summary>Field number for the "power" field.</summary>
    public const int PowerFieldNumber = 7;
    private long power_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Power {
      get { return power_; }
      set {
        power_ = value;
      }
    }

    /// <summary>Field number for the "avatarCharacterItemDataId" field.</summary>
    public const int AvatarCharacterItemDataIdFieldNumber = 8;
    private int avatarCharacterItemDataId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AvatarCharacterItemDataId {
      get { return avatarCharacterItemDataId_; }
      set {
        avatarCharacterItemDataId_ = value;
      }
    }

    /// <summary>Field number for the "telegram" field.</summary>
    public const int TelegramFieldNumber = 5;
    private global::Commons.Types.Players.PlayerTelegramMessage telegram_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Players.PlayerTelegramMessage Telegram {
      get { return telegram_; }
      set {
        telegram_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Level != other.Level) return false;
      if (IsAdmin != other.IsAdmin) return false;
      if (BoardId != other.BoardId) return false;
      if (Power != other.Power) return false;
      if (AvatarCharacterItemDataId != other.AvatarCharacterItemDataId) return false;
      if (!object.Equals(Telegram, other.Telegram)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (IsAdmin != false) hash ^= IsAdmin.GetHashCode();
      if (BoardId != 0L) hash ^= BoardId.GetHashCode();
      if (Power != 0L) hash ^= Power.GetHashCode();
      if (AvatarCharacterItemDataId != 0) hash ^= AvatarCharacterItemDataId.GetHashCode();
      if (telegram_ != null) hash ^= Telegram.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (BoardId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(BoardId);
      }
      if (Level != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Level);
      }
      if (telegram_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Telegram);
      }
      if (IsAdmin != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsAdmin);
      }
      if (Power != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(Power);
      }
      if (AvatarCharacterItemDataId != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(AvatarCharacterItemDataId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (BoardId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(BoardId);
      }
      if (Level != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Level);
      }
      if (telegram_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Telegram);
      }
      if (IsAdmin != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsAdmin);
      }
      if (Power != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(Power);
      }
      if (AvatarCharacterItemDataId != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(AvatarCharacterItemDataId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (IsAdmin != false) {
        size += 1 + 1;
      }
      if (BoardId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BoardId);
      }
      if (Power != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Power);
      }
      if (AvatarCharacterItemDataId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AvatarCharacterItemDataId);
      }
      if (telegram_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Telegram);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.IsAdmin != false) {
        IsAdmin = other.IsAdmin;
      }
      if (other.BoardId != 0L) {
        BoardId = other.BoardId;
      }
      if (other.Power != 0L) {
        Power = other.Power;
      }
      if (other.AvatarCharacterItemDataId != 0) {
        AvatarCharacterItemDataId = other.AvatarCharacterItemDataId;
      }
      if (other.telegram_ != null) {
        if (telegram_ == null) {
          Telegram = new global::Commons.Types.Players.PlayerTelegramMessage();
        }
        Telegram.MergeFrom(other.Telegram);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            BoardId = input.ReadInt64();
            break;
          }
          case 32: {
            Level = input.ReadInt32();
            break;
          }
          case 42: {
            if (telegram_ == null) {
              Telegram = new global::Commons.Types.Players.PlayerTelegramMessage();
            }
            input.ReadMessage(Telegram);
            break;
          }
          case 48: {
            IsAdmin = input.ReadBool();
            break;
          }
          case 56: {
            Power = input.ReadInt64();
            break;
          }
          case 64: {
            AvatarCharacterItemDataId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            BoardId = input.ReadInt64();
            break;
          }
          case 32: {
            Level = input.ReadInt32();
            break;
          }
          case 42: {
            if (telegram_ == null) {
              Telegram = new global::Commons.Types.Players.PlayerTelegramMessage();
            }
            input.ReadMessage(Telegram);
            break;
          }
          case 48: {
            IsAdmin = input.ReadBool();
            break;
          }
          case 56: {
            Power = input.ReadInt64();
            break;
          }
          case 64: {
            AvatarCharacterItemDataId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SelectTraitEventMessage : pb::IMessage<SelectTraitEventMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SelectTraitEventMessage> _parser = new pb::MessageParser<SelectTraitEventMessage>(() => new SelectTraitEventMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SelectTraitEventMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Commons.Types.Players.PlayerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SelectTraitEventMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SelectTraitEventMessage(SelectTraitEventMessage other) : this() {
      state_ = other.state_;
      traitItemGroup_ = other.traitItemGroup_ != null ? other.traitItemGroup_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SelectTraitEventMessage Clone() {
      return new SelectTraitEventMessage(this);
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 1;
    private global::Commons.Types.Players.SelectTraitEventMessage.Types.State state_ = global::Commons.Types.Players.SelectTraitEventMessage.Types.State.Pending;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Players.SelectTraitEventMessage.Types.State State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "traitItemGroup" field.</summary>
    public const int TraitItemGroupFieldNumber = 2;
    private global::Commons.Types.TraitItemGroup traitItemGroup_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.TraitItemGroup TraitItemGroup {
      get { return traitItemGroup_; }
      set {
        traitItemGroup_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SelectTraitEventMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SelectTraitEventMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (State != other.State) return false;
      if (!object.Equals(TraitItemGroup, other.TraitItemGroup)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (State != global::Commons.Types.Players.SelectTraitEventMessage.Types.State.Pending) hash ^= State.GetHashCode();
      if (traitItemGroup_ != null) hash ^= TraitItemGroup.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (State != global::Commons.Types.Players.SelectTraitEventMessage.Types.State.Pending) {
        output.WriteRawTag(8);
        output.WriteEnum((int) State);
      }
      if (traitItemGroup_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TraitItemGroup);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (State != global::Commons.Types.Players.SelectTraitEventMessage.Types.State.Pending) {
        output.WriteRawTag(8);
        output.WriteEnum((int) State);
      }
      if (traitItemGroup_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TraitItemGroup);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (State != global::Commons.Types.Players.SelectTraitEventMessage.Types.State.Pending) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (traitItemGroup_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TraitItemGroup);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SelectTraitEventMessage other) {
      if (other == null) {
        return;
      }
      if (other.State != global::Commons.Types.Players.SelectTraitEventMessage.Types.State.Pending) {
        State = other.State;
      }
      if (other.traitItemGroup_ != null) {
        if (traitItemGroup_ == null) {
          TraitItemGroup = new global::Commons.Types.TraitItemGroup();
        }
        TraitItemGroup.MergeFrom(other.TraitItemGroup);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            State = (global::Commons.Types.Players.SelectTraitEventMessage.Types.State) input.ReadEnum();
            break;
          }
          case 18: {
            if (traitItemGroup_ == null) {
              TraitItemGroup = new global::Commons.Types.TraitItemGroup();
            }
            input.ReadMessage(TraitItemGroup);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            State = (global::Commons.Types.Players.SelectTraitEventMessage.Types.State) input.ReadEnum();
            break;
          }
          case 18: {
            if (traitItemGroup_ == null) {
              TraitItemGroup = new global::Commons.Types.TraitItemGroup();
            }
            input.ReadMessage(TraitItemGroup);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the SelectTraitEventMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum State {
        [pbr::OriginalName("Pending")] Pending = 0,
        [pbr::OriginalName("Immediate")] Immediate = 1,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BoardPlayerMessage : pb::IMessage<BoardPlayerMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BoardPlayerMessage> _parser = new pb::MessageParser<BoardPlayerMessage>(() => new BoardPlayerMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BoardPlayerMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Commons.Types.Players.PlayerReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BoardPlayerMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BoardPlayerMessage(BoardPlayerMessage other) : this() {
      id_ = other.id_;
      bytesName_ = other.bytesName_;
      level_ = other.level_;
      itemStat_ = other.itemStat_.Clone();
      kills_ = other.kills_;
      deaths_ = other.deaths_;
      gold_ = other.gold_;
      exp_ = other.exp_;
      inventories_ = other.inventories_.Clone();
      rootedInventories_ = other.rootedInventories_.Clone();
      holdItems_ = other.holdItems_.Clone();
      acquiredItems_ = other.acquiredItems_.Clone();
      missions_ = other.missions_.Clone();
      learnableTraits_ = other.learnableTraits_.Clone();
      appliedTraits_ = other.appliedTraits_.Clone();
      inventorySkills_ = other.inventorySkills_.Clone();
      rerollLevelUpSelectTrait_ = other.rerollLevelUpSelectTrait_;
      selectTraitEvents_ = other.selectTraitEvents_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BoardPlayerMessage Clone() {
      return new BoardPlayerMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "bytesName" field.</summary>
    public const int BytesNameFieldNumber = 2;
    private pb::ByteString bytesName_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString BytesName {
      get { return bytesName_; }
      set {
        bytesName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 3;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "itemStat" field.</summary>
    public const int ItemStatFieldNumber = 4;
    private static readonly pb::FieldCodec<float> _repeated_itemStat_codec
        = pb::FieldCodec.ForFloat(34);
    private readonly pbc::RepeatedField<float> itemStat_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> ItemStat {
      get { return itemStat_; }
    }

    /// <summary>Field number for the "kills" field.</summary>
    public const int KillsFieldNumber = 5;
    private int kills_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Kills {
      get { return kills_; }
      set {
        kills_ = value;
      }
    }

    /// <summary>Field number for the "deaths" field.</summary>
    public const int DeathsFieldNumber = 6;
    private int deaths_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Deaths {
      get { return deaths_; }
      set {
        deaths_ = value;
      }
    }

    /// <summary>Field number for the "gold" field.</summary>
    public const int GoldFieldNumber = 7;
    private long gold_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Gold {
      get { return gold_; }
      set {
        gold_ = value;
      }
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 8;
    private long exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    /// <summary>Field number for the "inventories" field.</summary>
    public const int InventoriesFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Commons.Types.Players.PlayerInventory> _repeated_inventories_codec
        = pb::FieldCodec.ForMessage(74, global::Commons.Types.Players.PlayerInventory.Parser);
    private readonly pbc::RepeatedField<global::Commons.Types.Players.PlayerInventory> inventories_ = new pbc::RepeatedField<global::Commons.Types.Players.PlayerInventory>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Types.Players.PlayerInventory> Inventories {
      get { return inventories_; }
    }

    /// <summary>Field number for the "rootedInventories" field.</summary>
    public const int RootedInventoriesFieldNumber = 19;
    private static readonly pb::FieldCodec<global::Commons.Types.Players.PlayerInventory> _repeated_rootedInventories_codec
        = pb::FieldCodec.ForMessage(154, global::Commons.Types.Players.PlayerInventory.Parser);
    private readonly pbc::RepeatedField<global::Commons.Types.Players.PlayerInventory> rootedInventories_ = new pbc::RepeatedField<global::Commons.Types.Players.PlayerInventory>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Types.Players.PlayerInventory> RootedInventories {
      get { return rootedInventories_; }
    }

    /// <summary>Field number for the "holdItems" field.</summary>
    public const int HoldItemsFieldNumber = 10;
    private static readonly pb::FieldCodec<global::Commons.Types.Players.PlayerItemMessage> _repeated_holdItems_codec
        = pb::FieldCodec.ForMessage(82, global::Commons.Types.Players.PlayerItemMessage.Parser);
    private readonly pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage> holdItems_ = new pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage> HoldItems {
      get { return holdItems_; }
    }

    /// <summary>Field number for the "acquiredItems" field.</summary>
    public const int AcquiredItemsFieldNumber = 12;
    private static readonly pb::FieldCodec<global::Commons.Types.Players.PlayerItemMessage> _repeated_acquiredItems_codec
        = pb::FieldCodec.ForMessage(98, global::Commons.Types.Players.PlayerItemMessage.Parser);
    private readonly pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage> acquiredItems_ = new pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage> AcquiredItems {
      get { return acquiredItems_; }
    }

    /// <summary>Field number for the "missions" field.</summary>
    public const int MissionsFieldNumber = 13;
    private static readonly pbc::MapField<int, global::Commons.Types.Players.PlayerAchievementMessage>.Codec _map_missions_codec
        = new pbc::MapField<int, global::Commons.Types.Players.PlayerAchievementMessage>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Commons.Types.Players.PlayerAchievementMessage.Parser), 106);
    private readonly pbc::MapField<int, global::Commons.Types.Players.PlayerAchievementMessage> missions_ = new pbc::MapField<int, global::Commons.Types.Players.PlayerAchievementMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Commons.Types.Players.PlayerAchievementMessage> Missions {
      get { return missions_; }
    }

    /// <summary>Field number for the "learnableTraits" field.</summary>
    public const int LearnableTraitsFieldNumber = 14;
    private static readonly pb::FieldCodec<global::Commons.Types.Players.PlayerItemMessage> _repeated_learnableTraits_codec
        = pb::FieldCodec.ForMessage(114, global::Commons.Types.Players.PlayerItemMessage.Parser);
    private readonly pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage> learnableTraits_ = new pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage> LearnableTraits {
      get { return learnableTraits_; }
    }

    /// <summary>Field number for the "appliedTraits" field.</summary>
    public const int AppliedTraitsFieldNumber = 15;
    private static readonly pb::FieldCodec<global::Commons.Types.Players.PlayerItemMessage> _repeated_appliedTraits_codec
        = pb::FieldCodec.ForMessage(122, global::Commons.Types.Players.PlayerItemMessage.Parser);
    private readonly pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage> appliedTraits_ = new pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage> AppliedTraits {
      get { return appliedTraits_; }
    }

    /// <summary>Field number for the "inventorySkills" field.</summary>
    public const int InventorySkillsFieldNumber = 18;
    private static readonly pb::FieldCodec<global::Commons.Types.Players.PlayerItemMessage> _repeated_inventorySkills_codec
        = pb::FieldCodec.ForMessage(146, global::Commons.Types.Players.PlayerItemMessage.Parser);
    private readonly pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage> inventorySkills_ = new pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Types.Players.PlayerItemMessage> InventorySkills {
      get { return inventorySkills_; }
    }

    /// <summary>Field number for the "rerollLevelUpSelectTrait" field.</summary>
    public const int RerollLevelUpSelectTraitFieldNumber = 16;
    private int rerollLevelUpSelectTrait_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RerollLevelUpSelectTrait {
      get { return rerollLevelUpSelectTrait_; }
      set {
        rerollLevelUpSelectTrait_ = value;
      }
    }

    /// <summary>Field number for the "selectTraitEvents" field.</summary>
    public const int SelectTraitEventsFieldNumber = 17;
    private static readonly pb::FieldCodec<global::Commons.Types.Players.SelectTraitEventMessage> _repeated_selectTraitEvents_codec
        = pb::FieldCodec.ForMessage(138, global::Commons.Types.Players.SelectTraitEventMessage.Parser);
    private readonly pbc::RepeatedField<global::Commons.Types.Players.SelectTraitEventMessage> selectTraitEvents_ = new pbc::RepeatedField<global::Commons.Types.Players.SelectTraitEventMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Types.Players.SelectTraitEventMessage> SelectTraitEvents {
      get { return selectTraitEvents_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BoardPlayerMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BoardPlayerMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (BytesName != other.BytesName) return false;
      if (Level != other.Level) return false;
      if(!itemStat_.Equals(other.itemStat_)) return false;
      if (Kills != other.Kills) return false;
      if (Deaths != other.Deaths) return false;
      if (Gold != other.Gold) return false;
      if (Exp != other.Exp) return false;
      if(!inventories_.Equals(other.inventories_)) return false;
      if(!rootedInventories_.Equals(other.rootedInventories_)) return false;
      if(!holdItems_.Equals(other.holdItems_)) return false;
      if(!acquiredItems_.Equals(other.acquiredItems_)) return false;
      if (!Missions.Equals(other.Missions)) return false;
      if(!learnableTraits_.Equals(other.learnableTraits_)) return false;
      if(!appliedTraits_.Equals(other.appliedTraits_)) return false;
      if(!inventorySkills_.Equals(other.inventorySkills_)) return false;
      if (RerollLevelUpSelectTrait != other.RerollLevelUpSelectTrait) return false;
      if(!selectTraitEvents_.Equals(other.selectTraitEvents_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (BytesName.Length != 0) hash ^= BytesName.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      hash ^= itemStat_.GetHashCode();
      if (Kills != 0) hash ^= Kills.GetHashCode();
      if (Deaths != 0) hash ^= Deaths.GetHashCode();
      if (Gold != 0L) hash ^= Gold.GetHashCode();
      if (Exp != 0L) hash ^= Exp.GetHashCode();
      hash ^= inventories_.GetHashCode();
      hash ^= rootedInventories_.GetHashCode();
      hash ^= holdItems_.GetHashCode();
      hash ^= acquiredItems_.GetHashCode();
      hash ^= Missions.GetHashCode();
      hash ^= learnableTraits_.GetHashCode();
      hash ^= appliedTraits_.GetHashCode();
      hash ^= inventorySkills_.GetHashCode();
      if (RerollLevelUpSelectTrait != 0) hash ^= RerollLevelUpSelectTrait.GetHashCode();
      hash ^= selectTraitEvents_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (BytesName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(BytesName);
      }
      if (Level != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Level);
      }
      itemStat_.WriteTo(output, _repeated_itemStat_codec);
      if (Kills != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Kills);
      }
      if (Deaths != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Deaths);
      }
      if (Gold != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(Gold);
      }
      if (Exp != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(Exp);
      }
      inventories_.WriteTo(output, _repeated_inventories_codec);
      holdItems_.WriteTo(output, _repeated_holdItems_codec);
      acquiredItems_.WriteTo(output, _repeated_acquiredItems_codec);
      missions_.WriteTo(output, _map_missions_codec);
      learnableTraits_.WriteTo(output, _repeated_learnableTraits_codec);
      appliedTraits_.WriteTo(output, _repeated_appliedTraits_codec);
      if (RerollLevelUpSelectTrait != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(RerollLevelUpSelectTrait);
      }
      selectTraitEvents_.WriteTo(output, _repeated_selectTraitEvents_codec);
      inventorySkills_.WriteTo(output, _repeated_inventorySkills_codec);
      rootedInventories_.WriteTo(output, _repeated_rootedInventories_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (BytesName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(BytesName);
      }
      if (Level != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Level);
      }
      itemStat_.WriteTo(ref output, _repeated_itemStat_codec);
      if (Kills != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Kills);
      }
      if (Deaths != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Deaths);
      }
      if (Gold != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(Gold);
      }
      if (Exp != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(Exp);
      }
      inventories_.WriteTo(ref output, _repeated_inventories_codec);
      holdItems_.WriteTo(ref output, _repeated_holdItems_codec);
      acquiredItems_.WriteTo(ref output, _repeated_acquiredItems_codec);
      missions_.WriteTo(ref output, _map_missions_codec);
      learnableTraits_.WriteTo(ref output, _repeated_learnableTraits_codec);
      appliedTraits_.WriteTo(ref output, _repeated_appliedTraits_codec);
      if (RerollLevelUpSelectTrait != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(RerollLevelUpSelectTrait);
      }
      selectTraitEvents_.WriteTo(ref output, _repeated_selectTraitEvents_codec);
      inventorySkills_.WriteTo(ref output, _repeated_inventorySkills_codec);
      rootedInventories_.WriteTo(ref output, _repeated_rootedInventories_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (BytesName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BytesName);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      size += itemStat_.CalculateSize(_repeated_itemStat_codec);
      if (Kills != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Kills);
      }
      if (Deaths != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Deaths);
      }
      if (Gold != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Gold);
      }
      if (Exp != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Exp);
      }
      size += inventories_.CalculateSize(_repeated_inventories_codec);
      size += rootedInventories_.CalculateSize(_repeated_rootedInventories_codec);
      size += holdItems_.CalculateSize(_repeated_holdItems_codec);
      size += acquiredItems_.CalculateSize(_repeated_acquiredItems_codec);
      size += missions_.CalculateSize(_map_missions_codec);
      size += learnableTraits_.CalculateSize(_repeated_learnableTraits_codec);
      size += appliedTraits_.CalculateSize(_repeated_appliedTraits_codec);
      size += inventorySkills_.CalculateSize(_repeated_inventorySkills_codec);
      if (RerollLevelUpSelectTrait != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(RerollLevelUpSelectTrait);
      }
      size += selectTraitEvents_.CalculateSize(_repeated_selectTraitEvents_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BoardPlayerMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.BytesName.Length != 0) {
        BytesName = other.BytesName;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      itemStat_.Add(other.itemStat_);
      if (other.Kills != 0) {
        Kills = other.Kills;
      }
      if (other.Deaths != 0) {
        Deaths = other.Deaths;
      }
      if (other.Gold != 0L) {
        Gold = other.Gold;
      }
      if (other.Exp != 0L) {
        Exp = other.Exp;
      }
      inventories_.Add(other.inventories_);
      rootedInventories_.Add(other.rootedInventories_);
      holdItems_.Add(other.holdItems_);
      acquiredItems_.Add(other.acquiredItems_);
      missions_.MergeFrom(other.missions_);
      learnableTraits_.Add(other.learnableTraits_);
      appliedTraits_.Add(other.appliedTraits_);
      inventorySkills_.Add(other.inventorySkills_);
      if (other.RerollLevelUpSelectTrait != 0) {
        RerollLevelUpSelectTrait = other.RerollLevelUpSelectTrait;
      }
      selectTraitEvents_.Add(other.selectTraitEvents_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            BytesName = input.ReadBytes();
            break;
          }
          case 24: {
            Level = input.ReadInt32();
            break;
          }
          case 34:
          case 37: {
            itemStat_.AddEntriesFrom(input, _repeated_itemStat_codec);
            break;
          }
          case 40: {
            Kills = input.ReadInt32();
            break;
          }
          case 48: {
            Deaths = input.ReadInt32();
            break;
          }
          case 56: {
            Gold = input.ReadInt64();
            break;
          }
          case 64: {
            Exp = input.ReadInt64();
            break;
          }
          case 74: {
            inventories_.AddEntriesFrom(input, _repeated_inventories_codec);
            break;
          }
          case 82: {
            holdItems_.AddEntriesFrom(input, _repeated_holdItems_codec);
            break;
          }
          case 98: {
            acquiredItems_.AddEntriesFrom(input, _repeated_acquiredItems_codec);
            break;
          }
          case 106: {
            missions_.AddEntriesFrom(input, _map_missions_codec);
            break;
          }
          case 114: {
            learnableTraits_.AddEntriesFrom(input, _repeated_learnableTraits_codec);
            break;
          }
          case 122: {
            appliedTraits_.AddEntriesFrom(input, _repeated_appliedTraits_codec);
            break;
          }
          case 128: {
            RerollLevelUpSelectTrait = input.ReadInt32();
            break;
          }
          case 138: {
            selectTraitEvents_.AddEntriesFrom(input, _repeated_selectTraitEvents_codec);
            break;
          }
          case 146: {
            inventorySkills_.AddEntriesFrom(input, _repeated_inventorySkills_codec);
            break;
          }
          case 154: {
            rootedInventories_.AddEntriesFrom(input, _repeated_rootedInventories_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            BytesName = input.ReadBytes();
            break;
          }
          case 24: {
            Level = input.ReadInt32();
            break;
          }
          case 34:
          case 37: {
            itemStat_.AddEntriesFrom(ref input, _repeated_itemStat_codec);
            break;
          }
          case 40: {
            Kills = input.ReadInt32();
            break;
          }
          case 48: {
            Deaths = input.ReadInt32();
            break;
          }
          case 56: {
            Gold = input.ReadInt64();
            break;
          }
          case 64: {
            Exp = input.ReadInt64();
            break;
          }
          case 74: {
            inventories_.AddEntriesFrom(ref input, _repeated_inventories_codec);
            break;
          }
          case 82: {
            holdItems_.AddEntriesFrom(ref input, _repeated_holdItems_codec);
            break;
          }
          case 98: {
            acquiredItems_.AddEntriesFrom(ref input, _repeated_acquiredItems_codec);
            break;
          }
          case 106: {
            missions_.AddEntriesFrom(ref input, _map_missions_codec);
            break;
          }
          case 114: {
            learnableTraits_.AddEntriesFrom(ref input, _repeated_learnableTraits_codec);
            break;
          }
          case 122: {
            appliedTraits_.AddEntriesFrom(ref input, _repeated_appliedTraits_codec);
            break;
          }
          case 128: {
            RerollLevelUpSelectTrait = input.ReadInt32();
            break;
          }
          case 138: {
            selectTraitEvents_.AddEntriesFrom(ref input, _repeated_selectTraitEvents_codec);
            break;
          }
          case 146: {
            inventorySkills_.AddEntriesFrom(ref input, _repeated_inventorySkills_codec);
            break;
          }
          case 154: {
            rootedInventories_.AddEntriesFrom(ref input, _repeated_rootedInventories_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
