using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

internal class GameBoard_Update_Generator
{
    private static void Main(string[] args)
    {
        Console.WriteLine("Generating update handle partial & general implementation");
        var workingDirectory = Directory.GetCurrentDirectory().Split("Generators")[0] + @"Packets\Updates\";
        var protoPath = $@"{workingDirectory}\Updates.proto";
        Console.WriteLine("proto path: " + protoPath);

        if (!File.Exists(protoPath))
        {
            Console.WriteLine("😒 Proto file not found");
            return;
        }

        var regex = new Regex(@"^\s*([a-zA-Z0-9\.]+)\s+([a-zA-Z0-9_]+)\s*=\s*\d+;");

        var messages = new List<string>();
        using (var reader = new StreamReader(protoPath))
        {
            var isOneofSection = false;
            while (reader.ReadLine() is { } line)
            {
                if (line.Contains("oneof Update"))
                {
                    isOneofSection = true;
                    continue;
                }

                if (!isOneofSection)
                    continue;

                if (line.Contains('}'))
                    break;

                var match = regex.Match(line);
                if (line.Contains("--board-update") && match.Success)
                {
                    var name = match.Groups[1].Value;
                    messages.Add(name);
                }
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//  This code was generated by a tool.");
        sb.AppendLine("//");
        sb.AppendLine("//  Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//  the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using Commons.Packets.Updates;");
        sb.AppendLine();
        sb.AppendLine("namespace Commons.Game");
        sb.AppendLine("{");
        sb.AppendLine(@"    public partial class GameBoard");
        sb.AppendLine(@"    {");
        foreach (var messageName in messages)
        {
            sb.AppendLine($@"        partial void ServerHandleUpdate({messageName} update);");
        }
        sb.AppendLine();
        foreach (var messageName in messages)
        {
            sb.AppendLine($@"        private partial void HandleUpdateInternal({messageName} update);");
        }
        sb.AppendLine();
        sb.AppendLine(@"        private partial bool HandleUpdateInternal(IBoardUpdate update)");
        sb.AppendLine(@"        {");
        sb.AppendLine(@"            switch (update)");
        sb.AppendLine(@"            {");
        foreach (var message in messages)
        {
            sb.AppendLine($@"               case {message} u:");
            sb.AppendLine($@"                   ServerHandleUpdate(u);");
            sb.AppendLine($@"                   HandleUpdateInternal(u);");
            sb.AppendLine($@"                   break;");
        }
        sb.AppendLine(@"                default:");
        sb.AppendLine(@"                    Config.LogError($""GameBoard.HandleUpdate: unhandled update type {update.GetType()}"");");
        sb.AppendLine(@"                    return false;");
        sb.AppendLine(@"            }");
        sb.AppendLine();
        sb.AppendLine(@"            return true;");
        sb.AppendLine(@"        }");

        sb.AppendLine(@"    }");
        sb.AppendLine("}");


        var outputFilePath = $@"{Directory.GetCurrentDirectory().Split("Generators")[0]}\Game\GameBoard.Update.generated.cs";

        if (Path.GetDirectoryName(outputFilePath) is { } directoryName)
        {
            Directory.CreateDirectory(directoryName);
            File.WriteAllText(outputFilePath, sb.ToString());

            Console.WriteLine($"👍 Successfully update handle partial & general implementation. generate to {outputFilePath}");
        }
        else
        {
            Console.WriteLine($"😒 Failed to update handle partial & general implementation. generate to {outputFilePath}");
        }
    }
}