export const HOUSING_TECH = {
  version: '0.1-runtime',
  source: 'harness/design/ninja2/housing-building-tech-v0.yaml',
  resources: {
    gold: { itemId: 5, name: '골드', icon: '●' },
    exp: { itemId: 6, name: '경험치', icon: '◇' },
    lantern: { itemId: 8, name: '등불', icon: '◌' },
    wood: { itemId: 200101, name: '목재', icon: '▰' },
    stone: { itemId: 200102, name: '석재', icon: '◆' },
    soulflame: { itemId: 200103, name: '영혼불', icon: '◌' },
    herb: { itemId: 200108, name: '허브', icon: '✚' },
    food: { itemId: 200109, name: '식량', icon: '●' },
    tool: { itemId: 200110, name: '도구', icon: '▣' },
    bamboo: { itemId: 200106, name: '대나무', icon: '▥' },
    iron_ore: { itemId: 200107, name: '철광석', icon: '◆' },
  },
  homePaths: [
    [12, 7, 'wide'],
    [12, 18, 'wide'],
    [12, 4, 'wide'],
    [12, 3, 'narrow'],
    [7, 6, 'narrow'],
    [18, 19, 'narrow'],
  ],
  buildings: [
    {
      key: 'lantern_shrine',
      contentItemId: 200600,
      name: '등불 신전',
      tier: 'core',
      role: 'town_center',
      footprint: '2x2',
      runtimeTiles: [11, 12, 16, 17],
      runtimeAnchorTile: 12,
      spriteKey: 'shrine',
      assetStatus: 'existing',
      startsBuilt: true,
      homePreview: true,
      icon: '등불',
      output: '등불 반경',
      kind: 'soul',
      visual: { w: 142, h: 134, dx: 0, dy: -18 },
      base: { kind: 'plaza', w: 198, h: 148, dx: 0, dy: 18 },
      construction: { seconds: 0, cost: {} },
      placementKind: 'singleton',
      instanceRole: 'town_center_core',
      maxInstancesByLanternLevel: { 1: 1 },
      effectKind: 'sanctuary_core',
      levels: [
        { level: 1, effect: { light_radius: 38, max_open_tiles: 6, resident_cap: 6, max_building_level: 2, wood_per_min: 2, gold_per_min: 12 } },
        { level: 2, effect: { light_radius: 52, max_open_tiles: 8, resident_cap: 7, max_building_level: 3, wood_per_min: 3, gold_per_min: 20, unlocks: ['stone_quarry', 'training_yard'] }, levelUp: { seconds: 120, cost: { gold: 1200, wood: 120, stone: 20 } } },
        { level: 3, effect: { light_radius: 70, max_open_tiles: 12, resident_cap: 8, max_building_level: 4, wood_per_min: 5, gold_per_min: 32, unlocks: ['soulflame_well'] }, levelUp: { seconds: 600, cost: { gold: 2800, wood: 260, stone: 55, soulflame: 2 } } },
        { level: 4, effect: { light_radius: 92, max_open_tiles: 17, resident_cap: 10, max_building_level: 5, wood_per_min: 8, gold_per_min: 52, unlocks: ['herb_garden', 'resident_lodge'] }, levelUp: { seconds: 1800, cost: { gold: 6200, wood: 560, stone: 130, soulflame: 8 } } },
        { level: 5, effect: { light_radius: 120, max_open_tiles: 23, resident_cap: 12, max_building_level: 6, wood_per_min: 12, gold_per_min: 84, unlocks: ['workshop', 'guard_lantern', 'scout_post'] }, levelUp: { seconds: 5400, cost: { gold: 14000, wood: 1200, stone: 300, soulflame: 20 } } },
      ],
    },
    {
      key: 'wood_workshop',
      contentItemId: 200602,
      name: '목재 작업장',
      tier: 'core',
      role: 'production',
      footprint: '1x2',
      runtimeTiles: [6, 7],
      runtimeAnchorTile: 7,
      spriteKey: 'wood_workshop',
      assetStatus: 'existing',
      startsBuilt: false,
      homePreview: true,
      icon: '목재',
      output: '목재',
      kind: 'wood',
      visual: { w: 112, h: 96, dx: -18, dy: -16 },
      base: { kind: 'yard', w: 154, h: 72, dx: -10, dy: 22 },
      construction: { seconds: 30, cost: { gold: 120 } },
      additionalConstruction: { seconds: 180, cost: { gold: 700, wood: 45, stone: 8 } },
      placementKind: 'repeatable',
      instanceRole: 'production_node',
      maxInstancesByLanternLevel: { 1: 1, 3: 2, 5: 3, 6: 4 },
      duplicateScaling: { costMultiplierPerExtra: 1.25, timeMultiplierPerExtra: 1.15 },
      effectKind: 'produce_wood',
      levels: [
        { level: 1, effect: { wood_per_min: 8, storage_minutes: 60 } },
        { level: 2, effect: { wood_per_min: 14, storage_minutes: 75 }, levelUp: { seconds: 60, cost: { gold: 500, wood: 12 } } },
        { level: 3, effect: { wood_per_min: 22, storage_minutes: 90 }, levelUp: { seconds: 180, cost: { gold: 1200, wood: 28, stone: 4 } } },
        { level: 4, effect: { wood_per_min: 34, storage_minutes: 120 }, levelUp: { seconds: 600, cost: { gold: 2800, wood: 60, stone: 12 } } },
        { level: 5, effect: { wood_per_min: 52, storage_minutes: 150 }, levelUp: { seconds: 1800, cost: { gold: 6500, wood: 130, stone: 28, soulflame: 1 } } },
      ],
    },
    {
      key: 'stone_quarry',
      contentItemId: 200604,
      name: '채석장',
      tier: 'ring_1',
      role: 'production',
      footprint: '1x2',
      runtimeTiles: [8, 9],
      runtimeAnchorTile: 8,
      spriteKey: 'stone_quarry',
      assetStatus: 'generated',
      startsBuilt: false,
      homePreview: true,
      icon: '석재',
      output: '석재',
      kind: 'stone',
      visual: { w: 112, h: 96, dx: 10, dy: -16 },
      base: { kind: 'yard', w: 154, h: 72, dx: 8, dy: 22 },
      construction: { seconds: 180, cost: { gold: 600, wood: 35, stone: 8 } },
      placementKind: 'repeatable',
      instanceRole: 'production_node',
      maxInstancesByLanternLevel: { 2: 1, 4: 2, 6: 3 },
      duplicateScaling: { costMultiplierPerExtra: 1.25, timeMultiplierPerExtra: 1.15 },
      unlock: { lantern_shrine_level: 2 },
      effectKind: 'produce_stone',
      levels: [
        { level: 1, effect: { stone_per_min: 3, storage_minutes: 60 } },
        { level: 2, effect: { stone_per_min: 5, storage_minutes: 75 }, levelUp: { seconds: 300, cost: { gold: 1200, wood: 50, stone: 14 } } },
        { level: 3, effect: { stone_per_min: 8, storage_minutes: 90 }, levelUp: { seconds: 900, cost: { gold: 2500, wood: 95, stone: 32, soulflame: 1 } } },
        { level: 4, effect: { stone_per_min: 13, storage_minutes: 120 }, levelUp: { seconds: 2400, cost: { gold: 5600, wood: 180, stone: 72, soulflame: 3 } } },
        { level: 5, effect: { stone_per_min: 20, storage_minutes: 150 }, levelUp: { seconds: 7200, cost: { gold: 12000, wood: 360, stone: 150, soulflame: 8 } } },
      ],
    },
    {
      key: 'training_yard',
      contentItemId: 200601,
      name: '용병 훈련소',
      tier: 'ring_1',
      role: 'companion_management',
      footprint: '1x3',
      runtimeTiles: [13, 18, 19],
      runtimeAnchorTile: 18,
      spriteKey: 'training_yard',
      assetStatus: 'existing',
      startsBuilt: false,
      homePreview: true,
      icon: '용병',
      output: '동료/경험치',
      kind: 'training',
      visual: { w: 146, h: 84, dx: 14, dy: 4 },
      base: { kind: 'yard', w: 178, h: 106, dx: 10, dy: 28 },
      construction: { seconds: 120, cost: { gold: 300, wood: 30 } },
      placementKind: 'singleton',
      instanceRole: 'companion_center',
      maxInstancesByLanternLevel: { 1: 1 },
      unlock: { lantern_shrine_level: 2, wood_workshop_level: 2 },
      effectKind: 'companion_management_and_training',
      levels: [
        { level: 1, effect: { exp_per_min: 18, attack_percent: 1 } },
        { level: 2, effect: { exp_per_min: 30, attack_percent: 2 }, levelUp: { seconds: 120, cost: { gold: 500, wood: 12 } } },
        { level: 3, effect: { exp_per_min: 48, attack_percent: 3 }, levelUp: { seconds: 360, cost: { gold: 1200, wood: 28, stone: 4 } } },
        { level: 4, effect: { exp_per_min: 76, attack_percent: 5 }, levelUp: { seconds: 1200, cost: { gold: 3000, wood: 70, stone: 16 } } },
        { level: 5, effect: { exp_per_min: 118, attack_percent: 8 }, levelUp: { seconds: 3600, cost: { gold: 7600, wood: 150, stone: 40, soulflame: 2 } } },
      ],
    },
    {
      key: 'soulflame_well',
      contentItemId: 200603,
      name: '영혼광맥',
      tier: 'ring_1',
      role: 'rare_production',
      footprint: '1x1',
      runtimeTiles: [4],
      runtimeAnchorTile: 4,
      spriteKey: 'soulflame_well',
      assetStatus: 'existing',
      startsBuilt: false,
      homePreview: true,
      icon: '영혼불',
      output: '영혼불',
      kind: 'soul',
      visual: { w: 70, h: 92, dx: 0, dy: -8 },
      base: { kind: 'watch', w: 80, h: 58, dx: 0, dy: 24 },
      construction: { seconds: 600, cost: { gold: 1200, wood: 80, stone: 35, soulflame: 1 } },
      placementKind: 'singleton',
      instanceRole: 'rare_resource_gate',
      maxInstancesByLanternLevel: { 3: 1 },
      unlock: { lantern_shrine_level: 3, stone_quarry_level: 2 },
      effectKind: 'produce_soulflame',
      levels: [
        { level: 1, effect: { soulflame_per_hour: 0.6, stone_per_min: 1 } },
        { level: 2, effect: { soulflame_per_hour: 1.1, stone_per_min: 2 }, levelUp: { seconds: 900, cost: { gold: 1800, wood: 60, stone: 30, soulflame: 2 } } },
        { level: 3, effect: { soulflame_per_hour: 1.9, stone_per_min: 3 }, levelUp: { seconds: 2400, cost: { gold: 4200, wood: 140, stone: 75, soulflame: 5 } } },
        { level: 4, effect: { soulflame_per_hour: 3.2, stone_per_min: 5 }, levelUp: { seconds: 7200, cost: { gold: 9800, wood: 320, stone: 160, soulflame: 12 } } },
        { level: 5, effect: { soulflame_per_hour: 5, stone_per_min: 8 }, levelUp: { seconds: 14400, cost: { gold: 22000, wood: 720, stone: 360, soulflame: 30 } } },
      ],
    },
    {
      key: 'herb_garden',
      contentItemId: 200605,
      name: '허브 정원',
      tier: 'ring_2',
      role: 'support_production',
      footprint: '1x3',
      runtimeTiles: [-1, -2, -3],
      runtimeAnchorTile: -2,
      spriteKey: 'herb_garden',
      assetStatus: 'existing',
      startsBuilt: false,
      homePreview: true,
      icon: '정원',
      output: '허브',
      kind: 'leaf',
      visual: { w: 146, h: 84, dx: 14, dy: 4 },
      base: { kind: 'garden', w: 178, h: 106, dx: 10, dy: 28 },
      construction: { seconds: 900, cost: { gold: 2500, wood: 110, stone: 50, soulflame: 2 } },
      placementKind: 'repeatable',
      instanceRole: 'support_production_node',
      maxInstancesByLanternLevel: { 4: 1, 5: 2, 6: 3 },
      duplicateScaling: { costMultiplierPerExtra: 1.25, timeMultiplierPerExtra: 1.15 },
      unlock: { lantern_shrine_level: 4 },
      effectKind: 'produce_herb_and_recovery_bonus',
      levels: [
        { level: 1, effect: { herb_per_min: 4, recovery_percent: 1 } },
        { level: 2, effect: { herb_per_min: 7, recovery_percent: 2 }, levelUp: { seconds: 1200, cost: { gold: 3500, wood: 120, stone: 45, soulflame: 2 } } },
        { level: 3, effect: { herb_per_min: 11, recovery_percent: 3 }, levelUp: { seconds: 3000, cost: { gold: 7600, wood: 250, stone: 110, soulflame: 6 } } },
        { level: 4, effect: { herb_per_min: 17, recovery_percent: 5 }, levelUp: { seconds: 9000, cost: { gold: 16000, wood: 520, stone: 260, soulflame: 15 } } },
        { level: 5, effect: { herb_per_min: 26, recovery_percent: 8 }, levelUp: { seconds: 21600, cost: { gold: 36000, wood: 1100, stone: 560, soulflame: 36 } } },
      ],
    },
    {
      key: 'resident_lodge',
      contentItemId: 200606,
      name: '주민 숙소',
      tier: 'ring_2',
      role: 'capacity',
      footprint: '1x2',
      runtimeTiles: [10, 14],
      runtimeAnchorTile: 14,
      spriteKey: 'storage',
      assetStatus: 'existing',
      startsBuilt: false,
      homePreview: false,
      icon: '숙소',
      output: '주민',
      kind: 'resident',
      visual: { w: 112, h: 88, dx: 12, dy: -12 },
      base: { kind: 'yard', w: 150, h: 70, dx: 8, dy: 22 },
      construction: { seconds: 1200, cost: { gold: 3200, wood: 140, stone: 60, soulflame: 2 } },
      placementKind: 'repeatable',
      instanceRole: 'capacity_storage_node',
      maxInstancesByLanternLevel: { 4: 1, 5: 2, 6: 3 },
      duplicateScaling: { costMultiplierPerExtra: 1.25, timeMultiplierPerExtra: 1.15 },
      unlock: { lantern_shrine_level: 4 },
      effectKind: 'resident_cap_and_offline',
      levels: [
        { level: 1, effect: { resident_cap_bonus: 2, offline_cap_hours_bonus: 0.5, all_production_percent: 1 } },
        { level: 2, effect: { resident_cap_bonus: 3, offline_cap_hours_bonus: 1, all_production_percent: 2 }, levelUp: { seconds: 1800, cost: { gold: 4400, wood: 160, stone: 70, soulflame: 3 } } },
        { level: 3, effect: { resident_cap_bonus: 4, offline_cap_hours_bonus: 1.5, all_production_percent: 3 }, levelUp: { seconds: 5400, cost: { gold: 9800, wood: 340, stone: 160, soulflame: 8 } } },
        { level: 4, effect: { resident_cap_bonus: 5, offline_cap_hours_bonus: 2, all_production_percent: 5 }, levelUp: { seconds: 14400, cost: { gold: 22000, wood: 760, stone: 360, soulflame: 20 } } },
        { level: 5, effect: { resident_cap_bonus: 7, offline_cap_hours_bonus: 3, all_production_percent: 8 }, levelUp: { seconds: 28800, cost: { gold: 50000, wood: 1600, stone: 760, soulflame: 46 } } },
      ],
    },
    {
      key: 'workshop',
      contentItemId: 200607,
      name: '공방',
      tier: 'ring_2',
      role: 'crafting',
      footprint: '1x2',
      runtimeTiles: [2, 5],
      runtimeAnchorTile: 5,
      spriteKey: 'workshop',
      assetStatus: 'generated',
      startsBuilt: false,
      homePreview: true,
      icon: '공방',
      output: '도구',
      kind: 'workshop',
      visual: { w: 112, h: 96, dx: -6, dy: -16 },
      base: { kind: 'yard', w: 154, h: 72, dx: -2, dy: 22 },
      construction: { seconds: 1800, cost: { gold: 5200, wood: 220, stone: 120, soulflame: 5 } },
      placementKind: 'singleton',
      instanceRole: 'crafting_center',
      maxInstancesByLanternLevel: { 5: 1 },
      unlock: { lantern_shrine_level: 5, resident_lodge_level: 1 },
      effectKind: 'tools_and_build_speed',
      levels: [
        { level: 1, effect: { tool_per_hour: 1, construction_time_reduction_percent: 2 } },
        { level: 2, effect: { tool_per_hour: 2, construction_time_reduction_percent: 4 }, levelUp: { seconds: 2400, cost: { gold: 7200, wood: 260, stone: 140, soulflame: 6 } } },
        { level: 3, effect: { tool_per_hour: 3, construction_time_reduction_percent: 7 }, levelUp: { seconds: 7200, cost: { gold: 16000, wood: 560, stone: 300, soulflame: 14 } } },
        { level: 4, effect: { tool_per_hour: 5, construction_time_reduction_percent: 11 }, levelUp: { seconds: 18000, cost: { gold: 36000, wood: 1200, stone: 640, soulflame: 32 } } },
        { level: 5, effect: { tool_per_hour: 8, construction_time_reduction_percent: 16 }, levelUp: { seconds: 43200, cost: { gold: 78000, wood: 2600, stone: 1400, soulflame: 72 } } },
      ],
    },
    {
      key: 'guard_lantern',
      contentItemId: 200608,
      name: '수호등탑',
      tier: 'ring_2',
      role: 'combat_bonus',
      footprint: '1x1',
      runtimeTiles: [3],
      runtimeAnchorTile: 3,
      spriteKey: 'guard_lantern',
      assetStatus: 'existing',
      startsBuilt: false,
      homePreview: true,
      icon: '수호',
      output: '보스 피해',
      kind: 'guard',
      visual: { w: 70, h: 92, dx: 0, dy: -8 },
      base: { kind: 'watch', w: 80, h: 58, dx: 0, dy: 24 },
      construction: { seconds: 1800, cost: { gold: 6000, wood: 180, stone: 160, soulflame: 6 } },
      placementKind: 'singleton',
      instanceRole: 'combat_guard',
      maxInstancesByLanternLevel: { 5: 1 },
      unlock: { lantern_shrine_level: 5 },
      effectKind: 'boss_and_defense_bonus',
      levels: [
        { level: 1, effect: { boss_damage_percent: 2, defense_percent: 1 } },
        { level: 2, effect: { boss_damage_percent: 4, defense_percent: 2 }, levelUp: { seconds: 3000, cost: { gold: 8500, wood: 220, stone: 180, soulflame: 7 } } },
        { level: 3, effect: { boss_damage_percent: 7, defense_percent: 3 }, levelUp: { seconds: 9000, cost: { gold: 19000, wood: 480, stone: 420, soulflame: 18 } } },
        { level: 4, effect: { boss_damage_percent: 11, defense_percent: 5 }, levelUp: { seconds: 21600, cost: { gold: 42000, wood: 1000, stone: 900, soulflame: 40 } } },
        { level: 5, effect: { boss_damage_percent: 16, defense_percent: 8 }, levelUp: { seconds: 43200, cost: { gold: 92000, wood: 2200, stone: 1900, soulflame: 88 } } },
      ],
    },
    {
      key: 'scout_post',
      contentItemId: 200609,
      name: '정찰소',
      tier: 'ring_2',
      role: 'farming_control',
      footprint: '1x1',
      runtimeTiles: [1],
      runtimeAnchorTile: 1,
      spriteKey: 'scout_post',
      assetStatus: 'generated',
      startsBuilt: false,
      homePreview: true,
      icon: '정찰',
      output: '드롭률',
      kind: 'scout',
      visual: { w: 70, h: 92, dx: 0, dy: -8 },
      base: { kind: 'watch', w: 80, h: 58, dx: 0, dy: 24 },
      construction: { seconds: 2400, cost: { gold: 7200, wood: 240, stone: 180, soulflame: 8 } },
      placementKind: 'singleton',
      instanceRole: 'expedition_control',
      maxInstancesByLanternLevel: { 5: 1 },
      unlock: { lantern_shrine_level: 5, guard_lantern_level: 1 },
      effectKind: 'expedition_preview_and_drop_bonus',
      levels: [
        { level: 1, effect: { resource_expedition_slots: 1, item_drop_percent: 1 } },
        { level: 2, effect: { resource_expedition_slots: 1, item_drop_percent: 2 }, levelUp: { seconds: 3600, cost: { gold: 9800, wood: 280, stone: 220, soulflame: 9 } } },
        { level: 3, effect: { resource_expedition_slots: 2, item_drop_percent: 4 }, levelUp: { seconds: 10800, cost: { gold: 22000, wood: 620, stone: 520, soulflame: 22 } } },
        { level: 4, effect: { resource_expedition_slots: 2, item_drop_percent: 7 }, levelUp: { seconds: 28800, cost: { gold: 48000, wood: 1300, stone: 1100, soulflame: 50 } } },
        { level: 5, effect: { resource_expedition_slots: 3, item_drop_percent: 10 }, levelUp: { seconds: 57600, cost: { gold: 105000, wood: 2800, stone: 2400, soulflame: 110 } } },
      ],
    },
    {
      key: 'granary',
      contentItemId: 200610,
      name: '보급창고',
      tier: 'ring_3',
      role: 'supply_capacity',
      footprint: '1x2',
      runtimeTiles: [-4, -5],
      runtimeAnchorTile: -4,
      spriteKey: 'granary',
      assetStatus: 'generated',
      startsBuilt: false,
      homePreview: true,
      icon: '보급',
      output: '식량',
      kind: 'granary',
      visual: { w: 112, h: 96, dx: 0, dy: -16 },
      base: { kind: 'yard', w: 154, h: 72, dx: 0, dy: 22 },
      construction: { seconds: 5400, cost: { gold: 18000, wood: 650, stone: 420, soulflame: 12, herb: 30, tool: 2 } },
      placementKind: 'repeatable',
      instanceRole: 'supply_storage_node',
      maxInstancesByLanternLevel: { 6: 2 },
      duplicateScaling: { costMultiplierPerExtra: 1.25, timeMultiplierPerExtra: 1.15 },
      unlock: { lantern_shrine_level: 6, resident_lodge_level: 3 },
      effectKind: 'food_storage_and_expedition_supply',
      levels: [
        { level: 1, effect: { food_per_hour: 12, expedition_supply_cap: 2, offline_cap_hours_bonus: 0.5 } },
        { level: 2, effect: { food_per_hour: 20, expedition_supply_cap: 3, offline_cap_hours_bonus: 0.75 }, levelUp: { seconds: 7200, cost: { gold: 24000, wood: 780, stone: 520, soulflame: 14, herb: 45, tool: 3 } } },
        { level: 3, effect: { food_per_hour: 32, expedition_supply_cap: 4, offline_cap_hours_bonus: 1 }, levelUp: { seconds: 14400, cost: { gold: 52000, wood: 1450, stone: 980, soulflame: 30, bamboo: 80, tool: 8 } } },
        { level: 4, effect: { food_per_hour: 50, expedition_supply_cap: 5, offline_cap_hours_bonus: 1.5 }, levelUp: { seconds: 28800, cost: { gold: 112000, wood: 3000, stone: 2100, soulflame: 68, bamboo: 180, iron_ore: 45, tool: 18 } } },
        { level: 5, effect: { food_per_hour: 78, expedition_supply_cap: 7, offline_cap_hours_bonus: 2 }, levelUp: { seconds: 64800, cost: { gold: 250000, wood: 6400, stone: 4600, soulflame: 150, bamboo: 420, iron_ore: 120, tool: 42 } } },
      ],
    },
    {
      key: 'bamboo_grove',
      contentItemId: 200611,
      name: '대나무숲',
      tier: 'ring_3',
      role: 'advanced_production',
      footprint: '1x3',
      runtimeTiles: [-6, -7, -8],
      runtimeAnchorTile: -7,
      spriteKey: 'bamboo_grove',
      assetStatus: 'generated',
      startsBuilt: false,
      homePreview: true,
      icon: '대나무',
      output: '대나무',
      kind: 'bamboo',
      visual: { w: 146, h: 84, dx: 12, dy: 4 },
      base: { kind: 'garden', w: 178, h: 106, dx: 10, dy: 28 },
      construction: { seconds: 4800, cost: { gold: 15000, wood: 720, stone: 280, soulflame: 8, herb: 20 } },
      placementKind: 'repeatable',
      instanceRole: 'advanced_production_node',
      maxInstancesByLanternLevel: { 6: 2 },
      duplicateScaling: { costMultiplierPerExtra: 1.25, timeMultiplierPerExtra: 1.15 },
      unlock: { lantern_shrine_level: 6, herb_garden_level: 2 },
      effectKind: 'produce_bamboo_and_build_cost_relief',
      levels: [
        { level: 1, effect: { bamboo_per_min: 3, wood_cost_reduction_percent: 1 } },
        { level: 2, effect: { bamboo_per_min: 5, wood_cost_reduction_percent: 2 }, levelUp: { seconds: 6600, cost: { gold: 22000, wood: 900, stone: 360, soulflame: 12, herb: 35 } } },
        { level: 3, effect: { bamboo_per_min: 8, wood_cost_reduction_percent: 3 }, levelUp: { seconds: 13200, cost: { gold: 48000, wood: 1700, stone: 740, soulflame: 26, tool: 6 } } },
        { level: 4, effect: { bamboo_per_min: 13, wood_cost_reduction_percent: 5 }, levelUp: { seconds: 28800, cost: { gold: 105000, wood: 3600, stone: 1600, soulflame: 60, tool: 14 } } },
        { level: 5, effect: { bamboo_per_min: 20, wood_cost_reduction_percent: 8 }, levelUp: { seconds: 57600, cost: { gold: 230000, wood: 7800, stone: 3600, soulflame: 136, iron_ore: 90, tool: 32 } } },
      ],
    },
    {
      key: 'iron_mine',
      contentItemId: 200612,
      name: '철광산',
      tier: 'ring_3',
      role: 'advanced_production',
      footprint: '1x2',
      runtimeTiles: [-9, -10],
      runtimeAnchorTile: -9,
      spriteKey: 'iron_mine',
      assetStatus: 'generated',
      startsBuilt: false,
      homePreview: true,
      icon: '철광',
      output: '철광석',
      kind: 'iron',
      visual: { w: 112, h: 96, dx: 0, dy: -16 },
      base: { kind: 'yard', w: 154, h: 72, dx: 0, dy: 22 },
      construction: { seconds: 7200, cost: { gold: 26000, wood: 900, stone: 760, soulflame: 18, bamboo: 40, tool: 4 } },
      placementKind: 'repeatable',
      instanceRole: 'advanced_production_node',
      maxInstancesByLanternLevel: { 6: 2 },
      duplicateScaling: { costMultiplierPerExtra: 1.25, timeMultiplierPerExtra: 1.15 },
      unlock: { lantern_shrine_level: 6, scout_post_level: 2, bamboo_grove_level: 1 },
      effectKind: 'produce_iron_and_midgame_upgrade_gate',
      levels: [
        { level: 1, effect: { iron_ore_per_hour: 4, boss_damage_percent: 1 } },
        { level: 2, effect: { iron_ore_per_hour: 7, boss_damage_percent: 2 }, levelUp: { seconds: 9000, cost: { gold: 34000, wood: 1100, stone: 900, soulflame: 22, bamboo: 70, tool: 6 } } },
        { level: 3, effect: { iron_ore_per_hour: 12, boss_damage_percent: 3 }, levelUp: { seconds: 18000, cost: { gold: 74000, wood: 2200, stone: 1800, soulflame: 50, bamboo: 160, tool: 14 } } },
        { level: 4, effect: { iron_ore_per_hour: 20, boss_damage_percent: 5 }, levelUp: { seconds: 36000, cost: { gold: 160000, wood: 4700, stone: 3900, soulflame: 112, bamboo: 380, tool: 32 } } },
        { level: 5, effect: { iron_ore_per_hour: 32, boss_damage_percent: 8 }, levelUp: { seconds: 72000, cost: { gold: 360000, wood: 10200, stone: 8600, soulflame: 250, bamboo: 900, tool: 72 } } },
      ],
    },
  ],
};
