export const editorStrings = {
  editorTitle: '에디터',
  file: '파일',
  openWorkspace: '워크스페이스 불러오기',
  saveWorkspace: '워크스페이스 저장',
  saveAsWorkspace: '워크스페이스 다른 이름으로 저장',
  saveAll: '워크스페이스 및 Trigger.json 일괄 저장',
  importWorkspacePatchResources: '워크스페이스 클라이언트 폴더에서 불러오기',
  exportWorkspacePatchResources: '워크스페이스 클라이언트 폴더에 저장',
  exportTriggerJSONLocal: 'Triggers.json 클라이언트 폴더에 저장',
  exportTriggerJSON: 'Triggers.json 다른 이름으로 저장',
  clearWorkspace: '전체 워크스페이스 초기화',
  clearCurrent: '현재 화면 초기화',
  clearAllConfirm: '전체 데이터를 삭제하고 워크스페이스를 초기화합니다.',
  clearCurrentConfirm: '현재 화면의 편집 데이터를 삭제합니다.',
  promptFileName: '파일 이름을 입력하세요.',
  previewTriggerIR: '👀 중간 코드 미리보기',
  previewTriggerJSON: '👀 Triggers.json 미리보기',
  selectTrigger: '트리거 선택',
  addTrigger: '새 트리거 추가',
  promptTriggerName: '트리거 이름을 입력하세요.',
  deleteTrigger: '🔥 삭제',
  deleteTriggerConfirm: '트리거를 삭제하시겠습니까?',
  selectUndefined: '선택되지 않음',
  type: '분류',
  period: '주기 (틱)',
  triggerWSfile: '트리거 워크스페이스 파일',
  logic: '논리',
  loops: '반복',
  math: '연산',
  variables: '변수',
  outputCall: '입출력 및 기능 호출',
  if: '조건 %1 이(가) 참이면',
  do: '%1',
  and: '그리고 (AND)',
  or: '또는 (OR)',
  not: '아닐 때 (NOT) %1',
  setVariable: '%3 %1을(를) %2(으)로 설정',
  setVariableReserved: 'caller%3 변수 %1을(를) %2(으)로 설정',
  setVariableUser: 'Parameter:%1을(를) %2로 설정',
  call: 'caller%2 %1 함수 호출',
  callWithArguments: 'caller%2 %1 함수 호출 (String Arguments 포함) %3',
  callReturn: 'caller%2 %1 함수 호출 후 결과 가져오기',
  callTrigger: 'caller%2 트리거 %1 호출',
  return: '종료',
  change: '%3 %1에 %2만큼 더하기',
  repeat0: '%1번 반복',
  repeat1: '%1',
  whileUntil: '%2이(가) %1 반복',
  while: '참이거나 0이 아닌 동안',
  until: '0 또는 거짓이 될 때까지',
  break: '반복 나가기',
  continue: '반복문 처음으로 되돌아가기',
  isEven: '이(가) 짝수',
  isOdd: '이(가) 홀수',
  isPrime: '이(가) 소수',
  isPositive: '이(가) 양수',
  isNegative: '이(가) 음수',
  modulo: '%1을(를) %2(으)로 나눈 나머지',
  uploadSuccess: 'Triggers.json 파일이 성공적으로 업데이트되었습니다.',
  uploadFail: 'Triggers.json 파일 업로드에 실패했습니다.',
  uploadPatchResourcesSuccess: '워크스페이스 파일을 성공적으로 저장했습니다.',
  uploadPatchResourcesFail: '워크스페이스 파일을 저장하지 못했습니다.',
  uploadAllSuccess: 'Triggers.json 파일과 워크스페이스 파일을 성공적으로 저장했습니다.',
  argument: '인자',
  editTriggerList: '트리거 목록 편집',
  close: '닫기',
  changeName: '이름 변경',
  confirm: '확인',
  cancel: '취소',
  edit: '편집',
  undo: '실행 취소',
  redo: '다시 실행',
  cut: '잘라내기',
  copy: '복사',
  paste: '붙여넣기',
  delete: '삭제',
  selectAll: '모두 선택',
  view: '보기',
  reload: '새로고침',
  toggleDevTools: '개발자 도구 토글',
  resetZoom: '확대/축소 초기화',
  zoomIn: '확대',
  zoomOut: '축소',
  toggleFullscreen: '전체 화면 전환',
  window: '창',
  minimize: '최소화',
  zoom: '확대/축소',
  front: '앞으로',
  help: '도움말',
  ok: '확인',
  failedToStartCompilerProcess: '컴파일러 프로세스를 시작하지 못했습니다. Python 설치를 확인해주세요.',
  compilerProcessExited: '컴파일러 프로세스가 비정상적으로 종료되었습니다.',
  failedToFindCompilerScript: '컴파일러 스크립트를 찾지 못했습니다. 실행 경로를 확인해주세요.',
  yes: '예',
  no: '아니요',
  moduleNotFoundTitle: 'Python 3 모듈을 찾을 수 없음.',
  moduleNotFoundMessage: '필요한 Python 3 모듈을 찾지 못했습니다. 모듈을 설치하시겠습니까?',
  installFailed: '모듈 설치에 실패했습니다.',
  moduleInstalled: '모듈이 성공적으로 설치되었습니다. 프로그램을 다시 시작해주세요.',
  compilerNotRunning: '컴파일러 시작중입니다. 잠시만 기다려주세요.',
  pythonNotFound: 'Python을 찾을 수 없습니다. Python이 설치되어 있는지 확인해주세요.',
  failedToFindClientPath: '클라이언트 경로를 찾지 못했습니다. 클라이언트 repo를 받았는지 확인해주세요.',
  failedToCompile: '컴파일에 실패했습니다.',
  text: '텍스트',
  debug: '디버그',
  blockDebug0: '디버그 %1 설명 %2',
  blockDebug1: '값 %1',
  newVariable: '새 변수',
  variableExists: '%1 변수가 이미 존재합니다.',
  killCompiler: '컴파일러 프로세스 강제 종료',
  setVariablePredefined: 'Predefined:%1을(를) %2(으)로 설정',
  duplicate: '복제',
  duplicateTriggerConfirm: '트리거를 복사합니다.',
  sort: '정렬 변경',
  sortNameAsc: '이름 오름차순',
  sortNameDesc: '이름 내림차순',
  sortRandom: '랜덤',
  search: '검색',
  searchTrigger: '트리거 필터',
  failedToLoadWorkspace: '워크스페이스 파일을 로드할 수 없습니다.',
  reloadedWorkspace: '워크스페이스 파일 변경이 감지되어 새로 로드했습니다.',
  predefined: '사전 정의된 값',
  setLocation: 'Location: %1',
  setTeamTag: 'Team Tag: %1',
  setWeaponType: 'Weapon Type: %1',
  setMapType: 'Map Type: %1',
  setTag: 'Tag: %1',
  setGameBoardState: 'Board State: %1',
  importWorkspacePatchResourcesSuccess: '워크스페이스 파일을 성공적으로 불러왔습니다.',
  blockIngame0: '인게임 기능 %1  데이터 (텍스트) %2',
  blockIngame1: '데이터 0 (숫자) %1',
  blockIngame2: '데이터 1 (숫자) %1',
  blockIngame3: '데이터 2 (숫자) %1',
  blockIngame4: '데이터 3 (숫자) %1',
  blockIngame5: '데이터 4 (숫자) %1',
  setString: '문자열: %1',
  getStringDirectly: '문자열 키: %1',
  getStringToId: '문자열 (Id): %1',
  refresh: '새로고침',
  saving: '저장중...',
  userVariables: '사용자 변수',
  specialVariables: '특수 변수',
  toLoadWorkspace: '워크스페이스를 불러올까요?',
  noResults: '검색 결과가 없습니다.',
  textBlock_FxEventDispatchAssetPath: 'Skills/FxSettings/FxEventDispatch/%1.asset',
};