id: 500302
group: 500300
name: "화요 장비 던전"
type: Dungeon
tags: [WeekdayDungeon, Tuesday]
scene: "PFB_MAP_Meadow_Day_Chapter"
popupArgs: { ClientModeManager: ModeManagerMushroom, ClientHomeMapDataId: 500101 }
initLevel: 10
locations:
  - { id: -1, position: { x: -7.5, y: 0.0 }, geometries: [{ circle: { center: { x: 0.0, y: 0.0 }, radius: 0.75 } }] }
  - { id: 1, position: { x: 7.5, y: 0.0 }, geometries: [{ circle: { center: { x: 0.0, y: 0.0 }, radius: 1.75 } }] }
triggers: [MAP_ONSTART_MUSHROOMFIELDWAVE1, MAP_ONUPDATE_MUSHROOMFIELDUPDATE]
rewardAddItemGroups:
  - shouldAddAll: true
    probPercent: 100
    addItems: [{ itemDataId: 200103, count: 24, isCore: true }]
