id: 500303
group: 500303
name: "수요 스킬 던전"
type: Dungeon
tags: [WeekdayDungeon, Wednesday, Skill]
scene: "PFB_MAP_Meadow_Dawn_Chapter"
sprite: "Maps/Map_Meadow_Dawn/Img_Map_Meadow_Dawn_Sky.png"
popupArgs:
  ClientModeManager: ModeManagerMushroom
  ClientHomeMapDataId: 500101
  ClientPhaserBackground: weekday_meadow_dawn
  ClientClearReturnDelayMs: 3000
  ClientWaveCount: 2
initLevel: 10
locations:
  - { id: -1, position: { x: -7.5, y: 0.0 }, geometries: [{ circle: { center: { x: 0.0, y: 0.0 }, radius: 0.75 } }] }
  - { id: 1, position: { x: 7.5, y: 0.0 }, geometries: [{ circle: { center: { x: 0.0, y: 0.0 }, radius: 1.75 } }] }
triggers: [MAP_ONSTART_WEEKDAYWEDNESDAYSKILLDUNGEON, MAP_ONUPDATE_WEEKDAYWEDNESDAYSKILLDUNGEON]
rewardAddItemGroups:
  - shouldAddAll: true
    probPercent: 100
    addItems: [{ itemDataId: 200104, count: 22, isCore: true }]
