// <auto-generated>
//  This code was generated by a tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
// </auto-generated>
using Commons.Packets.Requests;

namespace Commons.Packets
{
    public partial class Packet
    {
        public readonly Request Request = new();
        public static Packet Pop(byte key, PingRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.PingRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, SkipBoardRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.SkipBoardRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, SendCommandRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.SendCommandRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, LoginRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.LoginRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, SignInOauthRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.SignInOauthRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, UseCashItemRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.UseCashItemRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, LevelUpItemRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.LevelUpItemRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, LevelDownItemRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.LevelDownItemRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, DecomposeItemRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.DecomposeItemRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, ClaimDailyRewardRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.ClaimDailyRewardRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, CreateItemRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.CreateItemRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, BuyItemRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.BuyItemRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, DisposeItemRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.DisposeItemRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, RerollItemOptionRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.RerollItemOptionRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, CreateReceiptRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.CreateReceiptRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, VerifyReceiptRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.VerifyReceiptRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, CreateBoardRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.CreateBoardRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, JoinBoardRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.JoinBoardRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, GetBoardRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.GetBoardRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, LeaveBoardRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.LeaveBoardRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, InteractBoardRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.InteractBoardRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, AutoPlayToTickBoardRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.AutoPlayToTickBoardRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, ClaimAchievementRewardRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.ClaimAchievementRewardRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, IncreaseAchievementRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.IncreaseAchievementRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, GetPlayerRankingRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.GetPlayerRankingRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, GetPlayerReferralsRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.GetPlayerReferralsRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, AddPlayerReferralRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.AddPlayerReferralRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, GetPlayerMailsRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.GetPlayerMailsRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, ReadPlayerMailsRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.ReadPlayerMailsRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, DeletePlayerMailsRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.DeletePlayerMailsRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, UpdatePlayerTelegramTonAddressRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.UpdatePlayerTelegramTonAddressRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, GetPlayerDefenseRankResultsRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.GetPlayerDefenseRankResultsRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, GetPlayerChatsRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.GetPlayerChatsRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, SendPlayerChatRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.SendPlayerChatRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, UpdatePlayerNameRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.UpdatePlayerNameRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, GetPlayerInfoRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.GetPlayerInfoRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, GetNoticesRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.GetNoticesRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, ReadNoticeRequest request)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.ReadNoticeRequest = request;
            return packet;
        }

        public static Packet Pop(byte key, SendCommandRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.SendCommandResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, LoginRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.LoginResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, SignInOauthRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.SignInOauthResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, UseCashItemRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.UseCashItemResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, LevelUpItemRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.LevelUpItemResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, LevelDownItemRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.LevelDownItemResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, DecomposeItemRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.DecomposeItemResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, ClaimDailyRewardRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.ClaimDailyRewardResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, CreateItemRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.CreateItemResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, BuyItemRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.BuyItemResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, DisposeItemRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.DisposeItemResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, RerollItemOptionRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.RerollItemOptionResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, CreateReceiptRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.CreateReceiptResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, VerifyReceiptRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.VerifyReceiptResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, CreateBoardRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.CreateBoardResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, JoinBoardRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.JoinBoardResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, GetBoardRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.GetBoardResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, LeaveBoardRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.LeaveBoardResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, InteractBoardRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.InteractBoardResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, AutoPlayToTickBoardRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.AutoPlayToTickBoardResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, ClaimAchievementRewardRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.ClaimAchievementRewardResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, IncreaseAchievementRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.IncreaseAchievementResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, GetPlayerRankingRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.GetPlayerRankingResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, GetPlayerReferralsRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.GetPlayerReferralsResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, AddPlayerReferralRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.AddPlayerReferralResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, GetPlayerMailsRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.GetPlayerMailsResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, ReadPlayerMailsRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.ReadPlayerMailsResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, DeletePlayerMailsRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.DeletePlayerMailsResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, UpdatePlayerTelegramTonAddressRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.UpdatePlayerTelegramTonAddressResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, GetPlayerDefenseRankResultsRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.GetPlayerDefenseRankResultsResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, GetPlayerChatsRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.GetPlayerChatsResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, SendPlayerChatRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.SendPlayerChatResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, UpdatePlayerNameRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.UpdatePlayerNameResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, GetPlayerInfoRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.GetPlayerInfoResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, GetNoticesRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.GetNoticesResponse = response;
            return packet;
        }

        public static Packet Pop(byte key, ReadNoticeRequest.Types.Response response, long requestId = 0L)
        {
            var packet = Pool.Pop();
            packet.PacketType = Type.Request;
            packet.Key = key;
            packet.Request.Id = requestId;
            packet.Request.ReadNoticeResponse = response;
            return packet;
        }

    }
}
