using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

internal class PacketRequestsPopGenerator
{
    private static void Main(string[] args)
    {
        Console.WriteLine("Generating packet pop overloads");
        var workingDirectory = Directory.GetCurrentDirectory().Split("Generators")[0] + @"Packets\";
        var protoPath = $@"{workingDirectory}\Requests\Requests.proto";
        Console.WriteLine("proto path: " + protoPath);

        if (!File.Exists(protoPath))
        {
            Console.WriteLine("😒 Proto file not found");
            return;
        }

        var regex = new Regex(@"^\s*([a-zA-Z0-9\.]+)\s+([a-zA-Z0-9_]+)\s*=\s*\d+;");

        var requestMessages = new List<string>();
        var responseMessages = new List<string>();
        using (var reader = new StreamReader(protoPath))
        {
            var isRequestSection = false;
            while (reader.ReadLine() is { } line)
            {
                if (line.Contains("oneof Request"))
                {
                    isRequestSection = true;
                    continue;
                }

                if (!isRequestSection)
                    continue;

                if (line.Contains("}"))
                    break;

                var match = regex.Match(line);
                if (match.Success)
                {
                    var name = match.Groups[1].Value;
                    if (name.Contains(".Response"))
                    {
                        responseMessages.Add(name);
                    }
                    else
                    {
                        requestMessages.Add(name);
                    }
                }
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//  This code was generated by a tool.");
        sb.AppendLine("//");
        sb.AppendLine("//  Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//  the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using Commons.Packets.Requests;");
        sb.AppendLine();
        sb.AppendLine("namespace Commons.Packets");
        sb.AppendLine("{");
        sb.AppendLine("    public partial class Packet");
        sb.AppendLine("    {");
        sb.AppendLine("        public readonly Request Request = new();");
        foreach (var requestMessage in requestMessages)
        {
            sb.AppendLine($"        public static Packet Pop(byte key, {requestMessage} request)");
            sb.AppendLine("        {");
            sb.AppendLine("            var packet = Pool.Pop();");
            sb.AppendLine("            packet.PacketType = Type.Request;");
            sb.AppendLine("            packet.Key = key;");
            sb.AppendLine($"            packet.Request.{requestMessage} = request;");
            sb.AppendLine("            return packet;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
        foreach (var responseMessage in responseMessages)
        {
            sb.AppendLine($"        public static Packet Pop(byte key, {responseMessage.Replace(".Response", ".Types.Response")} response, long requestId = 0L)");
            sb.AppendLine("        {");
            sb.AppendLine("            var packet = Pool.Pop();");
            sb.AppendLine("            packet.PacketType = Type.Request;");
            sb.AppendLine("            packet.Key = key;");
            sb.AppendLine("            packet.Request.Id = requestId;");
            sb.AppendLine($"            packet.Request.{responseMessage.Replace("Request.Response", "Response")} = response;");
            sb.AppendLine("            return packet;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        var outputFilePath = $@"{workingDirectory}\Packet.Requests.Pop.generated.cs";
        
        if (Path.GetDirectoryName(outputFilePath) is { } directoryName)
        {
            Directory.CreateDirectory(directoryName);
            File.WriteAllText(outputFilePath, sb.ToString());

            Console.WriteLine($"👍 Successfully generated packet response extension. generate to {outputFilePath}");
        }
        else
        {
            Console.WriteLine($"😒 Failed to generate packet response extension. not found directory in {outputFilePath}");
        }

        Console.ResetColor();
    }
}