using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

internal class PacketUpdatesPopGenerator
{
    private static void Main(string[] args)
    {
        Console.WriteLine("Generating packet pop overloads");
        var workingDirectory = Directory.GetCurrentDirectory().Split("Generators")[0] + @"Packets\";
        var protoPath = $@"{workingDirectory}\Updates\Updates.proto";
        Console.WriteLine("proto path: " + protoPath);

        if (!File.Exists(protoPath))
        {
            Console.WriteLine("😒 Proto file not found");
            return;
        }

        var regex = new Regex(@"^\s*([a-zA-Z0-9\.]+)\s+([a-zA-Z0-9_]+)\s*=\s*\d+;");

        var messages = new List<string>();
        using (var reader = new StreamReader(protoPath))
        {
            var isOneofSection = false;
            while (reader.ReadLine() is { } line)
            {
                if (line.Contains("oneof Update"))
                {
                    isOneofSection = true;
                    continue;
                }

                if (!isOneofSection)
                    continue;

                if (line.Contains('}'))
                    break;

                var match = regex.Match(line);
                if (match.Success)
                {
                    var name = match.Groups[1].Value;
                    messages.Add(name);
                }
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//  This code was generated by a tool.");
        sb.AppendLine("//");
        sb.AppendLine("//  Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//  the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("using Commons.Packets.Updates;");
        sb.AppendLine();
        sb.AppendLine("namespace Commons.Packets");
        sb.AppendLine("{");
        sb.AppendLine("    public partial class Packet");
        sb.AppendLine("    {");
        sb.AppendLine("        public readonly Update Update = new();");
        foreach (var requestMessage in messages)
        {
            sb.AppendLine($"        public static Packet Pop(byte key, {requestMessage} update)");
            sb.AppendLine("        {");
            sb.AppendLine("            var packet = Pool.Pop();");
            sb.AppendLine("            packet.PacketType = Type.Update;");
            sb.AppendLine("            packet.Key = key;");
            sb.AppendLine($"            packet.Update.{requestMessage} = update;");
            sb.AppendLine("            return packet;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        var outputFilePath = $@"{workingDirectory}\Packet.Updates.Pop.generated.cs";
        
        if (Path.GetDirectoryName(outputFilePath) is { } directoryName)
        {
            Directory.CreateDirectory(directoryName);
            File.WriteAllText(outputFilePath, sb.ToString());

            Console.WriteLine($"👍 Successfully generated packet response extension. generate to {outputFilePath}");
        }
        else
        {
            Console.WriteLine($"😒 Failed to generate packet response extension. not found directory in {outputFilePath}");
        }

        Console.ResetColor();
    }
}