using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

internal class UpdateExtensionGenerator
{
    private static void Main(string[] args)
    {
        Console.WriteLine("Generating update response extension");
        var workingDirectory = Directory.GetCurrentDirectory().Split("Generators")[0] + @"Packets\Updates\";
        var protoPath = $@"{workingDirectory}\Updates.proto";
        Console.WriteLine("proto path: " + protoPath);

        if (!File.Exists(protoPath))
        {
            Console.WriteLine("😒 Proto file not found");
            return;
        }

        var regex = new Regex(@"^\s*([a-zA-Z0-9\.]+)\s+([a-zA-Z0-9_]+)\s*=\s*\d+;");

        var messages = new List<string>();
        var boardUpdates = new HashSet<string>();
        
        using (var reader = new StreamReader(protoPath))
        {
            var isOneofSection = false;
            while (reader.ReadLine() is { } line)
            {
                if (line.Contains("oneof Update"))
                {
                    isOneofSection = true;
                    continue;
                }

                if (!isOneofSection)
                    continue;

                if (line.Contains('}'))
                    break;

                var match = regex.Match(line);
                if (match.Success)
                {
                    var name = match.Groups[1].Value;
                    messages.Add(name);

                    if (line.Contains("--board-update"))
                        boardUpdates.Add(name);
                }
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//  This code was generated by a tool.");
        sb.AppendLine("//");
        sb.AppendLine("//  Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//  the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("namespace Commons.Packets.Updates");
        sb.AppendLine("{");
        foreach (var messageName in messages)
        {
            var interfaceString = "IUpdate";

            if (boardUpdates.Contains(messageName))
                interfaceString += ", IBoardUpdate";

            sb.AppendLine(@$"   public partial class {messageName} : {interfaceString} {{}}");
        }
        sb.AppendLine("}");


        var outputFilePath = $@"{workingDirectory}\Update.generated.cs";
        
        if (Path.GetDirectoryName(outputFilePath) is { } directoryName)
        {
            Directory.CreateDirectory(directoryName);
            File.WriteAllText(outputFilePath, sb.ToString());
            
            Console.WriteLine($"👍 Successfully generated packet update extension. generate to {outputFilePath}");
        }
        else
        {
            Console.WriteLine($"😒 Failed to generate packet update extension. generate to {outputFilePath}");
        }
        
    }
}