id: 110201
name: "이끼 포자"
tags: [Monster]
armorType: NormalArmor
warmupDelay: 2.0
targetMode: Chaser
targetAwareDistance: 24.0
targetResetDistance: 30.0

addStats:
  - { type: Hp, value: [140.0] }
  - { type: Attack, value: [14.0] }
  - { type: Defense, value: [5.0] }
  - { type: MoveSpeed, value: [3.1] }

triggers:
  - UNIT_ONSTART_SPORELINGWANDER
  - UNIT_ONUPDATE_SPORELINGATTACK

dropAddItemGroups:
  - shouldAddAll: true
    probPercent: 100
    addItems:
      - { itemDataId: 5, minCount: 18, maxCount: 28, isCore: true }
      - { itemDataId: 6, count: 8 }
  - shouldAddAll: false
    probPercent: 45
    addItems:
      - { itemDataId: 200101, count: 1, weight: 100, group: 1 }

prefab: "Units/Monsters/large_melee_slime_green.prefab"
sprite: "Units/Monsters/Assets/large_melee_slime.png"
uiScale: 1.0
