id: 110301
name: "황금 데굴록"
type: Normal
tags: [Monster, WeekdayDungeon, Monday, Gold]
armorType: NormalArmor
warmupDelay: 0.6
targetMode: Chaser
targetAwareDistance: 24.0
targetResetDistance: 30.0
deadDestroyDelaySeconds: 0.35

addStats:
  - { type: Hp, value: [95.0] }
  - { type: Attack, value: [7.0] }
  - { type: Defense, value: [2.0] }
  - { type: AttackSpeed, value: [1.6] }
  - { type: MoveSpeed, value: [4.4] }

triggers:
  - UNIT_ONSTART_WEEKDAYGOLDSWARMSTART
  - UNIT_ONUPDATE_WEEKDAYGOLDSWARMATTACK

dropAddItemGroups:
  - shouldAddAll: true
    probPercent: 100
    addItems:
      - { itemDataId: 5, minCount: 80, maxCount: 140, isCore: true }
  - shouldAddAll: false
    probPercent: 18
    addItems:
      - { itemDataId: 200101, count: 1, weight: 100, group: 1 }

prefab: "Units/Monsters/dungeonboss_melee_DegulRock.prefab"
sprite: "Units/Monsters/Assets/DegulRock.png"
animations:
  Idle: Idle
  Run: Run
  Attack: Attack1
  Dead: Dead
uiScale: 0.9
collideSize: { x: 0.9, y: 0.9 }
hitSize: { x: 1.0, y: 1.0 }
