// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AddDamage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Commons.Types.Units {

  /// <summary>Holder for reflection information generated from AddDamage.proto</summary>
  public static partial class AddDamageReflection {

    #region Descriptor
    /// <summary>File descriptor for AddDamage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AddDamageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9BZGREYW1hZ2UucHJvdG8SE0NvbW1vbnMuVHlwZXMuVW5pdHMaDlVzZVNr",
            "aWxsLnByb3RvIokDCglBZGREYW1hZ2USDwoHZGFtYWdlcxgBIAMoAxIcChRh",
            "dHRhY2tQZXJjZW50RGFtYWdlcxgCIAMoAhIYChBocFBlcmNlbnREYW1hZ2Vz",
            "GAMgAygCEhsKE21heEhwUGVyY2VudERhbWFnZXMYBCADKAISEQoJc3BEYW1h",
            "Z2VzGAUgAygDEg8KB2lzTWFnaWMYZCABKAgSGgoRa25vY2tiYWNrRHVyYXRp",
            "b24YyAEgASgCEhoKEWtub2NrYmFja0Rpc3RhbmNlGMkBIAEoAhIWCg1meE9u",
            "S25vY2tiYWNrGMoBIAEoCRIcChNkaXNhYmxlTW92ZUR1cmF0aW9uGKwCIAEo",
            "AhIeChVkaXNhYmxlQWN0aW9uRHVyYXRpb24YrQIgASgCEhAKB2Z4T25IaXQY",
            "kAMgASgJEhgKD2Z4T25Dcml0aWNhbEhpdBiRAyABKAkSOAoQb25EYW1hZ2VV",
            "c2VTa2lsbBiSAyABKAsyHS5Db21tb25zLlR5cGVzLlVuaXRzLlVzZVNraWxs",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Commons.Types.Units.UseSkillReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Types.Units.AddDamage), global::Commons.Types.Units.AddDamage.Parser, new[]{ "Damages", "AttackPercentDamages", "HpPercentDamages", "MaxHpPercentDamages", "SpDamages", "IsMagic", "KnockbackDuration", "KnockbackDistance", "FxOnKnockback", "DisableMoveDuration", "DisableActionDuration", "FxOnHit", "FxOnCriticalHit", "OnDamageUseSkill" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AddDamage : pb::IMessage<AddDamage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AddDamage> _parser = new pb::MessageParser<AddDamage>(() => new AddDamage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AddDamage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Commons.Types.Units.AddDamageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddDamage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddDamage(AddDamage other) : this() {
      damages_ = other.damages_.Clone();
      attackPercentDamages_ = other.attackPercentDamages_.Clone();
      hpPercentDamages_ = other.hpPercentDamages_.Clone();
      maxHpPercentDamages_ = other.maxHpPercentDamages_.Clone();
      spDamages_ = other.spDamages_.Clone();
      isMagic_ = other.isMagic_;
      knockbackDuration_ = other.knockbackDuration_;
      knockbackDistance_ = other.knockbackDistance_;
      fxOnKnockback_ = other.fxOnKnockback_;
      disableMoveDuration_ = other.disableMoveDuration_;
      disableActionDuration_ = other.disableActionDuration_;
      fxOnHit_ = other.fxOnHit_;
      fxOnCriticalHit_ = other.fxOnCriticalHit_;
      onDamageUseSkill_ = other.onDamageUseSkill_ != null ? other.onDamageUseSkill_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddDamage Clone() {
      return new AddDamage(this);
    }

    /// <summary>Field number for the "damages" field.</summary>
    public const int DamagesFieldNumber = 1;
    private static readonly pb::FieldCodec<long> _repeated_damages_codec
        = pb::FieldCodec.ForInt64(10);
    private readonly pbc::RepeatedField<long> damages_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> Damages {
      get { return damages_; }
    }

    /// <summary>Field number for the "attackPercentDamages" field.</summary>
    public const int AttackPercentDamagesFieldNumber = 2;
    private static readonly pb::FieldCodec<float> _repeated_attackPercentDamages_codec
        = pb::FieldCodec.ForFloat(18);
    private readonly pbc::RepeatedField<float> attackPercentDamages_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> AttackPercentDamages {
      get { return attackPercentDamages_; }
    }

    /// <summary>Field number for the "hpPercentDamages" field.</summary>
    public const int HpPercentDamagesFieldNumber = 3;
    private static readonly pb::FieldCodec<float> _repeated_hpPercentDamages_codec
        = pb::FieldCodec.ForFloat(26);
    private readonly pbc::RepeatedField<float> hpPercentDamages_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> HpPercentDamages {
      get { return hpPercentDamages_; }
    }

    /// <summary>Field number for the "maxHpPercentDamages" field.</summary>
    public const int MaxHpPercentDamagesFieldNumber = 4;
    private static readonly pb::FieldCodec<float> _repeated_maxHpPercentDamages_codec
        = pb::FieldCodec.ForFloat(34);
    private readonly pbc::RepeatedField<float> maxHpPercentDamages_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> MaxHpPercentDamages {
      get { return maxHpPercentDamages_; }
    }

    /// <summary>Field number for the "spDamages" field.</summary>
    public const int SpDamagesFieldNumber = 5;
    private static readonly pb::FieldCodec<long> _repeated_spDamages_codec
        = pb::FieldCodec.ForInt64(42);
    private readonly pbc::RepeatedField<long> spDamages_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> SpDamages {
      get { return spDamages_; }
    }

    /// <summary>Field number for the "isMagic" field.</summary>
    public const int IsMagicFieldNumber = 100;
    private bool isMagic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsMagic {
      get { return isMagic_; }
      set {
        isMagic_ = value;
      }
    }

    /// <summary>Field number for the "knockbackDuration" field.</summary>
    public const int KnockbackDurationFieldNumber = 200;
    private float knockbackDuration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float KnockbackDuration {
      get { return knockbackDuration_; }
      set {
        knockbackDuration_ = value;
      }
    }

    /// <summary>Field number for the "knockbackDistance" field.</summary>
    public const int KnockbackDistanceFieldNumber = 201;
    private float knockbackDistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float KnockbackDistance {
      get { return knockbackDistance_; }
      set {
        knockbackDistance_ = value;
      }
    }

    /// <summary>Field number for the "fxOnKnockback" field.</summary>
    public const int FxOnKnockbackFieldNumber = 202;
    private string fxOnKnockback_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FxOnKnockback {
      get { return fxOnKnockback_; }
      set {
        fxOnKnockback_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "disableMoveDuration" field.</summary>
    public const int DisableMoveDurationFieldNumber = 300;
    private float disableMoveDuration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float DisableMoveDuration {
      get { return disableMoveDuration_; }
      set {
        disableMoveDuration_ = value;
      }
    }

    /// <summary>Field number for the "disableActionDuration" field.</summary>
    public const int DisableActionDurationFieldNumber = 301;
    private float disableActionDuration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float DisableActionDuration {
      get { return disableActionDuration_; }
      set {
        disableActionDuration_ = value;
      }
    }

    /// <summary>Field number for the "fxOnHit" field.</summary>
    public const int FxOnHitFieldNumber = 400;
    private string fxOnHit_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FxOnHit {
      get { return fxOnHit_; }
      set {
        fxOnHit_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "fxOnCriticalHit" field.</summary>
    public const int FxOnCriticalHitFieldNumber = 401;
    private string fxOnCriticalHit_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FxOnCriticalHit {
      get { return fxOnCriticalHit_; }
      set {
        fxOnCriticalHit_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "onDamageUseSkill" field.</summary>
    public const int OnDamageUseSkillFieldNumber = 402;
    private global::Commons.Types.Units.UseSkill onDamageUseSkill_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Units.UseSkill OnDamageUseSkill {
      get { return onDamageUseSkill_; }
      set {
        onDamageUseSkill_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AddDamage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AddDamage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!damages_.Equals(other.damages_)) return false;
      if(!attackPercentDamages_.Equals(other.attackPercentDamages_)) return false;
      if(!hpPercentDamages_.Equals(other.hpPercentDamages_)) return false;
      if(!maxHpPercentDamages_.Equals(other.maxHpPercentDamages_)) return false;
      if(!spDamages_.Equals(other.spDamages_)) return false;
      if (IsMagic != other.IsMagic) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(KnockbackDuration, other.KnockbackDuration)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(KnockbackDistance, other.KnockbackDistance)) return false;
      if (FxOnKnockback != other.FxOnKnockback) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DisableMoveDuration, other.DisableMoveDuration)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DisableActionDuration, other.DisableActionDuration)) return false;
      if (FxOnHit != other.FxOnHit) return false;
      if (FxOnCriticalHit != other.FxOnCriticalHit) return false;
      if (!object.Equals(OnDamageUseSkill, other.OnDamageUseSkill)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= damages_.GetHashCode();
      hash ^= attackPercentDamages_.GetHashCode();
      hash ^= hpPercentDamages_.GetHashCode();
      hash ^= maxHpPercentDamages_.GetHashCode();
      hash ^= spDamages_.GetHashCode();
      if (IsMagic != false) hash ^= IsMagic.GetHashCode();
      if (KnockbackDuration != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(KnockbackDuration);
      if (KnockbackDistance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(KnockbackDistance);
      if (FxOnKnockback.Length != 0) hash ^= FxOnKnockback.GetHashCode();
      if (DisableMoveDuration != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DisableMoveDuration);
      if (DisableActionDuration != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DisableActionDuration);
      if (FxOnHit.Length != 0) hash ^= FxOnHit.GetHashCode();
      if (FxOnCriticalHit.Length != 0) hash ^= FxOnCriticalHit.GetHashCode();
      if (onDamageUseSkill_ != null) hash ^= OnDamageUseSkill.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      damages_.WriteTo(output, _repeated_damages_codec);
      attackPercentDamages_.WriteTo(output, _repeated_attackPercentDamages_codec);
      hpPercentDamages_.WriteTo(output, _repeated_hpPercentDamages_codec);
      maxHpPercentDamages_.WriteTo(output, _repeated_maxHpPercentDamages_codec);
      spDamages_.WriteTo(output, _repeated_spDamages_codec);
      if (IsMagic != false) {
        output.WriteRawTag(160, 6);
        output.WriteBool(IsMagic);
      }
      if (KnockbackDuration != 0F) {
        output.WriteRawTag(197, 12);
        output.WriteFloat(KnockbackDuration);
      }
      if (KnockbackDistance != 0F) {
        output.WriteRawTag(205, 12);
        output.WriteFloat(KnockbackDistance);
      }
      if (FxOnKnockback.Length != 0) {
        output.WriteRawTag(210, 12);
        output.WriteString(FxOnKnockback);
      }
      if (DisableMoveDuration != 0F) {
        output.WriteRawTag(229, 18);
        output.WriteFloat(DisableMoveDuration);
      }
      if (DisableActionDuration != 0F) {
        output.WriteRawTag(237, 18);
        output.WriteFloat(DisableActionDuration);
      }
      if (FxOnHit.Length != 0) {
        output.WriteRawTag(130, 25);
        output.WriteString(FxOnHit);
      }
      if (FxOnCriticalHit.Length != 0) {
        output.WriteRawTag(138, 25);
        output.WriteString(FxOnCriticalHit);
      }
      if (onDamageUseSkill_ != null) {
        output.WriteRawTag(146, 25);
        output.WriteMessage(OnDamageUseSkill);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      damages_.WriteTo(ref output, _repeated_damages_codec);
      attackPercentDamages_.WriteTo(ref output, _repeated_attackPercentDamages_codec);
      hpPercentDamages_.WriteTo(ref output, _repeated_hpPercentDamages_codec);
      maxHpPercentDamages_.WriteTo(ref output, _repeated_maxHpPercentDamages_codec);
      spDamages_.WriteTo(ref output, _repeated_spDamages_codec);
      if (IsMagic != false) {
        output.WriteRawTag(160, 6);
        output.WriteBool(IsMagic);
      }
      if (KnockbackDuration != 0F) {
        output.WriteRawTag(197, 12);
        output.WriteFloat(KnockbackDuration);
      }
      if (KnockbackDistance != 0F) {
        output.WriteRawTag(205, 12);
        output.WriteFloat(KnockbackDistance);
      }
      if (FxOnKnockback.Length != 0) {
        output.WriteRawTag(210, 12);
        output.WriteString(FxOnKnockback);
      }
      if (DisableMoveDuration != 0F) {
        output.WriteRawTag(229, 18);
        output.WriteFloat(DisableMoveDuration);
      }
      if (DisableActionDuration != 0F) {
        output.WriteRawTag(237, 18);
        output.WriteFloat(DisableActionDuration);
      }
      if (FxOnHit.Length != 0) {
        output.WriteRawTag(130, 25);
        output.WriteString(FxOnHit);
      }
      if (FxOnCriticalHit.Length != 0) {
        output.WriteRawTag(138, 25);
        output.WriteString(FxOnCriticalHit);
      }
      if (onDamageUseSkill_ != null) {
        output.WriteRawTag(146, 25);
        output.WriteMessage(OnDamageUseSkill);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += damages_.CalculateSize(_repeated_damages_codec);
      size += attackPercentDamages_.CalculateSize(_repeated_attackPercentDamages_codec);
      size += hpPercentDamages_.CalculateSize(_repeated_hpPercentDamages_codec);
      size += maxHpPercentDamages_.CalculateSize(_repeated_maxHpPercentDamages_codec);
      size += spDamages_.CalculateSize(_repeated_spDamages_codec);
      if (IsMagic != false) {
        size += 2 + 1;
      }
      if (KnockbackDuration != 0F) {
        size += 2 + 4;
      }
      if (KnockbackDistance != 0F) {
        size += 2 + 4;
      }
      if (FxOnKnockback.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(FxOnKnockback);
      }
      if (DisableMoveDuration != 0F) {
        size += 2 + 4;
      }
      if (DisableActionDuration != 0F) {
        size += 2 + 4;
      }
      if (FxOnHit.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(FxOnHit);
      }
      if (FxOnCriticalHit.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(FxOnCriticalHit);
      }
      if (onDamageUseSkill_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(OnDamageUseSkill);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AddDamage other) {
      if (other == null) {
        return;
      }
      damages_.Add(other.damages_);
      attackPercentDamages_.Add(other.attackPercentDamages_);
      hpPercentDamages_.Add(other.hpPercentDamages_);
      maxHpPercentDamages_.Add(other.maxHpPercentDamages_);
      spDamages_.Add(other.spDamages_);
      if (other.IsMagic != false) {
        IsMagic = other.IsMagic;
      }
      if (other.KnockbackDuration != 0F) {
        KnockbackDuration = other.KnockbackDuration;
      }
      if (other.KnockbackDistance != 0F) {
        KnockbackDistance = other.KnockbackDistance;
      }
      if (other.FxOnKnockback.Length != 0) {
        FxOnKnockback = other.FxOnKnockback;
      }
      if (other.DisableMoveDuration != 0F) {
        DisableMoveDuration = other.DisableMoveDuration;
      }
      if (other.DisableActionDuration != 0F) {
        DisableActionDuration = other.DisableActionDuration;
      }
      if (other.FxOnHit.Length != 0) {
        FxOnHit = other.FxOnHit;
      }
      if (other.FxOnCriticalHit.Length != 0) {
        FxOnCriticalHit = other.FxOnCriticalHit;
      }
      if (other.onDamageUseSkill_ != null) {
        if (onDamageUseSkill_ == null) {
          OnDamageUseSkill = new global::Commons.Types.Units.UseSkill();
        }
        OnDamageUseSkill.MergeFrom(other.OnDamageUseSkill);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            damages_.AddEntriesFrom(input, _repeated_damages_codec);
            break;
          }
          case 18:
          case 21: {
            attackPercentDamages_.AddEntriesFrom(input, _repeated_attackPercentDamages_codec);
            break;
          }
          case 26:
          case 29: {
            hpPercentDamages_.AddEntriesFrom(input, _repeated_hpPercentDamages_codec);
            break;
          }
          case 34:
          case 37: {
            maxHpPercentDamages_.AddEntriesFrom(input, _repeated_maxHpPercentDamages_codec);
            break;
          }
          case 42:
          case 40: {
            spDamages_.AddEntriesFrom(input, _repeated_spDamages_codec);
            break;
          }
          case 800: {
            IsMagic = input.ReadBool();
            break;
          }
          case 1605: {
            KnockbackDuration = input.ReadFloat();
            break;
          }
          case 1613: {
            KnockbackDistance = input.ReadFloat();
            break;
          }
          case 1618: {
            FxOnKnockback = input.ReadString();
            break;
          }
          case 2405: {
            DisableMoveDuration = input.ReadFloat();
            break;
          }
          case 2413: {
            DisableActionDuration = input.ReadFloat();
            break;
          }
          case 3202: {
            FxOnHit = input.ReadString();
            break;
          }
          case 3210: {
            FxOnCriticalHit = input.ReadString();
            break;
          }
          case 3218: {
            if (onDamageUseSkill_ == null) {
              OnDamageUseSkill = new global::Commons.Types.Units.UseSkill();
            }
            input.ReadMessage(OnDamageUseSkill);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            damages_.AddEntriesFrom(ref input, _repeated_damages_codec);
            break;
          }
          case 18:
          case 21: {
            attackPercentDamages_.AddEntriesFrom(ref input, _repeated_attackPercentDamages_codec);
            break;
          }
          case 26:
          case 29: {
            hpPercentDamages_.AddEntriesFrom(ref input, _repeated_hpPercentDamages_codec);
            break;
          }
          case 34:
          case 37: {
            maxHpPercentDamages_.AddEntriesFrom(ref input, _repeated_maxHpPercentDamages_codec);
            break;
          }
          case 42:
          case 40: {
            spDamages_.AddEntriesFrom(ref input, _repeated_spDamages_codec);
            break;
          }
          case 800: {
            IsMagic = input.ReadBool();
            break;
          }
          case 1605: {
            KnockbackDuration = input.ReadFloat();
            break;
          }
          case 1613: {
            KnockbackDistance = input.ReadFloat();
            break;
          }
          case 1618: {
            FxOnKnockback = input.ReadString();
            break;
          }
          case 2405: {
            DisableMoveDuration = input.ReadFloat();
            break;
          }
          case 2413: {
            DisableActionDuration = input.ReadFloat();
            break;
          }
          case 3202: {
            FxOnHit = input.ReadString();
            break;
          }
          case 3210: {
            FxOnCriticalHit = input.ReadString();
            break;
          }
          case 3218: {
            if (onDamageUseSkill_ == null) {
              OnDamageUseSkill = new global::Commons.Types.Units.UseSkill();
            }
            input.ReadMessage(OnDamageUseSkill);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
