// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AddHeal.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Commons.Types.Units {

  /// <summary>Holder for reflection information generated from AddHeal.proto</summary>
  public static partial class AddHealReflection {

    #region Descriptor
    /// <summary>File descriptor for AddHeal.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AddHealReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1BZGRIZWFsLnByb3RvEhNDb21tb25zLlR5cGVzLlVuaXRzGg5Vc2VTa2ls",
            "bC5wcm90byLdAQoHQWRkSGVhbBINCgVoZWFscxgBIAMoAxIaChJhdHRhY2tQ",
            "ZXJjZW50SGVhbHMYAiADKAISDwoHc3BIZWFscxgDIAMoAxIZChFtYXhIcFBl",
            "cmNlbnRIZWFscxgEIAMoAhISCgpndWFyZEhlYWxzGAUgAygDEh8KF21heEhw",
            "UGVyY2VudFNoaWVsZEhlYWxzGAYgAygCEg8KB2Z4T25IaXQYZCABKAkSNQoO",
            "b25IZWFsVXNlU2tpbGwYZSABKAsyHS5Db21tb25zLlR5cGVzLlVuaXRzLlVz",
            "ZVNraWxsYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Commons.Types.Units.UseSkillReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Types.Units.AddHeal), global::Commons.Types.Units.AddHeal.Parser, new[]{ "Heals", "AttackPercentHeals", "SpHeals", "MaxHpPercentHeals", "GuardHeals", "MaxHpPercentShieldHeals", "FxOnHit", "OnHealUseSkill" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AddHeal : pb::IMessage<AddHeal>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AddHeal> _parser = new pb::MessageParser<AddHeal>(() => new AddHeal());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AddHeal> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Commons.Types.Units.AddHealReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddHeal() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddHeal(AddHeal other) : this() {
      heals_ = other.heals_.Clone();
      attackPercentHeals_ = other.attackPercentHeals_.Clone();
      spHeals_ = other.spHeals_.Clone();
      maxHpPercentHeals_ = other.maxHpPercentHeals_.Clone();
      guardHeals_ = other.guardHeals_.Clone();
      maxHpPercentShieldHeals_ = other.maxHpPercentShieldHeals_.Clone();
      fxOnHit_ = other.fxOnHit_;
      onHealUseSkill_ = other.onHealUseSkill_ != null ? other.onHealUseSkill_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddHeal Clone() {
      return new AddHeal(this);
    }

    /// <summary>Field number for the "heals" field.</summary>
    public const int HealsFieldNumber = 1;
    private static readonly pb::FieldCodec<long> _repeated_heals_codec
        = pb::FieldCodec.ForInt64(10);
    private readonly pbc::RepeatedField<long> heals_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> Heals {
      get { return heals_; }
    }

    /// <summary>Field number for the "attackPercentHeals" field.</summary>
    public const int AttackPercentHealsFieldNumber = 2;
    private static readonly pb::FieldCodec<float> _repeated_attackPercentHeals_codec
        = pb::FieldCodec.ForFloat(18);
    private readonly pbc::RepeatedField<float> attackPercentHeals_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> AttackPercentHeals {
      get { return attackPercentHeals_; }
    }

    /// <summary>Field number for the "spHeals" field.</summary>
    public const int SpHealsFieldNumber = 3;
    private static readonly pb::FieldCodec<long> _repeated_spHeals_codec
        = pb::FieldCodec.ForInt64(26);
    private readonly pbc::RepeatedField<long> spHeals_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> SpHeals {
      get { return spHeals_; }
    }

    /// <summary>Field number for the "maxHpPercentHeals" field.</summary>
    public const int MaxHpPercentHealsFieldNumber = 4;
    private static readonly pb::FieldCodec<float> _repeated_maxHpPercentHeals_codec
        = pb::FieldCodec.ForFloat(34);
    private readonly pbc::RepeatedField<float> maxHpPercentHeals_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> MaxHpPercentHeals {
      get { return maxHpPercentHeals_; }
    }

    /// <summary>Field number for the "guardHeals" field.</summary>
    public const int GuardHealsFieldNumber = 5;
    private static readonly pb::FieldCodec<long> _repeated_guardHeals_codec
        = pb::FieldCodec.ForInt64(42);
    private readonly pbc::RepeatedField<long> guardHeals_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<long> GuardHeals {
      get { return guardHeals_; }
    }

    /// <summary>Field number for the "maxHpPercentShieldHeals" field.</summary>
    public const int MaxHpPercentShieldHealsFieldNumber = 6;
    private static readonly pb::FieldCodec<float> _repeated_maxHpPercentShieldHeals_codec
        = pb::FieldCodec.ForFloat(50);
    private readonly pbc::RepeatedField<float> maxHpPercentShieldHeals_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> MaxHpPercentShieldHeals {
      get { return maxHpPercentShieldHeals_; }
    }

    /// <summary>Field number for the "fxOnHit" field.</summary>
    public const int FxOnHitFieldNumber = 100;
    private string fxOnHit_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FxOnHit {
      get { return fxOnHit_; }
      set {
        fxOnHit_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "onHealUseSkill" field.</summary>
    public const int OnHealUseSkillFieldNumber = 101;
    private global::Commons.Types.Units.UseSkill onHealUseSkill_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Units.UseSkill OnHealUseSkill {
      get { return onHealUseSkill_; }
      set {
        onHealUseSkill_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AddHeal);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AddHeal other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!heals_.Equals(other.heals_)) return false;
      if(!attackPercentHeals_.Equals(other.attackPercentHeals_)) return false;
      if(!spHeals_.Equals(other.spHeals_)) return false;
      if(!maxHpPercentHeals_.Equals(other.maxHpPercentHeals_)) return false;
      if(!guardHeals_.Equals(other.guardHeals_)) return false;
      if(!maxHpPercentShieldHeals_.Equals(other.maxHpPercentShieldHeals_)) return false;
      if (FxOnHit != other.FxOnHit) return false;
      if (!object.Equals(OnHealUseSkill, other.OnHealUseSkill)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= heals_.GetHashCode();
      hash ^= attackPercentHeals_.GetHashCode();
      hash ^= spHeals_.GetHashCode();
      hash ^= maxHpPercentHeals_.GetHashCode();
      hash ^= guardHeals_.GetHashCode();
      hash ^= maxHpPercentShieldHeals_.GetHashCode();
      if (FxOnHit.Length != 0) hash ^= FxOnHit.GetHashCode();
      if (onHealUseSkill_ != null) hash ^= OnHealUseSkill.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      heals_.WriteTo(output, _repeated_heals_codec);
      attackPercentHeals_.WriteTo(output, _repeated_attackPercentHeals_codec);
      spHeals_.WriteTo(output, _repeated_spHeals_codec);
      maxHpPercentHeals_.WriteTo(output, _repeated_maxHpPercentHeals_codec);
      guardHeals_.WriteTo(output, _repeated_guardHeals_codec);
      maxHpPercentShieldHeals_.WriteTo(output, _repeated_maxHpPercentShieldHeals_codec);
      if (FxOnHit.Length != 0) {
        output.WriteRawTag(162, 6);
        output.WriteString(FxOnHit);
      }
      if (onHealUseSkill_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(OnHealUseSkill);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      heals_.WriteTo(ref output, _repeated_heals_codec);
      attackPercentHeals_.WriteTo(ref output, _repeated_attackPercentHeals_codec);
      spHeals_.WriteTo(ref output, _repeated_spHeals_codec);
      maxHpPercentHeals_.WriteTo(ref output, _repeated_maxHpPercentHeals_codec);
      guardHeals_.WriteTo(ref output, _repeated_guardHeals_codec);
      maxHpPercentShieldHeals_.WriteTo(ref output, _repeated_maxHpPercentShieldHeals_codec);
      if (FxOnHit.Length != 0) {
        output.WriteRawTag(162, 6);
        output.WriteString(FxOnHit);
      }
      if (onHealUseSkill_ != null) {
        output.WriteRawTag(170, 6);
        output.WriteMessage(OnHealUseSkill);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += heals_.CalculateSize(_repeated_heals_codec);
      size += attackPercentHeals_.CalculateSize(_repeated_attackPercentHeals_codec);
      size += spHeals_.CalculateSize(_repeated_spHeals_codec);
      size += maxHpPercentHeals_.CalculateSize(_repeated_maxHpPercentHeals_codec);
      size += guardHeals_.CalculateSize(_repeated_guardHeals_codec);
      size += maxHpPercentShieldHeals_.CalculateSize(_repeated_maxHpPercentShieldHeals_codec);
      if (FxOnHit.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(FxOnHit);
      }
      if (onHealUseSkill_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(OnHealUseSkill);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AddHeal other) {
      if (other == null) {
        return;
      }
      heals_.Add(other.heals_);
      attackPercentHeals_.Add(other.attackPercentHeals_);
      spHeals_.Add(other.spHeals_);
      maxHpPercentHeals_.Add(other.maxHpPercentHeals_);
      guardHeals_.Add(other.guardHeals_);
      maxHpPercentShieldHeals_.Add(other.maxHpPercentShieldHeals_);
      if (other.FxOnHit.Length != 0) {
        FxOnHit = other.FxOnHit;
      }
      if (other.onHealUseSkill_ != null) {
        if (onHealUseSkill_ == null) {
          OnHealUseSkill = new global::Commons.Types.Units.UseSkill();
        }
        OnHealUseSkill.MergeFrom(other.OnHealUseSkill);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            heals_.AddEntriesFrom(input, _repeated_heals_codec);
            break;
          }
          case 18:
          case 21: {
            attackPercentHeals_.AddEntriesFrom(input, _repeated_attackPercentHeals_codec);
            break;
          }
          case 26:
          case 24: {
            spHeals_.AddEntriesFrom(input, _repeated_spHeals_codec);
            break;
          }
          case 34:
          case 37: {
            maxHpPercentHeals_.AddEntriesFrom(input, _repeated_maxHpPercentHeals_codec);
            break;
          }
          case 42:
          case 40: {
            guardHeals_.AddEntriesFrom(input, _repeated_guardHeals_codec);
            break;
          }
          case 50:
          case 53: {
            maxHpPercentShieldHeals_.AddEntriesFrom(input, _repeated_maxHpPercentShieldHeals_codec);
            break;
          }
          case 802: {
            FxOnHit = input.ReadString();
            break;
          }
          case 810: {
            if (onHealUseSkill_ == null) {
              OnHealUseSkill = new global::Commons.Types.Units.UseSkill();
            }
            input.ReadMessage(OnHealUseSkill);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            heals_.AddEntriesFrom(ref input, _repeated_heals_codec);
            break;
          }
          case 18:
          case 21: {
            attackPercentHeals_.AddEntriesFrom(ref input, _repeated_attackPercentHeals_codec);
            break;
          }
          case 26:
          case 24: {
            spHeals_.AddEntriesFrom(ref input, _repeated_spHeals_codec);
            break;
          }
          case 34:
          case 37: {
            maxHpPercentHeals_.AddEntriesFrom(ref input, _repeated_maxHpPercentHeals_codec);
            break;
          }
          case 42:
          case 40: {
            guardHeals_.AddEntriesFrom(ref input, _repeated_guardHeals_codec);
            break;
          }
          case 50:
          case 53: {
            maxHpPercentShieldHeals_.AddEntriesFrom(ref input, _repeated_maxHpPercentShieldHeals_codec);
            break;
          }
          case 802: {
            FxOnHit = input.ReadString();
            break;
          }
          case 810: {
            if (onHealUseSkill_ == null) {
              OnHealUseSkill = new global::Commons.Types.Units.UseSkill();
            }
            input.ReadMessage(OnHealUseSkill);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
