// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: UseSkill.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Commons.Types.Units {

  /// <summary>Holder for reflection information generated from UseSkill.proto</summary>
  public static partial class UseSkillReflection {

    #region Descriptor
    /// <summary>File descriptor for UseSkill.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UseSkillReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5Vc2VTa2lsbC5wcm90bxITQ29tbW9ucy5UeXBlcy5Vbml0cxoVR2VvbWV0",
            "cnlNZXNzYWdlLnByb3RvIoABCghVc2VTa2lsbBITCgtza2lsbERhdGFJZBhk",
            "IAEoBRIRCghhdFRhcmdldBjIASABKAgSOQoIcG9zaXRpb24YyQEgASgLMiYu",
            "Q29tbW9ucy5UeXBlcy5HZW9tZXRyeS5WZWN0b3IyTWVzc2FnZRIRCghyb3Rh",
            "dGlvbhjKASABKAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Commons.Types.Geometry.GeometryMessageReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Types.Units.UseSkill), global::Commons.Types.Units.UseSkill.Parser, new[]{ "SkillDataId", "AtTarget", "Position", "Rotation" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UseSkill : pb::IMessage<UseSkill>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UseSkill> _parser = new pb::MessageParser<UseSkill>(() => new UseSkill());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UseSkill> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Commons.Types.Units.UseSkillReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UseSkill() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UseSkill(UseSkill other) : this() {
      skillDataId_ = other.skillDataId_;
      atTarget_ = other.atTarget_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      rotation_ = other.rotation_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UseSkill Clone() {
      return new UseSkill(this);
    }

    /// <summary>Field number for the "skillDataId" field.</summary>
    public const int SkillDataIdFieldNumber = 100;
    private int skillDataId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SkillDataId {
      get { return skillDataId_; }
      set {
        skillDataId_ = value;
      }
    }

    /// <summary>Field number for the "atTarget" field.</summary>
    public const int AtTargetFieldNumber = 200;
    private bool atTarget_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool AtTarget {
      get { return atTarget_; }
      set {
        atTarget_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 201;
    private global::Commons.Types.Geometry.Vector2Message position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Geometry.Vector2Message Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "rotation" field.</summary>
    public const int RotationFieldNumber = 202;
    private float rotation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Rotation {
      get { return rotation_; }
      set {
        rotation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UseSkill);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UseSkill other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SkillDataId != other.SkillDataId) return false;
      if (AtTarget != other.AtTarget) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Rotation, other.Rotation)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SkillDataId != 0) hash ^= SkillDataId.GetHashCode();
      if (AtTarget != false) hash ^= AtTarget.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (Rotation != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Rotation);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SkillDataId != 0) {
        output.WriteRawTag(160, 6);
        output.WriteInt32(SkillDataId);
      }
      if (AtTarget != false) {
        output.WriteRawTag(192, 12);
        output.WriteBool(AtTarget);
      }
      if (position_ != null) {
        output.WriteRawTag(202, 12);
        output.WriteMessage(Position);
      }
      if (Rotation != 0F) {
        output.WriteRawTag(213, 12);
        output.WriteFloat(Rotation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SkillDataId != 0) {
        output.WriteRawTag(160, 6);
        output.WriteInt32(SkillDataId);
      }
      if (AtTarget != false) {
        output.WriteRawTag(192, 12);
        output.WriteBool(AtTarget);
      }
      if (position_ != null) {
        output.WriteRawTag(202, 12);
        output.WriteMessage(Position);
      }
      if (Rotation != 0F) {
        output.WriteRawTag(213, 12);
        output.WriteFloat(Rotation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SkillDataId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(SkillDataId);
      }
      if (AtTarget != false) {
        size += 2 + 1;
      }
      if (position_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (Rotation != 0F) {
        size += 2 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UseSkill other) {
      if (other == null) {
        return;
      }
      if (other.SkillDataId != 0) {
        SkillDataId = other.SkillDataId;
      }
      if (other.AtTarget != false) {
        AtTarget = other.AtTarget;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Commons.Types.Geometry.Vector2Message();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.Rotation != 0F) {
        Rotation = other.Rotation;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 800: {
            SkillDataId = input.ReadInt32();
            break;
          }
          case 1600: {
            AtTarget = input.ReadBool();
            break;
          }
          case 1610: {
            if (position_ == null) {
              Position = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(Position);
            break;
          }
          case 1621: {
            Rotation = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 800: {
            SkillDataId = input.ReadInt32();
            break;
          }
          case 1600: {
            AtTarget = input.ReadBool();
            break;
          }
          case 1610: {
            if (position_ == null) {
              Position = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(Position);
            break;
          }
          case 1621: {
            Rotation = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
