// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DamageTypeStatType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Commons.Types.Units.DamageTypeStat {

  /// <summary>Holder for reflection information generated from DamageTypeStatType.proto</summary>
  public static partial class DamageTypeStatTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for DamageTypeStatType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DamageTypeStatTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhEYW1hZ2VUeXBlU3RhdFR5cGUucHJvdG8SIkNvbW1vbnMuVHlwZXMuVW5p",
            "dHMuRGFtYWdlVHlwZVN0YXQaEERhbWFnZVR5cGUucHJvdG8inQEKEUFkZERh",
            "bWFnZVR5cGVTdGF0EjMKCmRhbWFnZVR5cGUYASABKA4yHy5Db21tb25zLlR5",
            "cGVzLlVuaXRzLkRhbWFnZVR5cGUSRAoEdHlwZRgCIAEoDjI2LkNvbW1vbnMu",
            "VHlwZXMuVW5pdHMuRGFtYWdlVHlwZVN0YXQuRGFtYWdlVHlwZVN0YXRUeXBl",
            "Eg0KBXZhbHVlGAMgAygCKkgKEkRhbWFnZVR5cGVTdGF0VHlwZRIRCg1EYW1h",
            "Z2VQZXJjZW50EAASFAoQR290RGFtYWdlUGVyY2VudBABEgkKBUNvdW50EAJi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Commons.Types.Units.DamageTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Commons.Types.Units.DamageTypeStat.DamageTypeStatType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Types.Units.DamageTypeStat.AddDamageTypeStat), global::Commons.Types.Units.DamageTypeStat.AddDamageTypeStat.Parser, new[]{ "DamageType", "Type", "Value" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum DamageTypeStatType {
    [pbr::OriginalName("DamagePercent")] DamagePercent = 0,
    [pbr::OriginalName("GotDamagePercent")] GotDamagePercent = 1,
    [pbr::OriginalName("Count")] Count = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class AddDamageTypeStat : pb::IMessage<AddDamageTypeStat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<AddDamageTypeStat> _parser = new pb::MessageParser<AddDamageTypeStat>(() => new AddDamageTypeStat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<AddDamageTypeStat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Commons.Types.Units.DamageTypeStat.DamageTypeStatTypeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddDamageTypeStat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddDamageTypeStat(AddDamageTypeStat other) : this() {
      damageType_ = other.damageType_;
      type_ = other.type_;
      value_ = other.value_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public AddDamageTypeStat Clone() {
      return new AddDamageTypeStat(this);
    }

    /// <summary>Field number for the "damageType" field.</summary>
    public const int DamageTypeFieldNumber = 1;
    private global::Commons.Types.Units.DamageType damageType_ = global::Commons.Types.Units.DamageType.NormalDamage;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Units.DamageType DamageType {
      get { return damageType_; }
      set {
        damageType_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::Commons.Types.Units.DamageTypeStat.DamageTypeStatType type_ = global::Commons.Types.Units.DamageTypeStat.DamageTypeStatType.DamagePercent;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Units.DamageTypeStat.DamageTypeStatType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 3;
    private static readonly pb::FieldCodec<float> _repeated_value_codec
        = pb::FieldCodec.ForFloat(26);
    private readonly pbc::RepeatedField<float> value_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Value {
      get { return value_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as AddDamageTypeStat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(AddDamageTypeStat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DamageType != other.DamageType) return false;
      if (Type != other.Type) return false;
      if(!value_.Equals(other.value_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DamageType != global::Commons.Types.Units.DamageType.NormalDamage) hash ^= DamageType.GetHashCode();
      if (Type != global::Commons.Types.Units.DamageTypeStat.DamageTypeStatType.DamagePercent) hash ^= Type.GetHashCode();
      hash ^= value_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DamageType != global::Commons.Types.Units.DamageType.NormalDamage) {
        output.WriteRawTag(8);
        output.WriteEnum((int) DamageType);
      }
      if (Type != global::Commons.Types.Units.DamageTypeStat.DamageTypeStatType.DamagePercent) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      value_.WriteTo(output, _repeated_value_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DamageType != global::Commons.Types.Units.DamageType.NormalDamage) {
        output.WriteRawTag(8);
        output.WriteEnum((int) DamageType);
      }
      if (Type != global::Commons.Types.Units.DamageTypeStat.DamageTypeStatType.DamagePercent) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      value_.WriteTo(ref output, _repeated_value_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DamageType != global::Commons.Types.Units.DamageType.NormalDamage) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DamageType);
      }
      if (Type != global::Commons.Types.Units.DamageTypeStat.DamageTypeStatType.DamagePercent) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      size += value_.CalculateSize(_repeated_value_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(AddDamageTypeStat other) {
      if (other == null) {
        return;
      }
      if (other.DamageType != global::Commons.Types.Units.DamageType.NormalDamage) {
        DamageType = other.DamageType;
      }
      if (other.Type != global::Commons.Types.Units.DamageTypeStat.DamageTypeStatType.DamagePercent) {
        Type = other.Type;
      }
      value_.Add(other.value_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DamageType = (global::Commons.Types.Units.DamageType) input.ReadEnum();
            break;
          }
          case 16: {
            Type = (global::Commons.Types.Units.DamageTypeStat.DamageTypeStatType) input.ReadEnum();
            break;
          }
          case 26:
          case 29: {
            value_.AddEntriesFrom(input, _repeated_value_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DamageType = (global::Commons.Types.Units.DamageType) input.ReadEnum();
            break;
          }
          case 16: {
            Type = (global::Commons.Types.Units.DamageTypeStat.DamageTypeStatType) input.ReadEnum();
            break;
          }
          case 26:
          case 29: {
            value_.AddEntriesFrom(ref input, _repeated_value_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
