// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameBoard.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Commons.Game {

  /// <summary>Holder for reflection information generated from GameBoard.proto</summary>
  public static partial class GameBoardReflection {

    #region Descriptor
    /// <summary>File descriptor for GameBoard.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameBoardReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9HYW1lQm9hcmQucHJvdG8SDENvbW1vbnMuR2FtZRofZ29vZ2xlL3Byb3Rv",
            "YnVmL3RpbWVzdGFtcC5wcm90bxoOR2FtZVVuaXQucHJvdG8aD0dhbWVTa2ls",
            "bC5wcm90bxoSR2FtZURyb3BJdGVtLnByb3RvGhVSZXNvdXJjZVRyaWdnZXIu",
            "cHJvdG8aDFBsYXllci5wcm90bxoXUGxheWVyQWNoaWV2ZW1lbnQucHJvdG8a",
            "ElBsYXllckF2YXRhci5wcm90byLfDAoJR2FtZUJvYXJkEjUKB3BsYXllcnMY",
            "ASADKAsyJC5Db21tb25zLkdhbWUuR2FtZUJvYXJkLlBsYXllcnNFbnRyeRI/",
            "CgxhY2hpZXZlbWVudHMYAiADKAsyKS5Db21tb25zLkdhbWUuR2FtZUJvYXJk",
            "LkFjaGlldmVtZW50c0VudHJ5ElcKGGRpc2FibGVkVGVycmFpblRyaWFuZ2xl",
            "cxgDIAMoCzI1LkNvbW1vbnMuR2FtZS5HYW1lQm9hcmQuRGlzYWJsZWRUZXJy",
            "YWluVHJpYW5nbGVzRW50cnkSMQoFdW5pdHMYBCADKAsyIi5Db21tb25zLkdh",
            "bWUuR2FtZUJvYXJkLlVuaXRzRW50cnkSMwoGc2tpbGxzGAUgAygLMiMuQ29t",
            "bW9ucy5HYW1lLkdhbWVCb2FyZC5Ta2lsbHNFbnRyeRI5Cglkcm9wSXRlbXMY",
            "BiADKAsyJi5Db21tb25zLkdhbWUuR2FtZUJvYXJkLkRyb3BJdGVtc0VudHJ5",
            "EgoKAmlkGGQgASgDEg4KBmRhdGFJZBhlIAEoBRINCgR0aWNrGMgBIAEoDRIN",
            "CgRzZWVkGMkBIAEoDRJACgl2YXJpYWJsZXMYygEgASgLMiwuQ29tbW9ucy5S",
            "ZXNvdXJjZXMuUmVzb3VyY2VUcmlnZ2VyLlZhcmlhYmxlcxIXCg50aW1lclN0",
            "YXJ0VGljaxjLASABKA0SFwoOdGltZXJQYXVzZVRpY2sYzAEgASgNEhUKDHRp",
            "bWVyRW5kVGljaxjNASABKA0SFAoLd2lubmluZ1RlYW0YzgEgASgFEi0KBXN0",
            "YXRlGM8BIAEoDjIdLkNvbW1vbnMuR2FtZS5HYW1lQm9hcmQuU3RhdGUSGQoQ",
            "YWN0aW9uQmxvY2tGbGFncxjQASABKAQSEwoKbmV4dFVuaXRJZBisAiABKA0S",
            "FwoObmV4dERyb3BJdGVtSWQYrQIgASgNEhQKC25leHRTa2lsbElkGK4CIAEo",
            "DRIcChNuZXh0SW52ZW50b3J5SXRlbUlkGK8CIAEoDRJBCg1kZWZlbnNlUGxh",
            "eWVyGJADIAEoCzIpLkNvbW1vbnMuVHlwZXMuUGxheWVycy5Cb2FyZFBsYXll",
            "ck1lc3NhZ2USQQoTZGVmZW5zZVBsYXllckF2YXRhchiRAyABKAsyIy5Db21t",
            "b25zLlR5cGVzLlBsYXllcnMuUGxheWVyQXZhdGFyEi4KCWNyZWF0ZWRBdBjQ",
            "DyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wGlkKDFBsYXllcnNF",
            "bnRyeRILCgNrZXkYASABKAMSOAoFdmFsdWUYAiABKAsyKS5Db21tb25zLlR5",
            "cGVzLlBsYXllcnMuQm9hcmRQbGF5ZXJNZXNzYWdlOgI4ARpkChFBY2hpZXZl",
            "bWVudHNFbnRyeRILCgNrZXkYASABKAUSPgoFdmFsdWUYAiABKAsyLy5Db21t",
            "b25zLlR5cGVzLlBsYXllcnMuUGxheWVyQWNoaWV2ZW1lbnRNZXNzYWdlOgI4",
            "ARo/Ch1EaXNhYmxlZFRlcnJhaW5UcmlhbmdsZXNFbnRyeRILCgNrZXkYASAB",
            "KAUSDQoFdmFsdWUYAiABKAg6AjgBGkQKClVuaXRzRW50cnkSCwoDa2V5GAEg",
            "ASgDEiUKBXZhbHVlGAIgASgLMhYuQ29tbW9ucy5HYW1lLkdhbWVVbml0OgI4",
            "ARpGCgtTa2lsbHNFbnRyeRILCgNrZXkYASABKAMSJgoFdmFsdWUYAiABKAsy",
            "Fy5Db21tb25zLkdhbWUuR2FtZVNraWxsOgI4ARpMCg5Ecm9wSXRlbXNFbnRy",
            "eRILCgNrZXkYASABKAMSKQoFdmFsdWUYAiABKAsyGi5Db21tb25zLkdhbWUu",
            "R2FtZURyb3BJdGVtOgI4ASKGAQoFU3RhdGUSCAoESWRsZRAAEhMKDldpbGxJ",
            "bml0aWFsaXplEOgHEhEKDEluaXRpYWxpemluZxDpBxIQCgtJbml0aWFsaXpl",
            "ZBDqBxINCghXaWxsUGxheRDQDxIMCgdQbGF5aW5nENEPEg8KCVdpbGxFbmRl",
            "ZBDAhD0SCwoFRW5kZWQQwYQ9IjoKD0Jsb2NrQWN0aW9uRmxhZxIICgROb25l",
            "EAASCQoFU2tpbGwQARIICgRNb3ZlEAISCAoESGVhbBAEYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Commons.Game.GameUnitReflection.Descriptor, global::Commons.Game.GameSkillReflection.Descriptor, global::Commons.Game.GameDropItemReflection.Descriptor, global::Commons.Resources.ResourceTriggerReflection.Descriptor, global::Commons.Types.Players.PlayerReflection.Descriptor, global::Commons.Types.Players.PlayerAchievementReflection.Descriptor, global::Commons.Types.Players.PlayerAvatarReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Game.GameBoard), global::Commons.Game.GameBoard.Parser, new[]{ "Players", "Achievements", "DisabledTerrainTriangles", "Units", "Skills", "DropItems", "Id", "DataId", "Tick", "Seed", "Variables", "TimerStartTick", "TimerPauseTick", "TimerEndTick", "WinningTeam", "State", "ActionBlockFlags", "NextUnitId", "NextDropItemId", "NextSkillId", "NextInventoryItemId", "DefensePlayer", "DefensePlayerAvatar", "CreatedAt" }, null, new[]{ typeof(global::Commons.Game.GameBoard.Types.State), typeof(global::Commons.Game.GameBoard.Types.BlockActionFlag) }, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameBoard : pb::IMessage<GameBoard>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameBoard> _parser = new pb::MessageParser<GameBoard>(() => new GameBoard());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameBoard> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Commons.Game.GameBoardReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameBoard() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameBoard(GameBoard other) : this() {
      players_ = other.players_.Clone();
      achievements_ = other.achievements_.Clone();
      disabledTerrainTriangles_ = other.disabledTerrainTriangles_.Clone();
      units_ = other.units_.Clone();
      skills_ = other.skills_.Clone();
      dropItems_ = other.dropItems_.Clone();
      id_ = other.id_;
      dataId_ = other.dataId_;
      tick_ = other.tick_;
      seed_ = other.seed_;
      variables_ = other.variables_ != null ? other.variables_.Clone() : null;
      timerStartTick_ = other.timerStartTick_;
      timerPauseTick_ = other.timerPauseTick_;
      timerEndTick_ = other.timerEndTick_;
      winningTeam_ = other.winningTeam_;
      state_ = other.state_;
      actionBlockFlags_ = other.actionBlockFlags_;
      nextUnitId_ = other.nextUnitId_;
      nextDropItemId_ = other.nextDropItemId_;
      nextSkillId_ = other.nextSkillId_;
      nextInventoryItemId_ = other.nextInventoryItemId_;
      defensePlayer_ = other.defensePlayer_ != null ? other.defensePlayer_.Clone() : null;
      defensePlayerAvatar_ = other.defensePlayerAvatar_ != null ? other.defensePlayerAvatar_.Clone() : null;
      createdAt_ = other.createdAt_ != null ? other.createdAt_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameBoard Clone() {
      return new GameBoard(this);
    }

    /// <summary>Field number for the "players" field.</summary>
    public const int PlayersFieldNumber = 1;
    private static readonly pbc::MapField<long, global::Commons.Types.Players.BoardPlayerMessage>.Codec _map_players_codec
        = new pbc::MapField<long, global::Commons.Types.Players.BoardPlayerMessage>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Commons.Types.Players.BoardPlayerMessage.Parser), 10);
    private readonly pbc::MapField<long, global::Commons.Types.Players.BoardPlayerMessage> players_ = new pbc::MapField<long, global::Commons.Types.Players.BoardPlayerMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Commons.Types.Players.BoardPlayerMessage> Players {
      get { return players_; }
    }

    /// <summary>Field number for the "achievements" field.</summary>
    public const int AchievementsFieldNumber = 2;
    private static readonly pbc::MapField<int, global::Commons.Types.Players.PlayerAchievementMessage>.Codec _map_achievements_codec
        = new pbc::MapField<int, global::Commons.Types.Players.PlayerAchievementMessage>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Commons.Types.Players.PlayerAchievementMessage.Parser), 18);
    private readonly pbc::MapField<int, global::Commons.Types.Players.PlayerAchievementMessage> achievements_ = new pbc::MapField<int, global::Commons.Types.Players.PlayerAchievementMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Commons.Types.Players.PlayerAchievementMessage> Achievements {
      get { return achievements_; }
    }

    /// <summary>Field number for the "disabledTerrainTriangles" field.</summary>
    public const int DisabledTerrainTrianglesFieldNumber = 3;
    private static readonly pbc::MapField<int, bool>.Codec _map_disabledTerrainTriangles_codec
        = new pbc::MapField<int, bool>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForBool(16, false), 26);
    private readonly pbc::MapField<int, bool> disabledTerrainTriangles_ = new pbc::MapField<int, bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, bool> DisabledTerrainTriangles {
      get { return disabledTerrainTriangles_; }
    }

    /// <summary>Field number for the "units" field.</summary>
    public const int UnitsFieldNumber = 4;
    private static readonly pbc::MapField<long, global::Commons.Game.GameUnit>.Codec _map_units_codec
        = new pbc::MapField<long, global::Commons.Game.GameUnit>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Commons.Game.GameUnit.Parser), 34);
    private readonly pbc::MapField<long, global::Commons.Game.GameUnit> units_ = new pbc::MapField<long, global::Commons.Game.GameUnit>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Commons.Game.GameUnit> Units {
      get { return units_; }
    }

    /// <summary>Field number for the "skills" field.</summary>
    public const int SkillsFieldNumber = 5;
    private static readonly pbc::MapField<long, global::Commons.Game.GameSkill>.Codec _map_skills_codec
        = new pbc::MapField<long, global::Commons.Game.GameSkill>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Commons.Game.GameSkill.Parser), 42);
    private readonly pbc::MapField<long, global::Commons.Game.GameSkill> skills_ = new pbc::MapField<long, global::Commons.Game.GameSkill>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Commons.Game.GameSkill> Skills {
      get { return skills_; }
    }

    /// <summary>Field number for the "dropItems" field.</summary>
    public const int DropItemsFieldNumber = 6;
    private static readonly pbc::MapField<long, global::Commons.Game.GameDropItem>.Codec _map_dropItems_codec
        = new pbc::MapField<long, global::Commons.Game.GameDropItem>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Commons.Game.GameDropItem.Parser), 50);
    private readonly pbc::MapField<long, global::Commons.Game.GameDropItem> dropItems_ = new pbc::MapField<long, global::Commons.Game.GameDropItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Commons.Game.GameDropItem> DropItems {
      get { return dropItems_; }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 100;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "dataId" field.</summary>
    public const int DataIdFieldNumber = 101;
    private int dataId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DataId {
      get { return dataId_; }
      set {
        dataId_ = value;
      }
    }

    /// <summary>Field number for the "tick" field.</summary>
    public const int TickFieldNumber = 200;
    private uint tick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Tick {
      get { return tick_; }
      set {
        tick_ = value;
      }
    }

    /// <summary>Field number for the "seed" field.</summary>
    public const int SeedFieldNumber = 201;
    private uint seed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Seed {
      get { return seed_; }
      set {
        seed_ = value;
      }
    }

    /// <summary>Field number for the "variables" field.</summary>
    public const int VariablesFieldNumber = 202;
    private global::Commons.Resources.ResourceTrigger.Types.Variables variables_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Resources.ResourceTrigger.Types.Variables Variables {
      get { return variables_; }
      set {
        variables_ = value;
      }
    }

    /// <summary>Field number for the "timerStartTick" field.</summary>
    public const int TimerStartTickFieldNumber = 203;
    private uint timerStartTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TimerStartTick {
      get { return timerStartTick_; }
      set {
        timerStartTick_ = value;
      }
    }

    /// <summary>Field number for the "timerPauseTick" field.</summary>
    public const int TimerPauseTickFieldNumber = 204;
    private uint timerPauseTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TimerPauseTick {
      get { return timerPauseTick_; }
      set {
        timerPauseTick_ = value;
      }
    }

    /// <summary>Field number for the "timerEndTick" field.</summary>
    public const int TimerEndTickFieldNumber = 205;
    private uint timerEndTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TimerEndTick {
      get { return timerEndTick_; }
      set {
        timerEndTick_ = value;
      }
    }

    /// <summary>Field number for the "winningTeam" field.</summary>
    public const int WinningTeamFieldNumber = 206;
    private int winningTeam_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int WinningTeam {
      get { return winningTeam_; }
      set {
        winningTeam_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 207;
    private global::Commons.Game.GameBoard.Types.State state_ = global::Commons.Game.GameBoard.Types.State.Idle;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Game.GameBoard.Types.State State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "actionBlockFlags" field.</summary>
    public const int ActionBlockFlagsFieldNumber = 208;
    private ulong actionBlockFlags_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ActionBlockFlags {
      get { return actionBlockFlags_; }
      set {
        actionBlockFlags_ = value;
      }
    }

    /// <summary>Field number for the "nextUnitId" field.</summary>
    public const int NextUnitIdFieldNumber = 300;
    private uint nextUnitId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NextUnitId {
      get { return nextUnitId_; }
      set {
        nextUnitId_ = value;
      }
    }

    /// <summary>Field number for the "nextDropItemId" field.</summary>
    public const int NextDropItemIdFieldNumber = 301;
    private uint nextDropItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NextDropItemId {
      get { return nextDropItemId_; }
      set {
        nextDropItemId_ = value;
      }
    }

    /// <summary>Field number for the "nextSkillId" field.</summary>
    public const int NextSkillIdFieldNumber = 302;
    private uint nextSkillId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NextSkillId {
      get { return nextSkillId_; }
      set {
        nextSkillId_ = value;
      }
    }

    /// <summary>Field number for the "nextInventoryItemId" field.</summary>
    public const int NextInventoryItemIdFieldNumber = 303;
    private uint nextInventoryItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NextInventoryItemId {
      get { return nextInventoryItemId_; }
      set {
        nextInventoryItemId_ = value;
      }
    }

    /// <summary>Field number for the "defensePlayer" field.</summary>
    public const int DefensePlayerFieldNumber = 400;
    private global::Commons.Types.Players.BoardPlayerMessage defensePlayer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Players.BoardPlayerMessage DefensePlayer {
      get { return defensePlayer_; }
      set {
        defensePlayer_ = value;
      }
    }

    /// <summary>Field number for the "defensePlayerAvatar" field.</summary>
    public const int DefensePlayerAvatarFieldNumber = 401;
    private global::Commons.Types.Players.PlayerAvatar defensePlayerAvatar_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Players.PlayerAvatar DefensePlayerAvatar {
      get { return defensePlayerAvatar_; }
      set {
        defensePlayerAvatar_ = value;
      }
    }

    /// <summary>Field number for the "createdAt" field.</summary>
    public const int CreatedAtFieldNumber = 2000;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createdAt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameBoard);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameBoard other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Players.Equals(other.Players)) return false;
      if (!Achievements.Equals(other.Achievements)) return false;
      if (!DisabledTerrainTriangles.Equals(other.DisabledTerrainTriangles)) return false;
      if (!Units.Equals(other.Units)) return false;
      if (!Skills.Equals(other.Skills)) return false;
      if (!DropItems.Equals(other.DropItems)) return false;
      if (Id != other.Id) return false;
      if (DataId != other.DataId) return false;
      if (Tick != other.Tick) return false;
      if (Seed != other.Seed) return false;
      if (!object.Equals(Variables, other.Variables)) return false;
      if (TimerStartTick != other.TimerStartTick) return false;
      if (TimerPauseTick != other.TimerPauseTick) return false;
      if (TimerEndTick != other.TimerEndTick) return false;
      if (WinningTeam != other.WinningTeam) return false;
      if (State != other.State) return false;
      if (ActionBlockFlags != other.ActionBlockFlags) return false;
      if (NextUnitId != other.NextUnitId) return false;
      if (NextDropItemId != other.NextDropItemId) return false;
      if (NextSkillId != other.NextSkillId) return false;
      if (NextInventoryItemId != other.NextInventoryItemId) return false;
      if (!object.Equals(DefensePlayer, other.DefensePlayer)) return false;
      if (!object.Equals(DefensePlayerAvatar, other.DefensePlayerAvatar)) return false;
      if (!object.Equals(CreatedAt, other.CreatedAt)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Players.GetHashCode();
      hash ^= Achievements.GetHashCode();
      hash ^= DisabledTerrainTriangles.GetHashCode();
      hash ^= Units.GetHashCode();
      hash ^= Skills.GetHashCode();
      hash ^= DropItems.GetHashCode();
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (DataId != 0) hash ^= DataId.GetHashCode();
      if (Tick != 0) hash ^= Tick.GetHashCode();
      if (Seed != 0) hash ^= Seed.GetHashCode();
      if (variables_ != null) hash ^= Variables.GetHashCode();
      if (TimerStartTick != 0) hash ^= TimerStartTick.GetHashCode();
      if (TimerPauseTick != 0) hash ^= TimerPauseTick.GetHashCode();
      if (TimerEndTick != 0) hash ^= TimerEndTick.GetHashCode();
      if (WinningTeam != 0) hash ^= WinningTeam.GetHashCode();
      if (State != global::Commons.Game.GameBoard.Types.State.Idle) hash ^= State.GetHashCode();
      if (ActionBlockFlags != 0UL) hash ^= ActionBlockFlags.GetHashCode();
      if (NextUnitId != 0) hash ^= NextUnitId.GetHashCode();
      if (NextDropItemId != 0) hash ^= NextDropItemId.GetHashCode();
      if (NextSkillId != 0) hash ^= NextSkillId.GetHashCode();
      if (NextInventoryItemId != 0) hash ^= NextInventoryItemId.GetHashCode();
      if (defensePlayer_ != null) hash ^= DefensePlayer.GetHashCode();
      if (defensePlayerAvatar_ != null) hash ^= DefensePlayerAvatar.GetHashCode();
      if (createdAt_ != null) hash ^= CreatedAt.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      players_.WriteTo(output, _map_players_codec);
      achievements_.WriteTo(output, _map_achievements_codec);
      disabledTerrainTriangles_.WriteTo(output, _map_disabledTerrainTriangles_codec);
      units_.WriteTo(output, _map_units_codec);
      skills_.WriteTo(output, _map_skills_codec);
      dropItems_.WriteTo(output, _map_dropItems_codec);
      if (Id != 0L) {
        output.WriteRawTag(160, 6);
        output.WriteInt64(Id);
      }
      if (DataId != 0) {
        output.WriteRawTag(168, 6);
        output.WriteInt32(DataId);
      }
      if (Tick != 0) {
        output.WriteRawTag(192, 12);
        output.WriteUInt32(Tick);
      }
      if (Seed != 0) {
        output.WriteRawTag(200, 12);
        output.WriteUInt32(Seed);
      }
      if (variables_ != null) {
        output.WriteRawTag(210, 12);
        output.WriteMessage(Variables);
      }
      if (TimerStartTick != 0) {
        output.WriteRawTag(216, 12);
        output.WriteUInt32(TimerStartTick);
      }
      if (TimerPauseTick != 0) {
        output.WriteRawTag(224, 12);
        output.WriteUInt32(TimerPauseTick);
      }
      if (TimerEndTick != 0) {
        output.WriteRawTag(232, 12);
        output.WriteUInt32(TimerEndTick);
      }
      if (WinningTeam != 0) {
        output.WriteRawTag(240, 12);
        output.WriteInt32(WinningTeam);
      }
      if (State != global::Commons.Game.GameBoard.Types.State.Idle) {
        output.WriteRawTag(248, 12);
        output.WriteEnum((int) State);
      }
      if (ActionBlockFlags != 0UL) {
        output.WriteRawTag(128, 13);
        output.WriteUInt64(ActionBlockFlags);
      }
      if (NextUnitId != 0) {
        output.WriteRawTag(224, 18);
        output.WriteUInt32(NextUnitId);
      }
      if (NextDropItemId != 0) {
        output.WriteRawTag(232, 18);
        output.WriteUInt32(NextDropItemId);
      }
      if (NextSkillId != 0) {
        output.WriteRawTag(240, 18);
        output.WriteUInt32(NextSkillId);
      }
      if (NextInventoryItemId != 0) {
        output.WriteRawTag(248, 18);
        output.WriteUInt32(NextInventoryItemId);
      }
      if (defensePlayer_ != null) {
        output.WriteRawTag(130, 25);
        output.WriteMessage(DefensePlayer);
      }
      if (defensePlayerAvatar_ != null) {
        output.WriteRawTag(138, 25);
        output.WriteMessage(DefensePlayerAvatar);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(130, 125);
        output.WriteMessage(CreatedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      players_.WriteTo(ref output, _map_players_codec);
      achievements_.WriteTo(ref output, _map_achievements_codec);
      disabledTerrainTriangles_.WriteTo(ref output, _map_disabledTerrainTriangles_codec);
      units_.WriteTo(ref output, _map_units_codec);
      skills_.WriteTo(ref output, _map_skills_codec);
      dropItems_.WriteTo(ref output, _map_dropItems_codec);
      if (Id != 0L) {
        output.WriteRawTag(160, 6);
        output.WriteInt64(Id);
      }
      if (DataId != 0) {
        output.WriteRawTag(168, 6);
        output.WriteInt32(DataId);
      }
      if (Tick != 0) {
        output.WriteRawTag(192, 12);
        output.WriteUInt32(Tick);
      }
      if (Seed != 0) {
        output.WriteRawTag(200, 12);
        output.WriteUInt32(Seed);
      }
      if (variables_ != null) {
        output.WriteRawTag(210, 12);
        output.WriteMessage(Variables);
      }
      if (TimerStartTick != 0) {
        output.WriteRawTag(216, 12);
        output.WriteUInt32(TimerStartTick);
      }
      if (TimerPauseTick != 0) {
        output.WriteRawTag(224, 12);
        output.WriteUInt32(TimerPauseTick);
      }
      if (TimerEndTick != 0) {
        output.WriteRawTag(232, 12);
        output.WriteUInt32(TimerEndTick);
      }
      if (WinningTeam != 0) {
        output.WriteRawTag(240, 12);
        output.WriteInt32(WinningTeam);
      }
      if (State != global::Commons.Game.GameBoard.Types.State.Idle) {
        output.WriteRawTag(248, 12);
        output.WriteEnum((int) State);
      }
      if (ActionBlockFlags != 0UL) {
        output.WriteRawTag(128, 13);
        output.WriteUInt64(ActionBlockFlags);
      }
      if (NextUnitId != 0) {
        output.WriteRawTag(224, 18);
        output.WriteUInt32(NextUnitId);
      }
      if (NextDropItemId != 0) {
        output.WriteRawTag(232, 18);
        output.WriteUInt32(NextDropItemId);
      }
      if (NextSkillId != 0) {
        output.WriteRawTag(240, 18);
        output.WriteUInt32(NextSkillId);
      }
      if (NextInventoryItemId != 0) {
        output.WriteRawTag(248, 18);
        output.WriteUInt32(NextInventoryItemId);
      }
      if (defensePlayer_ != null) {
        output.WriteRawTag(130, 25);
        output.WriteMessage(DefensePlayer);
      }
      if (defensePlayerAvatar_ != null) {
        output.WriteRawTag(138, 25);
        output.WriteMessage(DefensePlayerAvatar);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(130, 125);
        output.WriteMessage(CreatedAt);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += players_.CalculateSize(_map_players_codec);
      size += achievements_.CalculateSize(_map_achievements_codec);
      size += disabledTerrainTriangles_.CalculateSize(_map_disabledTerrainTriangles_codec);
      size += units_.CalculateSize(_map_units_codec);
      size += skills_.CalculateSize(_map_skills_codec);
      size += dropItems_.CalculateSize(_map_dropItems_codec);
      if (Id != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (DataId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(DataId);
      }
      if (Tick != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Tick);
      }
      if (Seed != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Seed);
      }
      if (variables_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Variables);
      }
      if (TimerStartTick != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(TimerStartTick);
      }
      if (TimerPauseTick != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(TimerPauseTick);
      }
      if (TimerEndTick != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(TimerEndTick);
      }
      if (WinningTeam != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(WinningTeam);
      }
      if (State != global::Commons.Game.GameBoard.Types.State.Idle) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (ActionBlockFlags != 0UL) {
        size += 2 + pb::CodedOutputStream.ComputeUInt64Size(ActionBlockFlags);
      }
      if (NextUnitId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(NextUnitId);
      }
      if (NextDropItemId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(NextDropItemId);
      }
      if (NextSkillId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(NextSkillId);
      }
      if (NextInventoryItemId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(NextInventoryItemId);
      }
      if (defensePlayer_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(DefensePlayer);
      }
      if (defensePlayerAvatar_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(DefensePlayerAvatar);
      }
      if (createdAt_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(CreatedAt);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameBoard other) {
      if (other == null) {
        return;
      }
      players_.MergeFrom(other.players_);
      achievements_.MergeFrom(other.achievements_);
      disabledTerrainTriangles_.MergeFrom(other.disabledTerrainTriangles_);
      units_.MergeFrom(other.units_);
      skills_.MergeFrom(other.skills_);
      dropItems_.MergeFrom(other.dropItems_);
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.DataId != 0) {
        DataId = other.DataId;
      }
      if (other.Tick != 0) {
        Tick = other.Tick;
      }
      if (other.Seed != 0) {
        Seed = other.Seed;
      }
      if (other.variables_ != null) {
        if (variables_ == null) {
          Variables = new global::Commons.Resources.ResourceTrigger.Types.Variables();
        }
        Variables.MergeFrom(other.Variables);
      }
      if (other.TimerStartTick != 0) {
        TimerStartTick = other.TimerStartTick;
      }
      if (other.TimerPauseTick != 0) {
        TimerPauseTick = other.TimerPauseTick;
      }
      if (other.TimerEndTick != 0) {
        TimerEndTick = other.TimerEndTick;
      }
      if (other.WinningTeam != 0) {
        WinningTeam = other.WinningTeam;
      }
      if (other.State != global::Commons.Game.GameBoard.Types.State.Idle) {
        State = other.State;
      }
      if (other.ActionBlockFlags != 0UL) {
        ActionBlockFlags = other.ActionBlockFlags;
      }
      if (other.NextUnitId != 0) {
        NextUnitId = other.NextUnitId;
      }
      if (other.NextDropItemId != 0) {
        NextDropItemId = other.NextDropItemId;
      }
      if (other.NextSkillId != 0) {
        NextSkillId = other.NextSkillId;
      }
      if (other.NextInventoryItemId != 0) {
        NextInventoryItemId = other.NextInventoryItemId;
      }
      if (other.defensePlayer_ != null) {
        if (defensePlayer_ == null) {
          DefensePlayer = new global::Commons.Types.Players.BoardPlayerMessage();
        }
        DefensePlayer.MergeFrom(other.DefensePlayer);
      }
      if (other.defensePlayerAvatar_ != null) {
        if (defensePlayerAvatar_ == null) {
          DefensePlayerAvatar = new global::Commons.Types.Players.PlayerAvatar();
        }
        DefensePlayerAvatar.MergeFrom(other.DefensePlayerAvatar);
      }
      if (other.createdAt_ != null) {
        if (createdAt_ == null) {
          CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreatedAt.MergeFrom(other.CreatedAt);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            players_.AddEntriesFrom(input, _map_players_codec);
            break;
          }
          case 18: {
            achievements_.AddEntriesFrom(input, _map_achievements_codec);
            break;
          }
          case 26: {
            disabledTerrainTriangles_.AddEntriesFrom(input, _map_disabledTerrainTriangles_codec);
            break;
          }
          case 34: {
            units_.AddEntriesFrom(input, _map_units_codec);
            break;
          }
          case 42: {
            skills_.AddEntriesFrom(input, _map_skills_codec);
            break;
          }
          case 50: {
            dropItems_.AddEntriesFrom(input, _map_dropItems_codec);
            break;
          }
          case 800: {
            Id = input.ReadInt64();
            break;
          }
          case 808: {
            DataId = input.ReadInt32();
            break;
          }
          case 1600: {
            Tick = input.ReadUInt32();
            break;
          }
          case 1608: {
            Seed = input.ReadUInt32();
            break;
          }
          case 1618: {
            if (variables_ == null) {
              Variables = new global::Commons.Resources.ResourceTrigger.Types.Variables();
            }
            input.ReadMessage(Variables);
            break;
          }
          case 1624: {
            TimerStartTick = input.ReadUInt32();
            break;
          }
          case 1632: {
            TimerPauseTick = input.ReadUInt32();
            break;
          }
          case 1640: {
            TimerEndTick = input.ReadUInt32();
            break;
          }
          case 1648: {
            WinningTeam = input.ReadInt32();
            break;
          }
          case 1656: {
            State = (global::Commons.Game.GameBoard.Types.State) input.ReadEnum();
            break;
          }
          case 1664: {
            ActionBlockFlags = input.ReadUInt64();
            break;
          }
          case 2400: {
            NextUnitId = input.ReadUInt32();
            break;
          }
          case 2408: {
            NextDropItemId = input.ReadUInt32();
            break;
          }
          case 2416: {
            NextSkillId = input.ReadUInt32();
            break;
          }
          case 2424: {
            NextInventoryItemId = input.ReadUInt32();
            break;
          }
          case 3202: {
            if (defensePlayer_ == null) {
              DefensePlayer = new global::Commons.Types.Players.BoardPlayerMessage();
            }
            input.ReadMessage(DefensePlayer);
            break;
          }
          case 3210: {
            if (defensePlayerAvatar_ == null) {
              DefensePlayerAvatar = new global::Commons.Types.Players.PlayerAvatar();
            }
            input.ReadMessage(DefensePlayerAvatar);
            break;
          }
          case 16002: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            players_.AddEntriesFrom(ref input, _map_players_codec);
            break;
          }
          case 18: {
            achievements_.AddEntriesFrom(ref input, _map_achievements_codec);
            break;
          }
          case 26: {
            disabledTerrainTriangles_.AddEntriesFrom(ref input, _map_disabledTerrainTriangles_codec);
            break;
          }
          case 34: {
            units_.AddEntriesFrom(ref input, _map_units_codec);
            break;
          }
          case 42: {
            skills_.AddEntriesFrom(ref input, _map_skills_codec);
            break;
          }
          case 50: {
            dropItems_.AddEntriesFrom(ref input, _map_dropItems_codec);
            break;
          }
          case 800: {
            Id = input.ReadInt64();
            break;
          }
          case 808: {
            DataId = input.ReadInt32();
            break;
          }
          case 1600: {
            Tick = input.ReadUInt32();
            break;
          }
          case 1608: {
            Seed = input.ReadUInt32();
            break;
          }
          case 1618: {
            if (variables_ == null) {
              Variables = new global::Commons.Resources.ResourceTrigger.Types.Variables();
            }
            input.ReadMessage(Variables);
            break;
          }
          case 1624: {
            TimerStartTick = input.ReadUInt32();
            break;
          }
          case 1632: {
            TimerPauseTick = input.ReadUInt32();
            break;
          }
          case 1640: {
            TimerEndTick = input.ReadUInt32();
            break;
          }
          case 1648: {
            WinningTeam = input.ReadInt32();
            break;
          }
          case 1656: {
            State = (global::Commons.Game.GameBoard.Types.State) input.ReadEnum();
            break;
          }
          case 1664: {
            ActionBlockFlags = input.ReadUInt64();
            break;
          }
          case 2400: {
            NextUnitId = input.ReadUInt32();
            break;
          }
          case 2408: {
            NextDropItemId = input.ReadUInt32();
            break;
          }
          case 2416: {
            NextSkillId = input.ReadUInt32();
            break;
          }
          case 2424: {
            NextInventoryItemId = input.ReadUInt32();
            break;
          }
          case 3202: {
            if (defensePlayer_ == null) {
              DefensePlayer = new global::Commons.Types.Players.BoardPlayerMessage();
            }
            input.ReadMessage(DefensePlayer);
            break;
          }
          case 3210: {
            if (defensePlayerAvatar_ == null) {
              DefensePlayerAvatar = new global::Commons.Types.Players.PlayerAvatar();
            }
            input.ReadMessage(DefensePlayerAvatar);
            break;
          }
          case 16002: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the GameBoard message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum State {
        [pbr::OriginalName("Idle")] Idle = 0,
        [pbr::OriginalName("WillInitialize")] WillInitialize = 1000,
        [pbr::OriginalName("Initializing")] Initializing = 1001,
        [pbr::OriginalName("Initialized")] Initialized = 1002,
        [pbr::OriginalName("WillPlay")] WillPlay = 2000,
        [pbr::OriginalName("Playing")] Playing = 2001,
        [pbr::OriginalName("WillEnded")] WillEnded = 1000000,
        [pbr::OriginalName("Ended")] Ended = 1000001,
      }

      public enum BlockActionFlag {
        [pbr::OriginalName("None")] None = 0,
        [pbr::OriginalName("Skill")] Skill = 1,
        [pbr::OriginalName("Move")] Move = 2,
        [pbr::OriginalName("Heal")] Heal = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
