// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameUnit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Commons.Game {

  /// <summary>Holder for reflection information generated from GameUnit.proto</summary>
  public static partial class GameUnitReflection {

    #region Descriptor
    /// <summary>File descriptor for GameUnit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameUnitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5HYW1lVW5pdC5wcm90bxIMQ29tbW9ucy5HYW1lGhJQbGF5ZXJBdmF0YXIu",
            "cHJvdG8aFUdlb21ldHJ5TWVzc2FnZS5wcm90bxoOR2FtZUJ1ZmYucHJvdG8a",
            "ElJlc291cmNlVW5pdC5wcm90bxoVUmVzb3VyY2VUcmlnZ2VyLnByb3RvIpsP",
            "CghHYW1lVW5pdBI0CgRwYXRoGAEgAygLMiYuQ29tbW9ucy5UeXBlcy5HZW9t",
            "ZXRyeS5WZWN0b3IyTWVzc2FnZRI4Cgljb29sZG93bnMYAiADKAsyJS5Db21t",
            "b25zLkdhbWUuR2FtZVVuaXQuQ29vbGRvd25zRW50cnkSEAoIYmFzZVN0YXQY",
            "AyADKAISMAoFYnVmZnMYBCADKAsyIS5Db21tb25zLkdhbWUuR2FtZVVuaXQu",
            "QnVmZnNFbnRyeRJACg1pdGVtQ29vbGRvd25zGAUgAygLMikuQ29tbW9ucy5H",
            "YW1lLkdhbWVVbml0Lkl0ZW1Db29sZG93bnNFbnRyeRJIChF2YXJpYWJsZXNC",
            "eUl0ZW1JZBgGIAMoCzItLkNvbW1vbnMuR2FtZS5HYW1lVW5pdC5WYXJpYWJs",
            "ZXNCeUl0ZW1JZEVudHJ5EhkKEWVxdWlwU2tpbGxEYXRhSWRzGAcgAygFEgoK",
            "AmlkGGQgASgDEg4KBmRhdGFJZBhlIAEoBRIOCgZvZmZzZXQYZiABKAUSPAoM",
            "aW5pdFBvc2l0aW9uGGcgASgLMiYuQ29tbW9ucy5UeXBlcy5HZW9tZXRyeS5W",
            "ZWN0b3IyTWVzc2FnZRITCgtvd25lclVuaXRJZBhoIAEoAxIRCghwbGF5ZXJJ",
            "ZBjIASABKAMSOgoMcGxheWVyQXZhdGFyGMkBIAEoCzIjLkNvbW1vbnMuVHlw",
            "ZXMuUGxheWVycy5QbGF5ZXJBdmF0YXISHwoWcGxheWVyQXZhdGFyV2VhcG9u",
            "U2xvdBjKASABKAUSDQoEdGVhbRisAiABKAUSDgoFbGV2ZWwYrQIgASgFEgwK",
            "A2V4cBiuAiABKAMSDQoEdGljaxiQAyABKA0SEwoKdGlja09mZnNldBiRAyAB",
            "KA0SQAoJdmFyaWFibGVzGJIDIAEoCzIsLkNvbW1vbnMuUmVzb3VyY2VzLlJl",
            "c291cmNlVHJpZ2dlci5WYXJpYWJsZXMSEwoKbmV4dEJ1ZmZJZBiTAyABKA0S",
            "OQoIcG9zaXRpb24YlAMgASgLMiYuQ29tbW9ucy5UeXBlcy5HZW9tZXRyeS5W",
            "ZWN0b3IyTWVzc2FnZRI6CglkaXJlY3Rpb24YlQMgASgLMiYuQ29tbW9ucy5U",
            "eXBlcy5HZW9tZXRyeS5WZWN0b3IyTWVzc2FnZRI5Cgh2ZWxvY2l0eRiWAyAB",
            "KAsyJi5Db21tb25zLlR5cGVzLkdlb21ldHJ5LlZlY3RvcjJNZXNzYWdlEj4K",
            "DW1vdmVEaXJlY3Rpb24YlwMgASgLMiYuQ29tbW9ucy5UeXBlcy5HZW9tZXRy",
            "eS5WZWN0b3IyTWVzc2FnZRJACg9tb3ZlRGVzdGluYXRpb24YmAMgASgLMiYu",
            "Q29tbW9ucy5UeXBlcy5HZW9tZXRyeS5WZWN0b3IyTWVzc2FnZRI/Cgp0YXJn",
            "ZXRNb2RlGJkDIAEoDjIqLkNvbW1vbnMuUmVzb3VyY2VzLlJlc291cmNlVW5p",
            "dC5UYXJnZXRNb2RlEhwKE3RhcmdldEF3YXJlRGlzdGFuY2UYmgMgASgCEhwK",
            "E3RhcmdldFJlc2V0RGlzdGFuY2UYmwMgASgCEhUKDHRhcmdldFVuaXRJZBic",
            "AyABKAMSPwoOcG9zaXRpb25PZmZzZXQYnQMgASgLMiYuQ29tbW9ucy5UeXBl",
            "cy5HZW9tZXRyeS5WZWN0b3IyTWVzc2FnZRJDChJrbm9ja2JhY2tEaXJlY3Rp",
            "b24Y9AMgASgLMiYuQ29tbW9ucy5UeXBlcy5HZW9tZXRyeS5WZWN0b3IyTWVz",
            "c2FnZRIWCg1rbm9ja2JhY2tUaWNrGPUDIAEoDRIXCg5rbm9ja2JhY2tTcGVl",
            "ZBj2AyABKAISDgoFc3RhdGUY2AQgASgNEhkKEG1vdmVEaXNhYmxlZFRpY2sY",
            "2QQgASgNEhsKEmFjdGlvbkRpc2FibGVkVGljaxjaBCABKA0SHwoWYWN0aW9u",
            "RGlzYWJsZWRQcmlvcml0eRjbBCABKAUSFAoLZGVzdHJveVRpY2sY3AQgASgN",
            "EhQKC3Jlc3Bhd25UaWNrGN0EIAEoDRIVCgxub0RhbWFnZVRpY2sY3gQgASgN",
            "EgsKAmhwGLwFIAEoAxILCgJtcBi9BSABKAMSDwoGc2hpZWxkGL4FIAEoAxIL",
            "CgJzcBi/BSABKAMSFAoLc3BSZWdlblRpY2sYwAUgASgNEg4KBWd1YXJkGMEF",
            "IAEoAxowCg5Db29sZG93bnNFbnRyeRILCgNrZXkYASABKAUSDQoFdmFsdWUY",
            "AiABKA06AjgBGkQKCkJ1ZmZzRW50cnkSCwoDa2V5GAEgASgDEiUKBXZhbHVl",
            "GAIgASgLMhYuQ29tbW9ucy5HYW1lLkdhbWVCdWZmOgI4ARo0ChJJdGVtQ29v",
            "bGRvd25zRW50cnkSCwoDa2V5GAEgASgDEg0KBXZhbHVlGAIgASgNOgI4ARpm",
            "ChZWYXJpYWJsZXNCeUl0ZW1JZEVudHJ5EgsKA2tleRgBIAEoAxI7CgV2YWx1",
            "ZRgCIAEoCzIsLkNvbW1vbnMuUmVzb3VyY2VzLlJlc291cmNlVHJpZ2dlci5W",
            "YXJpYWJsZXM6AjgBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Commons.Types.Players.PlayerAvatarReflection.Descriptor, global::Commons.Types.Geometry.GeometryMessageReflection.Descriptor, global::Commons.Game.GameBuffReflection.Descriptor, global::Commons.Resources.ResourceUnitReflection.Descriptor, global::Commons.Resources.ResourceTriggerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Commons.Game.GameUnit), global::Commons.Game.GameUnit.Parser, new[]{ "Path", "Cooldowns", "BaseStat", "Buffs", "ItemCooldowns", "VariablesByItemId", "EquipSkillDataIds", "Id", "DataId", "Offset", "InitPosition", "OwnerUnitId", "PlayerId", "PlayerAvatar", "PlayerAvatarWeaponSlot", "Team", "Level", "Exp", "Tick", "TickOffset", "Variables", "NextBuffId", "Position", "Direction", "Velocity", "MoveDirection", "MoveDestination", "TargetMode", "TargetAwareDistance", "TargetResetDistance", "TargetUnitId", "PositionOffset", "KnockbackDirection", "KnockbackTick", "KnockbackSpeed", "State", "MoveDisabledTick", "ActionDisabledTick", "ActionDisabledPriority", "DestroyTick", "RespawnTick", "NoDamageTick", "Hp", "Mp", "Shield", "Sp", "SpRegenTick", "Guard" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameUnit : pb::IMessage<GameUnit>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameUnit> _parser = new pb::MessageParser<GameUnit>(() => new GameUnit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameUnit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Commons.Game.GameUnitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameUnit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameUnit(GameUnit other) : this() {
      path_ = other.path_.Clone();
      cooldowns_ = other.cooldowns_.Clone();
      baseStat_ = other.baseStat_.Clone();
      buffs_ = other.buffs_.Clone();
      itemCooldowns_ = other.itemCooldowns_.Clone();
      variablesByItemId_ = other.variablesByItemId_.Clone();
      equipSkillDataIds_ = other.equipSkillDataIds_.Clone();
      id_ = other.id_;
      dataId_ = other.dataId_;
      offset_ = other.offset_;
      initPosition_ = other.initPosition_ != null ? other.initPosition_.Clone() : null;
      ownerUnitId_ = other.ownerUnitId_;
      playerId_ = other.playerId_;
      playerAvatar_ = other.playerAvatar_ != null ? other.playerAvatar_.Clone() : null;
      playerAvatarWeaponSlot_ = other.playerAvatarWeaponSlot_;
      team_ = other.team_;
      level_ = other.level_;
      exp_ = other.exp_;
      tick_ = other.tick_;
      tickOffset_ = other.tickOffset_;
      variables_ = other.variables_ != null ? other.variables_.Clone() : null;
      nextBuffId_ = other.nextBuffId_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      direction_ = other.direction_ != null ? other.direction_.Clone() : null;
      velocity_ = other.velocity_ != null ? other.velocity_.Clone() : null;
      moveDirection_ = other.moveDirection_ != null ? other.moveDirection_.Clone() : null;
      moveDestination_ = other.moveDestination_ != null ? other.moveDestination_.Clone() : null;
      targetMode_ = other.targetMode_;
      targetAwareDistance_ = other.targetAwareDistance_;
      targetResetDistance_ = other.targetResetDistance_;
      targetUnitId_ = other.targetUnitId_;
      positionOffset_ = other.positionOffset_ != null ? other.positionOffset_.Clone() : null;
      knockbackDirection_ = other.knockbackDirection_ != null ? other.knockbackDirection_.Clone() : null;
      knockbackTick_ = other.knockbackTick_;
      knockbackSpeed_ = other.knockbackSpeed_;
      state_ = other.state_;
      moveDisabledTick_ = other.moveDisabledTick_;
      actionDisabledTick_ = other.actionDisabledTick_;
      actionDisabledPriority_ = other.actionDisabledPriority_;
      destroyTick_ = other.destroyTick_;
      respawnTick_ = other.respawnTick_;
      noDamageTick_ = other.noDamageTick_;
      hp_ = other.hp_;
      mp_ = other.mp_;
      shield_ = other.shield_;
      sp_ = other.sp_;
      spRegenTick_ = other.spRegenTick_;
      guard_ = other.guard_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameUnit Clone() {
      return new GameUnit(this);
    }

    /// <summary>Field number for the "path" field.</summary>
    public const int PathFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Commons.Types.Geometry.Vector2Message> _repeated_path_codec
        = pb::FieldCodec.ForMessage(10, global::Commons.Types.Geometry.Vector2Message.Parser);
    private readonly pbc::RepeatedField<global::Commons.Types.Geometry.Vector2Message> path_ = new pbc::RepeatedField<global::Commons.Types.Geometry.Vector2Message>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Commons.Types.Geometry.Vector2Message> Path {
      get { return path_; }
    }

    /// <summary>Field number for the "cooldowns" field.</summary>
    public const int CooldownsFieldNumber = 2;
    private static readonly pbc::MapField<int, uint>.Codec _map_cooldowns_codec
        = new pbc::MapField<int, uint>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForUInt32(16, 0), 18);
    private readonly pbc::MapField<int, uint> cooldowns_ = new pbc::MapField<int, uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, uint> Cooldowns {
      get { return cooldowns_; }
    }

    /// <summary>Field number for the "baseStat" field.</summary>
    public const int BaseStatFieldNumber = 3;
    private static readonly pb::FieldCodec<float> _repeated_baseStat_codec
        = pb::FieldCodec.ForFloat(26);
    private readonly pbc::RepeatedField<float> baseStat_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> BaseStat {
      get { return baseStat_; }
    }

    /// <summary>Field number for the "buffs" field.</summary>
    public const int BuffsFieldNumber = 4;
    private static readonly pbc::MapField<long, global::Commons.Game.GameBuff>.Codec _map_buffs_codec
        = new pbc::MapField<long, global::Commons.Game.GameBuff>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Commons.Game.GameBuff.Parser), 34);
    private readonly pbc::MapField<long, global::Commons.Game.GameBuff> buffs_ = new pbc::MapField<long, global::Commons.Game.GameBuff>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Commons.Game.GameBuff> Buffs {
      get { return buffs_; }
    }

    /// <summary>Field number for the "itemCooldowns" field.</summary>
    public const int ItemCooldownsFieldNumber = 5;
    private static readonly pbc::MapField<long, uint>.Codec _map_itemCooldowns_codec
        = new pbc::MapField<long, uint>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForUInt32(16, 0), 42);
    private readonly pbc::MapField<long, uint> itemCooldowns_ = new pbc::MapField<long, uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, uint> ItemCooldowns {
      get { return itemCooldowns_; }
    }

    /// <summary>Field number for the "variablesByItemId" field.</summary>
    public const int VariablesByItemIdFieldNumber = 6;
    private static readonly pbc::MapField<long, global::Commons.Resources.ResourceTrigger.Types.Variables>.Codec _map_variablesByItemId_codec
        = new pbc::MapField<long, global::Commons.Resources.ResourceTrigger.Types.Variables>.Codec(pb::FieldCodec.ForInt64(8, 0L), pb::FieldCodec.ForMessage(18, global::Commons.Resources.ResourceTrigger.Types.Variables.Parser), 50);
    private readonly pbc::MapField<long, global::Commons.Resources.ResourceTrigger.Types.Variables> variablesByItemId_ = new pbc::MapField<long, global::Commons.Resources.ResourceTrigger.Types.Variables>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<long, global::Commons.Resources.ResourceTrigger.Types.Variables> VariablesByItemId {
      get { return variablesByItemId_; }
    }

    /// <summary>Field number for the "equipSkillDataIds" field.</summary>
    public const int EquipSkillDataIdsFieldNumber = 7;
    private static readonly pb::FieldCodec<int> _repeated_equipSkillDataIds_codec
        = pb::FieldCodec.ForInt32(58);
    private readonly pbc::RepeatedField<int> equipSkillDataIds_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> EquipSkillDataIds {
      get { return equipSkillDataIds_; }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 100;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "dataId" field.</summary>
    public const int DataIdFieldNumber = 101;
    private int dataId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int DataId {
      get { return dataId_; }
      set {
        dataId_ = value;
      }
    }

    /// <summary>Field number for the "offset" field.</summary>
    public const int OffsetFieldNumber = 102;
    private int offset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Offset {
      get { return offset_; }
      set {
        offset_ = value;
      }
    }

    /// <summary>Field number for the "initPosition" field.</summary>
    public const int InitPositionFieldNumber = 103;
    private global::Commons.Types.Geometry.Vector2Message initPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Geometry.Vector2Message InitPosition {
      get { return initPosition_; }
      set {
        initPosition_ = value;
      }
    }

    /// <summary>Field number for the "ownerUnitId" field.</summary>
    public const int OwnerUnitIdFieldNumber = 104;
    private long ownerUnitId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long OwnerUnitId {
      get { return ownerUnitId_; }
      set {
        ownerUnitId_ = value;
      }
    }

    /// <summary>Field number for the "playerId" field.</summary>
    public const int PlayerIdFieldNumber = 200;
    private long playerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PlayerId {
      get { return playerId_; }
      set {
        playerId_ = value;
      }
    }

    /// <summary>Field number for the "playerAvatar" field.</summary>
    public const int PlayerAvatarFieldNumber = 201;
    private global::Commons.Types.Players.PlayerAvatar playerAvatar_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Players.PlayerAvatar PlayerAvatar {
      get { return playerAvatar_; }
      set {
        playerAvatar_ = value;
      }
    }

    /// <summary>Field number for the "playerAvatarWeaponSlot" field.</summary>
    public const int PlayerAvatarWeaponSlotFieldNumber = 202;
    private int playerAvatarWeaponSlot_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PlayerAvatarWeaponSlot {
      get { return playerAvatarWeaponSlot_; }
      set {
        playerAvatarWeaponSlot_ = value;
      }
    }

    /// <summary>Field number for the "team" field.</summary>
    public const int TeamFieldNumber = 300;
    private int team_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Team {
      get { return team_; }
      set {
        team_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 301;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 302;
    private long exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    /// <summary>Field number for the "tick" field.</summary>
    public const int TickFieldNumber = 400;
    private uint tick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Tick {
      get { return tick_; }
      set {
        tick_ = value;
      }
    }

    /// <summary>Field number for the "tickOffset" field.</summary>
    public const int TickOffsetFieldNumber = 401;
    private uint tickOffset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TickOffset {
      get { return tickOffset_; }
      set {
        tickOffset_ = value;
      }
    }

    /// <summary>Field number for the "variables" field.</summary>
    public const int VariablesFieldNumber = 402;
    private global::Commons.Resources.ResourceTrigger.Types.Variables variables_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Resources.ResourceTrigger.Types.Variables Variables {
      get { return variables_; }
      set {
        variables_ = value;
      }
    }

    /// <summary>Field number for the "nextBuffId" field.</summary>
    public const int NextBuffIdFieldNumber = 403;
    private uint nextBuffId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NextBuffId {
      get { return nextBuffId_; }
      set {
        nextBuffId_ = value;
      }
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 404;
    private global::Commons.Types.Geometry.Vector2Message position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Geometry.Vector2Message Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    /// <summary>Field number for the "direction" field.</summary>
    public const int DirectionFieldNumber = 405;
    private global::Commons.Types.Geometry.Vector2Message direction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Geometry.Vector2Message Direction {
      get { return direction_; }
      set {
        direction_ = value;
      }
    }

    /// <summary>Field number for the "velocity" field.</summary>
    public const int VelocityFieldNumber = 406;
    private global::Commons.Types.Geometry.Vector2Message velocity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Geometry.Vector2Message Velocity {
      get { return velocity_; }
      set {
        velocity_ = value;
      }
    }

    /// <summary>Field number for the "moveDirection" field.</summary>
    public const int MoveDirectionFieldNumber = 407;
    private global::Commons.Types.Geometry.Vector2Message moveDirection_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Geometry.Vector2Message MoveDirection {
      get { return moveDirection_; }
      set {
        moveDirection_ = value;
      }
    }

    /// <summary>Field number for the "moveDestination" field.</summary>
    public const int MoveDestinationFieldNumber = 408;
    private global::Commons.Types.Geometry.Vector2Message moveDestination_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Geometry.Vector2Message MoveDestination {
      get { return moveDestination_; }
      set {
        moveDestination_ = value;
      }
    }

    /// <summary>Field number for the "targetMode" field.</summary>
    public const int TargetModeFieldNumber = 409;
    private global::Commons.Resources.ResourceUnit.Types.TargetMode targetMode_ = global::Commons.Resources.ResourceUnit.Types.TargetMode.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Resources.ResourceUnit.Types.TargetMode TargetMode {
      get { return targetMode_; }
      set {
        targetMode_ = value;
      }
    }

    /// <summary>Field number for the "targetAwareDistance" field.</summary>
    public const int TargetAwareDistanceFieldNumber = 410;
    private float targetAwareDistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TargetAwareDistance {
      get { return targetAwareDistance_; }
      set {
        targetAwareDistance_ = value;
      }
    }

    /// <summary>Field number for the "targetResetDistance" field.</summary>
    public const int TargetResetDistanceFieldNumber = 411;
    private float targetResetDistance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float TargetResetDistance {
      get { return targetResetDistance_; }
      set {
        targetResetDistance_ = value;
      }
    }

    /// <summary>Field number for the "targetUnitId" field.</summary>
    public const int TargetUnitIdFieldNumber = 412;
    private long targetUnitId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TargetUnitId {
      get { return targetUnitId_; }
      set {
        targetUnitId_ = value;
      }
    }

    /// <summary>Field number for the "positionOffset" field.</summary>
    public const int PositionOffsetFieldNumber = 413;
    private global::Commons.Types.Geometry.Vector2Message positionOffset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Geometry.Vector2Message PositionOffset {
      get { return positionOffset_; }
      set {
        positionOffset_ = value;
      }
    }

    /// <summary>Field number for the "knockbackDirection" field.</summary>
    public const int KnockbackDirectionFieldNumber = 500;
    private global::Commons.Types.Geometry.Vector2Message knockbackDirection_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Commons.Types.Geometry.Vector2Message KnockbackDirection {
      get { return knockbackDirection_; }
      set {
        knockbackDirection_ = value;
      }
    }

    /// <summary>Field number for the "knockbackTick" field.</summary>
    public const int KnockbackTickFieldNumber = 501;
    private uint knockbackTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KnockbackTick {
      get { return knockbackTick_; }
      set {
        knockbackTick_ = value;
      }
    }

    /// <summary>Field number for the "knockbackSpeed" field.</summary>
    public const int KnockbackSpeedFieldNumber = 502;
    private float knockbackSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float KnockbackSpeed {
      get { return knockbackSpeed_; }
      set {
        knockbackSpeed_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 600;
    private uint state_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "moveDisabledTick" field.</summary>
    public const int MoveDisabledTickFieldNumber = 601;
    private uint moveDisabledTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MoveDisabledTick {
      get { return moveDisabledTick_; }
      set {
        moveDisabledTick_ = value;
      }
    }

    /// <summary>Field number for the "actionDisabledTick" field.</summary>
    public const int ActionDisabledTickFieldNumber = 602;
    private uint actionDisabledTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ActionDisabledTick {
      get { return actionDisabledTick_; }
      set {
        actionDisabledTick_ = value;
      }
    }

    /// <summary>Field number for the "actionDisabledPriority" field.</summary>
    public const int ActionDisabledPriorityFieldNumber = 603;
    private int actionDisabledPriority_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ActionDisabledPriority {
      get { return actionDisabledPriority_; }
      set {
        actionDisabledPriority_ = value;
      }
    }

    /// <summary>Field number for the "destroyTick" field.</summary>
    public const int DestroyTickFieldNumber = 604;
    private uint destroyTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DestroyTick {
      get { return destroyTick_; }
      set {
        destroyTick_ = value;
      }
    }

    /// <summary>Field number for the "respawnTick" field.</summary>
    public const int RespawnTickFieldNumber = 605;
    private uint respawnTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RespawnTick {
      get { return respawnTick_; }
      set {
        respawnTick_ = value;
      }
    }

    /// <summary>Field number for the "noDamageTick" field.</summary>
    public const int NoDamageTickFieldNumber = 606;
    private uint noDamageTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint NoDamageTick {
      get { return noDamageTick_; }
      set {
        noDamageTick_ = value;
      }
    }

    /// <summary>Field number for the "hp" field.</summary>
    public const int HpFieldNumber = 700;
    private long hp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Hp {
      get { return hp_; }
      set {
        hp_ = value;
      }
    }

    /// <summary>Field number for the "mp" field.</summary>
    public const int MpFieldNumber = 701;
    private long mp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Mp {
      get { return mp_; }
      set {
        mp_ = value;
      }
    }

    /// <summary>Field number for the "shield" field.</summary>
    public const int ShieldFieldNumber = 702;
    private long shield_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Shield {
      get { return shield_; }
      set {
        shield_ = value;
      }
    }

    /// <summary>Field number for the "sp" field.</summary>
    public const int SpFieldNumber = 703;
    private long sp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Sp {
      get { return sp_; }
      set {
        sp_ = value;
      }
    }

    /// <summary>Field number for the "spRegenTick" field.</summary>
    public const int SpRegenTickFieldNumber = 704;
    private uint spRegenTick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SpRegenTick {
      get { return spRegenTick_; }
      set {
        spRegenTick_ = value;
      }
    }

    /// <summary>Field number for the "guard" field.</summary>
    public const int GuardFieldNumber = 705;
    private long guard_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Guard {
      get { return guard_; }
      set {
        guard_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameUnit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameUnit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!path_.Equals(other.path_)) return false;
      if (!Cooldowns.Equals(other.Cooldowns)) return false;
      if(!baseStat_.Equals(other.baseStat_)) return false;
      if (!Buffs.Equals(other.Buffs)) return false;
      if (!ItemCooldowns.Equals(other.ItemCooldowns)) return false;
      if (!VariablesByItemId.Equals(other.VariablesByItemId)) return false;
      if(!equipSkillDataIds_.Equals(other.equipSkillDataIds_)) return false;
      if (Id != other.Id) return false;
      if (DataId != other.DataId) return false;
      if (Offset != other.Offset) return false;
      if (!object.Equals(InitPosition, other.InitPosition)) return false;
      if (OwnerUnitId != other.OwnerUnitId) return false;
      if (PlayerId != other.PlayerId) return false;
      if (!object.Equals(PlayerAvatar, other.PlayerAvatar)) return false;
      if (PlayerAvatarWeaponSlot != other.PlayerAvatarWeaponSlot) return false;
      if (Team != other.Team) return false;
      if (Level != other.Level) return false;
      if (Exp != other.Exp) return false;
      if (Tick != other.Tick) return false;
      if (TickOffset != other.TickOffset) return false;
      if (!object.Equals(Variables, other.Variables)) return false;
      if (NextBuffId != other.NextBuffId) return false;
      if (!object.Equals(Position, other.Position)) return false;
      if (!object.Equals(Direction, other.Direction)) return false;
      if (!object.Equals(Velocity, other.Velocity)) return false;
      if (!object.Equals(MoveDirection, other.MoveDirection)) return false;
      if (!object.Equals(MoveDestination, other.MoveDestination)) return false;
      if (TargetMode != other.TargetMode) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TargetAwareDistance, other.TargetAwareDistance)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TargetResetDistance, other.TargetResetDistance)) return false;
      if (TargetUnitId != other.TargetUnitId) return false;
      if (!object.Equals(PositionOffset, other.PositionOffset)) return false;
      if (!object.Equals(KnockbackDirection, other.KnockbackDirection)) return false;
      if (KnockbackTick != other.KnockbackTick) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(KnockbackSpeed, other.KnockbackSpeed)) return false;
      if (State != other.State) return false;
      if (MoveDisabledTick != other.MoveDisabledTick) return false;
      if (ActionDisabledTick != other.ActionDisabledTick) return false;
      if (ActionDisabledPriority != other.ActionDisabledPriority) return false;
      if (DestroyTick != other.DestroyTick) return false;
      if (RespawnTick != other.RespawnTick) return false;
      if (NoDamageTick != other.NoDamageTick) return false;
      if (Hp != other.Hp) return false;
      if (Mp != other.Mp) return false;
      if (Shield != other.Shield) return false;
      if (Sp != other.Sp) return false;
      if (SpRegenTick != other.SpRegenTick) return false;
      if (Guard != other.Guard) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= path_.GetHashCode();
      hash ^= Cooldowns.GetHashCode();
      hash ^= baseStat_.GetHashCode();
      hash ^= Buffs.GetHashCode();
      hash ^= ItemCooldowns.GetHashCode();
      hash ^= VariablesByItemId.GetHashCode();
      hash ^= equipSkillDataIds_.GetHashCode();
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (DataId != 0) hash ^= DataId.GetHashCode();
      if (Offset != 0) hash ^= Offset.GetHashCode();
      if (initPosition_ != null) hash ^= InitPosition.GetHashCode();
      if (OwnerUnitId != 0L) hash ^= OwnerUnitId.GetHashCode();
      if (PlayerId != 0L) hash ^= PlayerId.GetHashCode();
      if (playerAvatar_ != null) hash ^= PlayerAvatar.GetHashCode();
      if (PlayerAvatarWeaponSlot != 0) hash ^= PlayerAvatarWeaponSlot.GetHashCode();
      if (Team != 0) hash ^= Team.GetHashCode();
      if (Level != 0) hash ^= Level.GetHashCode();
      if (Exp != 0L) hash ^= Exp.GetHashCode();
      if (Tick != 0) hash ^= Tick.GetHashCode();
      if (TickOffset != 0) hash ^= TickOffset.GetHashCode();
      if (variables_ != null) hash ^= Variables.GetHashCode();
      if (NextBuffId != 0) hash ^= NextBuffId.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (direction_ != null) hash ^= Direction.GetHashCode();
      if (velocity_ != null) hash ^= Velocity.GetHashCode();
      if (moveDirection_ != null) hash ^= MoveDirection.GetHashCode();
      if (moveDestination_ != null) hash ^= MoveDestination.GetHashCode();
      if (TargetMode != global::Commons.Resources.ResourceUnit.Types.TargetMode.None) hash ^= TargetMode.GetHashCode();
      if (TargetAwareDistance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TargetAwareDistance);
      if (TargetResetDistance != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TargetResetDistance);
      if (TargetUnitId != 0L) hash ^= TargetUnitId.GetHashCode();
      if (positionOffset_ != null) hash ^= PositionOffset.GetHashCode();
      if (knockbackDirection_ != null) hash ^= KnockbackDirection.GetHashCode();
      if (KnockbackTick != 0) hash ^= KnockbackTick.GetHashCode();
      if (KnockbackSpeed != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(KnockbackSpeed);
      if (State != 0) hash ^= State.GetHashCode();
      if (MoveDisabledTick != 0) hash ^= MoveDisabledTick.GetHashCode();
      if (ActionDisabledTick != 0) hash ^= ActionDisabledTick.GetHashCode();
      if (ActionDisabledPriority != 0) hash ^= ActionDisabledPriority.GetHashCode();
      if (DestroyTick != 0) hash ^= DestroyTick.GetHashCode();
      if (RespawnTick != 0) hash ^= RespawnTick.GetHashCode();
      if (NoDamageTick != 0) hash ^= NoDamageTick.GetHashCode();
      if (Hp != 0L) hash ^= Hp.GetHashCode();
      if (Mp != 0L) hash ^= Mp.GetHashCode();
      if (Shield != 0L) hash ^= Shield.GetHashCode();
      if (Sp != 0L) hash ^= Sp.GetHashCode();
      if (SpRegenTick != 0) hash ^= SpRegenTick.GetHashCode();
      if (Guard != 0L) hash ^= Guard.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      path_.WriteTo(output, _repeated_path_codec);
      cooldowns_.WriteTo(output, _map_cooldowns_codec);
      baseStat_.WriteTo(output, _repeated_baseStat_codec);
      buffs_.WriteTo(output, _map_buffs_codec);
      itemCooldowns_.WriteTo(output, _map_itemCooldowns_codec);
      variablesByItemId_.WriteTo(output, _map_variablesByItemId_codec);
      equipSkillDataIds_.WriteTo(output, _repeated_equipSkillDataIds_codec);
      if (Id != 0L) {
        output.WriteRawTag(160, 6);
        output.WriteInt64(Id);
      }
      if (DataId != 0) {
        output.WriteRawTag(168, 6);
        output.WriteInt32(DataId);
      }
      if (Offset != 0) {
        output.WriteRawTag(176, 6);
        output.WriteInt32(Offset);
      }
      if (initPosition_ != null) {
        output.WriteRawTag(186, 6);
        output.WriteMessage(InitPosition);
      }
      if (OwnerUnitId != 0L) {
        output.WriteRawTag(192, 6);
        output.WriteInt64(OwnerUnitId);
      }
      if (PlayerId != 0L) {
        output.WriteRawTag(192, 12);
        output.WriteInt64(PlayerId);
      }
      if (playerAvatar_ != null) {
        output.WriteRawTag(202, 12);
        output.WriteMessage(PlayerAvatar);
      }
      if (PlayerAvatarWeaponSlot != 0) {
        output.WriteRawTag(208, 12);
        output.WriteInt32(PlayerAvatarWeaponSlot);
      }
      if (Team != 0) {
        output.WriteRawTag(224, 18);
        output.WriteInt32(Team);
      }
      if (Level != 0) {
        output.WriteRawTag(232, 18);
        output.WriteInt32(Level);
      }
      if (Exp != 0L) {
        output.WriteRawTag(240, 18);
        output.WriteInt64(Exp);
      }
      if (Tick != 0) {
        output.WriteRawTag(128, 25);
        output.WriteUInt32(Tick);
      }
      if (TickOffset != 0) {
        output.WriteRawTag(136, 25);
        output.WriteUInt32(TickOffset);
      }
      if (variables_ != null) {
        output.WriteRawTag(146, 25);
        output.WriteMessage(Variables);
      }
      if (NextBuffId != 0) {
        output.WriteRawTag(152, 25);
        output.WriteUInt32(NextBuffId);
      }
      if (position_ != null) {
        output.WriteRawTag(162, 25);
        output.WriteMessage(Position);
      }
      if (direction_ != null) {
        output.WriteRawTag(170, 25);
        output.WriteMessage(Direction);
      }
      if (velocity_ != null) {
        output.WriteRawTag(178, 25);
        output.WriteMessage(Velocity);
      }
      if (moveDirection_ != null) {
        output.WriteRawTag(186, 25);
        output.WriteMessage(MoveDirection);
      }
      if (moveDestination_ != null) {
        output.WriteRawTag(194, 25);
        output.WriteMessage(MoveDestination);
      }
      if (TargetMode != global::Commons.Resources.ResourceUnit.Types.TargetMode.None) {
        output.WriteRawTag(200, 25);
        output.WriteEnum((int) TargetMode);
      }
      if (TargetAwareDistance != 0F) {
        output.WriteRawTag(213, 25);
        output.WriteFloat(TargetAwareDistance);
      }
      if (TargetResetDistance != 0F) {
        output.WriteRawTag(221, 25);
        output.WriteFloat(TargetResetDistance);
      }
      if (TargetUnitId != 0L) {
        output.WriteRawTag(224, 25);
        output.WriteInt64(TargetUnitId);
      }
      if (positionOffset_ != null) {
        output.WriteRawTag(234, 25);
        output.WriteMessage(PositionOffset);
      }
      if (knockbackDirection_ != null) {
        output.WriteRawTag(162, 31);
        output.WriteMessage(KnockbackDirection);
      }
      if (KnockbackTick != 0) {
        output.WriteRawTag(168, 31);
        output.WriteUInt32(KnockbackTick);
      }
      if (KnockbackSpeed != 0F) {
        output.WriteRawTag(181, 31);
        output.WriteFloat(KnockbackSpeed);
      }
      if (State != 0) {
        output.WriteRawTag(192, 37);
        output.WriteUInt32(State);
      }
      if (MoveDisabledTick != 0) {
        output.WriteRawTag(200, 37);
        output.WriteUInt32(MoveDisabledTick);
      }
      if (ActionDisabledTick != 0) {
        output.WriteRawTag(208, 37);
        output.WriteUInt32(ActionDisabledTick);
      }
      if (ActionDisabledPriority != 0) {
        output.WriteRawTag(216, 37);
        output.WriteInt32(ActionDisabledPriority);
      }
      if (DestroyTick != 0) {
        output.WriteRawTag(224, 37);
        output.WriteUInt32(DestroyTick);
      }
      if (RespawnTick != 0) {
        output.WriteRawTag(232, 37);
        output.WriteUInt32(RespawnTick);
      }
      if (NoDamageTick != 0) {
        output.WriteRawTag(240, 37);
        output.WriteUInt32(NoDamageTick);
      }
      if (Hp != 0L) {
        output.WriteRawTag(224, 43);
        output.WriteInt64(Hp);
      }
      if (Mp != 0L) {
        output.WriteRawTag(232, 43);
        output.WriteInt64(Mp);
      }
      if (Shield != 0L) {
        output.WriteRawTag(240, 43);
        output.WriteInt64(Shield);
      }
      if (Sp != 0L) {
        output.WriteRawTag(248, 43);
        output.WriteInt64(Sp);
      }
      if (SpRegenTick != 0) {
        output.WriteRawTag(128, 44);
        output.WriteUInt32(SpRegenTick);
      }
      if (Guard != 0L) {
        output.WriteRawTag(136, 44);
        output.WriteInt64(Guard);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      path_.WriteTo(ref output, _repeated_path_codec);
      cooldowns_.WriteTo(ref output, _map_cooldowns_codec);
      baseStat_.WriteTo(ref output, _repeated_baseStat_codec);
      buffs_.WriteTo(ref output, _map_buffs_codec);
      itemCooldowns_.WriteTo(ref output, _map_itemCooldowns_codec);
      variablesByItemId_.WriteTo(ref output, _map_variablesByItemId_codec);
      equipSkillDataIds_.WriteTo(ref output, _repeated_equipSkillDataIds_codec);
      if (Id != 0L) {
        output.WriteRawTag(160, 6);
        output.WriteInt64(Id);
      }
      if (DataId != 0) {
        output.WriteRawTag(168, 6);
        output.WriteInt32(DataId);
      }
      if (Offset != 0) {
        output.WriteRawTag(176, 6);
        output.WriteInt32(Offset);
      }
      if (initPosition_ != null) {
        output.WriteRawTag(186, 6);
        output.WriteMessage(InitPosition);
      }
      if (OwnerUnitId != 0L) {
        output.WriteRawTag(192, 6);
        output.WriteInt64(OwnerUnitId);
      }
      if (PlayerId != 0L) {
        output.WriteRawTag(192, 12);
        output.WriteInt64(PlayerId);
      }
      if (playerAvatar_ != null) {
        output.WriteRawTag(202, 12);
        output.WriteMessage(PlayerAvatar);
      }
      if (PlayerAvatarWeaponSlot != 0) {
        output.WriteRawTag(208, 12);
        output.WriteInt32(PlayerAvatarWeaponSlot);
      }
      if (Team != 0) {
        output.WriteRawTag(224, 18);
        output.WriteInt32(Team);
      }
      if (Level != 0) {
        output.WriteRawTag(232, 18);
        output.WriteInt32(Level);
      }
      if (Exp != 0L) {
        output.WriteRawTag(240, 18);
        output.WriteInt64(Exp);
      }
      if (Tick != 0) {
        output.WriteRawTag(128, 25);
        output.WriteUInt32(Tick);
      }
      if (TickOffset != 0) {
        output.WriteRawTag(136, 25);
        output.WriteUInt32(TickOffset);
      }
      if (variables_ != null) {
        output.WriteRawTag(146, 25);
        output.WriteMessage(Variables);
      }
      if (NextBuffId != 0) {
        output.WriteRawTag(152, 25);
        output.WriteUInt32(NextBuffId);
      }
      if (position_ != null) {
        output.WriteRawTag(162, 25);
        output.WriteMessage(Position);
      }
      if (direction_ != null) {
        output.WriteRawTag(170, 25);
        output.WriteMessage(Direction);
      }
      if (velocity_ != null) {
        output.WriteRawTag(178, 25);
        output.WriteMessage(Velocity);
      }
      if (moveDirection_ != null) {
        output.WriteRawTag(186, 25);
        output.WriteMessage(MoveDirection);
      }
      if (moveDestination_ != null) {
        output.WriteRawTag(194, 25);
        output.WriteMessage(MoveDestination);
      }
      if (TargetMode != global::Commons.Resources.ResourceUnit.Types.TargetMode.None) {
        output.WriteRawTag(200, 25);
        output.WriteEnum((int) TargetMode);
      }
      if (TargetAwareDistance != 0F) {
        output.WriteRawTag(213, 25);
        output.WriteFloat(TargetAwareDistance);
      }
      if (TargetResetDistance != 0F) {
        output.WriteRawTag(221, 25);
        output.WriteFloat(TargetResetDistance);
      }
      if (TargetUnitId != 0L) {
        output.WriteRawTag(224, 25);
        output.WriteInt64(TargetUnitId);
      }
      if (positionOffset_ != null) {
        output.WriteRawTag(234, 25);
        output.WriteMessage(PositionOffset);
      }
      if (knockbackDirection_ != null) {
        output.WriteRawTag(162, 31);
        output.WriteMessage(KnockbackDirection);
      }
      if (KnockbackTick != 0) {
        output.WriteRawTag(168, 31);
        output.WriteUInt32(KnockbackTick);
      }
      if (KnockbackSpeed != 0F) {
        output.WriteRawTag(181, 31);
        output.WriteFloat(KnockbackSpeed);
      }
      if (State != 0) {
        output.WriteRawTag(192, 37);
        output.WriteUInt32(State);
      }
      if (MoveDisabledTick != 0) {
        output.WriteRawTag(200, 37);
        output.WriteUInt32(MoveDisabledTick);
      }
      if (ActionDisabledTick != 0) {
        output.WriteRawTag(208, 37);
        output.WriteUInt32(ActionDisabledTick);
      }
      if (ActionDisabledPriority != 0) {
        output.WriteRawTag(216, 37);
        output.WriteInt32(ActionDisabledPriority);
      }
      if (DestroyTick != 0) {
        output.WriteRawTag(224, 37);
        output.WriteUInt32(DestroyTick);
      }
      if (RespawnTick != 0) {
        output.WriteRawTag(232, 37);
        output.WriteUInt32(RespawnTick);
      }
      if (NoDamageTick != 0) {
        output.WriteRawTag(240, 37);
        output.WriteUInt32(NoDamageTick);
      }
      if (Hp != 0L) {
        output.WriteRawTag(224, 43);
        output.WriteInt64(Hp);
      }
      if (Mp != 0L) {
        output.WriteRawTag(232, 43);
        output.WriteInt64(Mp);
      }
      if (Shield != 0L) {
        output.WriteRawTag(240, 43);
        output.WriteInt64(Shield);
      }
      if (Sp != 0L) {
        output.WriteRawTag(248, 43);
        output.WriteInt64(Sp);
      }
      if (SpRegenTick != 0) {
        output.WriteRawTag(128, 44);
        output.WriteUInt32(SpRegenTick);
      }
      if (Guard != 0L) {
        output.WriteRawTag(136, 44);
        output.WriteInt64(Guard);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += path_.CalculateSize(_repeated_path_codec);
      size += cooldowns_.CalculateSize(_map_cooldowns_codec);
      size += baseStat_.CalculateSize(_repeated_baseStat_codec);
      size += buffs_.CalculateSize(_map_buffs_codec);
      size += itemCooldowns_.CalculateSize(_map_itemCooldowns_codec);
      size += variablesByItemId_.CalculateSize(_map_variablesByItemId_codec);
      size += equipSkillDataIds_.CalculateSize(_repeated_equipSkillDataIds_codec);
      if (Id != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (DataId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(DataId);
      }
      if (Offset != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Offset);
      }
      if (initPosition_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(InitPosition);
      }
      if (OwnerUnitId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(OwnerUnitId);
      }
      if (PlayerId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(PlayerId);
      }
      if (playerAvatar_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PlayerAvatar);
      }
      if (PlayerAvatarWeaponSlot != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(PlayerAvatarWeaponSlot);
      }
      if (Team != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Team);
      }
      if (Level != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (Exp != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Exp);
      }
      if (Tick != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(Tick);
      }
      if (TickOffset != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(TickOffset);
      }
      if (variables_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Variables);
      }
      if (NextBuffId != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(NextBuffId);
      }
      if (position_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (direction_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Direction);
      }
      if (velocity_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Velocity);
      }
      if (moveDirection_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(MoveDirection);
      }
      if (moveDestination_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(MoveDestination);
      }
      if (TargetMode != global::Commons.Resources.ResourceUnit.Types.TargetMode.None) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) TargetMode);
      }
      if (TargetAwareDistance != 0F) {
        size += 2 + 4;
      }
      if (TargetResetDistance != 0F) {
        size += 2 + 4;
      }
      if (TargetUnitId != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(TargetUnitId);
      }
      if (positionOffset_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(PositionOffset);
      }
      if (knockbackDirection_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(KnockbackDirection);
      }
      if (KnockbackTick != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(KnockbackTick);
      }
      if (KnockbackSpeed != 0F) {
        size += 2 + 4;
      }
      if (State != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(State);
      }
      if (MoveDisabledTick != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(MoveDisabledTick);
      }
      if (ActionDisabledTick != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(ActionDisabledTick);
      }
      if (ActionDisabledPriority != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(ActionDisabledPriority);
      }
      if (DestroyTick != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(DestroyTick);
      }
      if (RespawnTick != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(RespawnTick);
      }
      if (NoDamageTick != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(NoDamageTick);
      }
      if (Hp != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Hp);
      }
      if (Mp != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Mp);
      }
      if (Shield != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Shield);
      }
      if (Sp != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Sp);
      }
      if (SpRegenTick != 0) {
        size += 2 + pb::CodedOutputStream.ComputeUInt32Size(SpRegenTick);
      }
      if (Guard != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Guard);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameUnit other) {
      if (other == null) {
        return;
      }
      path_.Add(other.path_);
      cooldowns_.MergeFrom(other.cooldowns_);
      baseStat_.Add(other.baseStat_);
      buffs_.MergeFrom(other.buffs_);
      itemCooldowns_.MergeFrom(other.itemCooldowns_);
      variablesByItemId_.MergeFrom(other.variablesByItemId_);
      equipSkillDataIds_.Add(other.equipSkillDataIds_);
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.DataId != 0) {
        DataId = other.DataId;
      }
      if (other.Offset != 0) {
        Offset = other.Offset;
      }
      if (other.initPosition_ != null) {
        if (initPosition_ == null) {
          InitPosition = new global::Commons.Types.Geometry.Vector2Message();
        }
        InitPosition.MergeFrom(other.InitPosition);
      }
      if (other.OwnerUnitId != 0L) {
        OwnerUnitId = other.OwnerUnitId;
      }
      if (other.PlayerId != 0L) {
        PlayerId = other.PlayerId;
      }
      if (other.playerAvatar_ != null) {
        if (playerAvatar_ == null) {
          PlayerAvatar = new global::Commons.Types.Players.PlayerAvatar();
        }
        PlayerAvatar.MergeFrom(other.PlayerAvatar);
      }
      if (other.PlayerAvatarWeaponSlot != 0) {
        PlayerAvatarWeaponSlot = other.PlayerAvatarWeaponSlot;
      }
      if (other.Team != 0) {
        Team = other.Team;
      }
      if (other.Level != 0) {
        Level = other.Level;
      }
      if (other.Exp != 0L) {
        Exp = other.Exp;
      }
      if (other.Tick != 0) {
        Tick = other.Tick;
      }
      if (other.TickOffset != 0) {
        TickOffset = other.TickOffset;
      }
      if (other.variables_ != null) {
        if (variables_ == null) {
          Variables = new global::Commons.Resources.ResourceTrigger.Types.Variables();
        }
        Variables.MergeFrom(other.Variables);
      }
      if (other.NextBuffId != 0) {
        NextBuffId = other.NextBuffId;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Commons.Types.Geometry.Vector2Message();
        }
        Position.MergeFrom(other.Position);
      }
      if (other.direction_ != null) {
        if (direction_ == null) {
          Direction = new global::Commons.Types.Geometry.Vector2Message();
        }
        Direction.MergeFrom(other.Direction);
      }
      if (other.velocity_ != null) {
        if (velocity_ == null) {
          Velocity = new global::Commons.Types.Geometry.Vector2Message();
        }
        Velocity.MergeFrom(other.Velocity);
      }
      if (other.moveDirection_ != null) {
        if (moveDirection_ == null) {
          MoveDirection = new global::Commons.Types.Geometry.Vector2Message();
        }
        MoveDirection.MergeFrom(other.MoveDirection);
      }
      if (other.moveDestination_ != null) {
        if (moveDestination_ == null) {
          MoveDestination = new global::Commons.Types.Geometry.Vector2Message();
        }
        MoveDestination.MergeFrom(other.MoveDestination);
      }
      if (other.TargetMode != global::Commons.Resources.ResourceUnit.Types.TargetMode.None) {
        TargetMode = other.TargetMode;
      }
      if (other.TargetAwareDistance != 0F) {
        TargetAwareDistance = other.TargetAwareDistance;
      }
      if (other.TargetResetDistance != 0F) {
        TargetResetDistance = other.TargetResetDistance;
      }
      if (other.TargetUnitId != 0L) {
        TargetUnitId = other.TargetUnitId;
      }
      if (other.positionOffset_ != null) {
        if (positionOffset_ == null) {
          PositionOffset = new global::Commons.Types.Geometry.Vector2Message();
        }
        PositionOffset.MergeFrom(other.PositionOffset);
      }
      if (other.knockbackDirection_ != null) {
        if (knockbackDirection_ == null) {
          KnockbackDirection = new global::Commons.Types.Geometry.Vector2Message();
        }
        KnockbackDirection.MergeFrom(other.KnockbackDirection);
      }
      if (other.KnockbackTick != 0) {
        KnockbackTick = other.KnockbackTick;
      }
      if (other.KnockbackSpeed != 0F) {
        KnockbackSpeed = other.KnockbackSpeed;
      }
      if (other.State != 0) {
        State = other.State;
      }
      if (other.MoveDisabledTick != 0) {
        MoveDisabledTick = other.MoveDisabledTick;
      }
      if (other.ActionDisabledTick != 0) {
        ActionDisabledTick = other.ActionDisabledTick;
      }
      if (other.ActionDisabledPriority != 0) {
        ActionDisabledPriority = other.ActionDisabledPriority;
      }
      if (other.DestroyTick != 0) {
        DestroyTick = other.DestroyTick;
      }
      if (other.RespawnTick != 0) {
        RespawnTick = other.RespawnTick;
      }
      if (other.NoDamageTick != 0) {
        NoDamageTick = other.NoDamageTick;
      }
      if (other.Hp != 0L) {
        Hp = other.Hp;
      }
      if (other.Mp != 0L) {
        Mp = other.Mp;
      }
      if (other.Shield != 0L) {
        Shield = other.Shield;
      }
      if (other.Sp != 0L) {
        Sp = other.Sp;
      }
      if (other.SpRegenTick != 0) {
        SpRegenTick = other.SpRegenTick;
      }
      if (other.Guard != 0L) {
        Guard = other.Guard;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            path_.AddEntriesFrom(input, _repeated_path_codec);
            break;
          }
          case 18: {
            cooldowns_.AddEntriesFrom(input, _map_cooldowns_codec);
            break;
          }
          case 26:
          case 29: {
            baseStat_.AddEntriesFrom(input, _repeated_baseStat_codec);
            break;
          }
          case 34: {
            buffs_.AddEntriesFrom(input, _map_buffs_codec);
            break;
          }
          case 42: {
            itemCooldowns_.AddEntriesFrom(input, _map_itemCooldowns_codec);
            break;
          }
          case 50: {
            variablesByItemId_.AddEntriesFrom(input, _map_variablesByItemId_codec);
            break;
          }
          case 58:
          case 56: {
            equipSkillDataIds_.AddEntriesFrom(input, _repeated_equipSkillDataIds_codec);
            break;
          }
          case 800: {
            Id = input.ReadInt64();
            break;
          }
          case 808: {
            DataId = input.ReadInt32();
            break;
          }
          case 816: {
            Offset = input.ReadInt32();
            break;
          }
          case 826: {
            if (initPosition_ == null) {
              InitPosition = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(InitPosition);
            break;
          }
          case 832: {
            OwnerUnitId = input.ReadInt64();
            break;
          }
          case 1600: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 1610: {
            if (playerAvatar_ == null) {
              PlayerAvatar = new global::Commons.Types.Players.PlayerAvatar();
            }
            input.ReadMessage(PlayerAvatar);
            break;
          }
          case 1616: {
            PlayerAvatarWeaponSlot = input.ReadInt32();
            break;
          }
          case 2400: {
            Team = input.ReadInt32();
            break;
          }
          case 2408: {
            Level = input.ReadInt32();
            break;
          }
          case 2416: {
            Exp = input.ReadInt64();
            break;
          }
          case 3200: {
            Tick = input.ReadUInt32();
            break;
          }
          case 3208: {
            TickOffset = input.ReadUInt32();
            break;
          }
          case 3218: {
            if (variables_ == null) {
              Variables = new global::Commons.Resources.ResourceTrigger.Types.Variables();
            }
            input.ReadMessage(Variables);
            break;
          }
          case 3224: {
            NextBuffId = input.ReadUInt32();
            break;
          }
          case 3234: {
            if (position_ == null) {
              Position = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(Position);
            break;
          }
          case 3242: {
            if (direction_ == null) {
              Direction = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(Direction);
            break;
          }
          case 3250: {
            if (velocity_ == null) {
              Velocity = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 3258: {
            if (moveDirection_ == null) {
              MoveDirection = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(MoveDirection);
            break;
          }
          case 3266: {
            if (moveDestination_ == null) {
              MoveDestination = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(MoveDestination);
            break;
          }
          case 3272: {
            TargetMode = (global::Commons.Resources.ResourceUnit.Types.TargetMode) input.ReadEnum();
            break;
          }
          case 3285: {
            TargetAwareDistance = input.ReadFloat();
            break;
          }
          case 3293: {
            TargetResetDistance = input.ReadFloat();
            break;
          }
          case 3296: {
            TargetUnitId = input.ReadInt64();
            break;
          }
          case 3306: {
            if (positionOffset_ == null) {
              PositionOffset = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(PositionOffset);
            break;
          }
          case 4002: {
            if (knockbackDirection_ == null) {
              KnockbackDirection = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(KnockbackDirection);
            break;
          }
          case 4008: {
            KnockbackTick = input.ReadUInt32();
            break;
          }
          case 4021: {
            KnockbackSpeed = input.ReadFloat();
            break;
          }
          case 4800: {
            State = input.ReadUInt32();
            break;
          }
          case 4808: {
            MoveDisabledTick = input.ReadUInt32();
            break;
          }
          case 4816: {
            ActionDisabledTick = input.ReadUInt32();
            break;
          }
          case 4824: {
            ActionDisabledPriority = input.ReadInt32();
            break;
          }
          case 4832: {
            DestroyTick = input.ReadUInt32();
            break;
          }
          case 4840: {
            RespawnTick = input.ReadUInt32();
            break;
          }
          case 4848: {
            NoDamageTick = input.ReadUInt32();
            break;
          }
          case 5600: {
            Hp = input.ReadInt64();
            break;
          }
          case 5608: {
            Mp = input.ReadInt64();
            break;
          }
          case 5616: {
            Shield = input.ReadInt64();
            break;
          }
          case 5624: {
            Sp = input.ReadInt64();
            break;
          }
          case 5632: {
            SpRegenTick = input.ReadUInt32();
            break;
          }
          case 5640: {
            Guard = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            path_.AddEntriesFrom(ref input, _repeated_path_codec);
            break;
          }
          case 18: {
            cooldowns_.AddEntriesFrom(ref input, _map_cooldowns_codec);
            break;
          }
          case 26:
          case 29: {
            baseStat_.AddEntriesFrom(ref input, _repeated_baseStat_codec);
            break;
          }
          case 34: {
            buffs_.AddEntriesFrom(ref input, _map_buffs_codec);
            break;
          }
          case 42: {
            itemCooldowns_.AddEntriesFrom(ref input, _map_itemCooldowns_codec);
            break;
          }
          case 50: {
            variablesByItemId_.AddEntriesFrom(ref input, _map_variablesByItemId_codec);
            break;
          }
          case 58:
          case 56: {
            equipSkillDataIds_.AddEntriesFrom(ref input, _repeated_equipSkillDataIds_codec);
            break;
          }
          case 800: {
            Id = input.ReadInt64();
            break;
          }
          case 808: {
            DataId = input.ReadInt32();
            break;
          }
          case 816: {
            Offset = input.ReadInt32();
            break;
          }
          case 826: {
            if (initPosition_ == null) {
              InitPosition = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(InitPosition);
            break;
          }
          case 832: {
            OwnerUnitId = input.ReadInt64();
            break;
          }
          case 1600: {
            PlayerId = input.ReadInt64();
            break;
          }
          case 1610: {
            if (playerAvatar_ == null) {
              PlayerAvatar = new global::Commons.Types.Players.PlayerAvatar();
            }
            input.ReadMessage(PlayerAvatar);
            break;
          }
          case 1616: {
            PlayerAvatarWeaponSlot = input.ReadInt32();
            break;
          }
          case 2400: {
            Team = input.ReadInt32();
            break;
          }
          case 2408: {
            Level = input.ReadInt32();
            break;
          }
          case 2416: {
            Exp = input.ReadInt64();
            break;
          }
          case 3200: {
            Tick = input.ReadUInt32();
            break;
          }
          case 3208: {
            TickOffset = input.ReadUInt32();
            break;
          }
          case 3218: {
            if (variables_ == null) {
              Variables = new global::Commons.Resources.ResourceTrigger.Types.Variables();
            }
            input.ReadMessage(Variables);
            break;
          }
          case 3224: {
            NextBuffId = input.ReadUInt32();
            break;
          }
          case 3234: {
            if (position_ == null) {
              Position = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(Position);
            break;
          }
          case 3242: {
            if (direction_ == null) {
              Direction = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(Direction);
            break;
          }
          case 3250: {
            if (velocity_ == null) {
              Velocity = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(Velocity);
            break;
          }
          case 3258: {
            if (moveDirection_ == null) {
              MoveDirection = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(MoveDirection);
            break;
          }
          case 3266: {
            if (moveDestination_ == null) {
              MoveDestination = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(MoveDestination);
            break;
          }
          case 3272: {
            TargetMode = (global::Commons.Resources.ResourceUnit.Types.TargetMode) input.ReadEnum();
            break;
          }
          case 3285: {
            TargetAwareDistance = input.ReadFloat();
            break;
          }
          case 3293: {
            TargetResetDistance = input.ReadFloat();
            break;
          }
          case 3296: {
            TargetUnitId = input.ReadInt64();
            break;
          }
          case 3306: {
            if (positionOffset_ == null) {
              PositionOffset = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(PositionOffset);
            break;
          }
          case 4002: {
            if (knockbackDirection_ == null) {
              KnockbackDirection = new global::Commons.Types.Geometry.Vector2Message();
            }
            input.ReadMessage(KnockbackDirection);
            break;
          }
          case 4008: {
            KnockbackTick = input.ReadUInt32();
            break;
          }
          case 4021: {
            KnockbackSpeed = input.ReadFloat();
            break;
          }
          case 4800: {
            State = input.ReadUInt32();
            break;
          }
          case 4808: {
            MoveDisabledTick = input.ReadUInt32();
            break;
          }
          case 4816: {
            ActionDisabledTick = input.ReadUInt32();
            break;
          }
          case 4824: {
            ActionDisabledPriority = input.ReadInt32();
            break;
          }
          case 4832: {
            DestroyTick = input.ReadUInt32();
            break;
          }
          case 4840: {
            RespawnTick = input.ReadUInt32();
            break;
          }
          case 4848: {
            NoDamageTick = input.ReadUInt32();
            break;
          }
          case 5600: {
            Hp = input.ReadInt64();
            break;
          }
          case 5608: {
            Mp = input.ReadInt64();
            break;
          }
          case 5616: {
            Shield = input.ReadInt64();
            break;
          }
          case 5624: {
            Sp = input.ReadInt64();
            break;
          }
          case 5632: {
            SpRegenTick = input.ReadUInt32();
            break;
          }
          case 5640: {
            Guard = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
