// <auto-generated>
//  This code was generated by a tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
// </auto-generated>
using Commons.Packets.Updates;

namespace Commons.Game
{
    public partial class GameBoard
    {
        partial void ServerHandleUpdate(BoardPlayerUpdate update);
        partial void ServerHandleUpdate(BoardAchievementUpdate update);
        partial void ServerHandleUpdate(BoardPlayerInventoryMergeUpdate update);
        partial void ServerHandleUpdate(BoardPlayerInventorySpawnUpdate update);
        partial void ServerHandleUpdate(BoardPlayerInventoryMoveUpdate update);
        partial void ServerHandleUpdate(BoardPlayerInventoryTransferUpdate update);
        partial void ServerHandleUpdate(BoardPlayerInventoryExpandUpdate update);
        partial void ServerHandleUpdate(BoardPlayerInventoryResetHoldUpdate update);
        partial void ServerHandleUpdate(VariableUpdate update);
        partial void ServerHandleUpdate(SelectTraitUpdate update);
        partial void ServerHandleUpdate(CompleteSelectTraitUpdate update);
        partial void ServerHandleUpdate(BoardStateUpdate update);
        partial void ServerHandleUpdate(BoardPlayerRunCheatUpdate update);
        partial void ServerHandleUpdate(RerollSelectTraitUpdate update);
        partial void ServerHandleUpdate(BoardPlayerInventoryRootingUpdate update);

        private partial void HandleUpdateInternal(BoardPlayerUpdate update);
        private partial void HandleUpdateInternal(BoardAchievementUpdate update);
        private partial void HandleUpdateInternal(BoardPlayerInventoryMergeUpdate update);
        private partial void HandleUpdateInternal(BoardPlayerInventorySpawnUpdate update);
        private partial void HandleUpdateInternal(BoardPlayerInventoryMoveUpdate update);
        private partial void HandleUpdateInternal(BoardPlayerInventoryTransferUpdate update);
        private partial void HandleUpdateInternal(BoardPlayerInventoryExpandUpdate update);
        private partial void HandleUpdateInternal(BoardPlayerInventoryResetHoldUpdate update);
        private partial void HandleUpdateInternal(VariableUpdate update);
        private partial void HandleUpdateInternal(SelectTraitUpdate update);
        private partial void HandleUpdateInternal(CompleteSelectTraitUpdate update);
        private partial void HandleUpdateInternal(BoardStateUpdate update);
        private partial void HandleUpdateInternal(BoardPlayerRunCheatUpdate update);
        private partial void HandleUpdateInternal(RerollSelectTraitUpdate update);
        private partial void HandleUpdateInternal(BoardPlayerInventoryRootingUpdate update);

        private partial bool HandleUpdateInternal(IBoardUpdate update)
        {
            switch (update)
            {
               case BoardPlayerUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case BoardAchievementUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case BoardPlayerInventoryMergeUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case BoardPlayerInventorySpawnUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case BoardPlayerInventoryMoveUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case BoardPlayerInventoryTransferUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case BoardPlayerInventoryExpandUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case BoardPlayerInventoryResetHoldUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case VariableUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case SelectTraitUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case CompleteSelectTraitUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case BoardStateUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case BoardPlayerRunCheatUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case RerollSelectTraitUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
               case BoardPlayerInventoryRootingUpdate u:
                   ServerHandleUpdate(u);
                   HandleUpdateInternal(u);
                   break;
                default:
                    Config.LogError($"GameBoard.HandleUpdate: unhandled update type {update.GetType()}");
                    return false;
            }

            return true;
        }
    }
}
